### ISSUE TITLE
Gif support

### ISSUE THREAD

**Issue by yosun** [yasirkula/UnityNativeGallery#1]
is animated gif save to gallery supported

**Comment by yasirkula** [comment]
I've downloaded [this gif](https://imgur.com/DfQqM) to StreamingAssets folder of my Android project and successfully saved it to gallery on Galaxy S3 using the following code:

```csharp
using UnityEngine;
using System.Collections;
using System.IO;

public class GifTest : MonoBehaviour 
{
	IEnumerator Start()
	{
		WWW www = new WWW( Path.Combine( Application.streamingAssetsPath, "DfQqM.gif" ) );
		yield return www;
		
		string path = Path.Combine( Application.temporaryCachePath, "test.gif" );
		File.WriteAllBytes( path, www.bytes );
		
		NativeGallery.SaveToGallery( path, "Gif Test", "test.gif", true );
	}
}
```

Basically, it copies the gif from StreamingAssets to a temporary location (as StreamingAssets can't be accessed directly on Android) and then saves this extracted image to the gallery.
