### ISSUE TITLE
iOS 13 issue with video paths - possible dublicate of issue #73

### ISSUE THREAD

**Issue by Marcurion** [yasirkula/UnityNativeGallery#101]
Related to #73 

We encountered the issue with the not usable paths with the latest Asset Store build.
However even though most of our custom code cant access the file, Handheld.PlayFullScreenMovie works even on iOS 13.3.

Can be replicated with a simple modification of the Example script from https://github.com/yasirkula/UnityNativeGallery

```
private void PickVideo()
{
	NativeGallery.Permission permission = NativeGallery.GetVideoFromGallery( ( path ) =>
	{
		Debug.Log( "Video path: " + path );
		if( path != null )
		{
			StartCoroutine(AccessDelayed(path));
			// Play the selected video
			//Handheld.PlayFullScreenMovie( "file://" + path );        // Works for some reason
			Debug.Log(File.Exists(path));                              // iOS 12.4.3: true iOS 13.3: false
			Debug.Log(File.Exists("file://" + path));                  // Always false

		}
	}, "Select a video" );

	Debug.Log( "Permission result: " + permission );
}




private IEnumerator AccessDelayed(string path)
{
	
	yield return new WaitForSeconds(5.0f);
	Debug.Log(File.Exists(path));                              // iOS 12.4.3: true iOS 13.3: false
	Debug.Log(File.Exists("file://" + path));                  // Always false

}
```

Debug log of the video path:

iOS 12.4.3
`iPhonePlayer(iPhone):56000 Video path: /private/var/mobile/Containers/Data/Application/EFF7B421-6EFC-4C95-9632-C6365DCB1BBF/tmp/5E3645C1-4044-4FCC-82BB-92D508F71148.MOV`
iOS 13.3
`iPhonePlayer(iPhone):56000 Video path: /private/var/mobile/Containers/Data/PluginKitPlugin/61591049-8272-4F91-AF8B-4B2B5301F90F/tmp/trim.62ADAF7C-297D-4061-B364-400C1BDC7A23.MOV`

Some related fixes I came across:

https://stackoverflow.com/questions/57798968/didfinishpickingmediawithinfo-returns-different-url-in-ios-13
https://github.com/apache/cordova-plugin-camera/issues/506#issuecomment-534070130

**Comment by yasirkula** [comment]
I'm not sure why this section of the code isn't working for you: https://github.com/yasirkula/UnityNativeGallery/blob/890f22792fb59fd40547c9a9ff0d388fec861b8c/Plugins/NativeGallery/iOS/NativeGallery.mm#L571-L591

Are there any error messages? I don't know what `__IPHONE_OS_VERSION_MAX_ALLOWED` corresponds to in Xcode but maybe its value is lower than iOS 13?

**Comment by Marcurion** [comment]
Thank you for your fast response...
I have an assumption: We are still using XCode 10.0 and __IPHONE_OS_VERSION_MAX_ALLOWED is checked at compile time.
So I will try compiling with XCode 11.
Will report my findings back, thank you for pointing out the relevant code section

**Comment by Marcurion** [comment]
The problem was indeed solved by compiling with latest XCode 11

**Comment by yasirkula** [comment]
Thanks for letting me know. I've learnt not to depend on `__IPHONE_OS_VERSION_MAX_ALLOWED` 😄
