### ISSUE TITLE
taking a screenshot with a device camera open (AR)

### ISSUE THREAD

**Issue by shacharoz** [yasirkula/UnityNativeGallery#103]
do you have an idea how should i use NativeGallery together with a device camera that is already open and being used (such as AR cases)?

to be specific i am using AR Foundation with Unity.

YOU HAVE MADE A FANTASTIC JOB with your code: NativeShare, NativeCamera and NativeGallery.
if you would like to accept my offer, i would be happy to create sample project of examples (you wrote the sample code but i think people would appreciate a sample with all the definitions already inside).

**Comment by yasirkula** [comment]
If the TakeScreenshotAndSave function in the example code is not working, then I'm not sure how to capture a screenshot.

Thank you for your kind words, feel free to create a sample project with my plugins 😄 But I'm not planning to add a sample scene to the plugin itself, so please don't expect the sample project to be merged into the master branch.

**Comment by shacharoz** [comment]
ah, you think that TakeScreenshotAndSave() already supposed to work even with the camera is open?
mm. ok i will try again to validate.
