### ISSUE TITLE
Screenshot of custom size

### ISSUE THREAD

**Issue by mohsinkhan26** [yasirkula/UnityNativeGallery#104]
```
Texture2D ss = new Texture2D( Screen.width, Screen.height, TextureFormat.RGB24, false );
	ss.ReadPixels( new Rect( 0, 0, Screen.width, Screen.height ), 0, 0 );
	ss.Apply();
```
I replaced above lines with this

```
[SerializeField] RectTransform screenshotRect;

// then in IEnumerator TakeScreenshotAndSave()
Texture2D ss = new Texture2D((int)screenshotRect.rect.width, (int)screenshotRect.rect.height, TextureFormat.RGB24, false);
            ss.ReadPixels(new Rect(0, 0, screenshotRect.rect.width, screenshotRect.rect.height), 0, 0);
            ss.Apply();
this.Log("TakeScreenshotAndSave Resolution-Width: " + ss.width + "   Height: " + ss.height
                + "\nWidth: " + screenshotRect.rect.width + "   Height: " + screenshotRect.rect.height);

// Log result is
// TakeScreenshotAndSave Resolution-Width: 1824   Height: 1793
// Width: 1824.945   Height: 1793.125
```

It captures that much area, but NOT with the actual content. I mean the screenshot taken is in light grey color totally. Have a look at the image attached, this is the result
![20200304200503](https://user-images.githubusercontent.com/28417925/75965195-6d35bb80-5f03-11ea-8763-85fbf4aba5b0.png)

Any workaround? Am I doing something wrong?

**Comment by yasirkula** [comment]
I can't explain why it is all grey but make sure that CanvasScaler's "Ui Scale Mode" is set to "Constant Pixel Size". If screenshotRect isn't located at the bottom left corner of the screen, then the first two parameters at `new Rect(0, 0, screenshotRect.rect.width, screenshotRect.rect.height)` should be changed to offset the screenshot area.

In any case, this is not really related to NativeGallery, so I'm closing this issue. Please google "unity take partial screenshot" for more topics about this issue.

**Comment by mohsinkhan26** [comment]
No, I mean the resolution is exactly the same as I wanted (you can check the log and its result). But without the content, I mean I was taking the screenshot of my game using this plugin and it resulted in this grey image.

**Comment by yasirkula** [comment]
The screenshot function that I'm using isn't special to NativeGallery, which is what I'm saying; it is a standard way of capturing a screenshot without using ScreenCapture.CaptureScreenshot.

You can try displaying the screenshot on a RawImage to see if it is grey there, as well. If it is not, then this issue is indeed related to screenshot becoming grey while being saved to Gallery with NativeGallery and I can take a look at that. Otherwise, the proper place to ask for help for this issue is [Unity forums](https://forum.unity.com/forums/scripting.12/).

**Comment by mohsinkhan26** [comment]
Sorry, those lines work. The thing is, in screenspace, the bounds are different than the actual screen size.

And obviously, not related to this plugin, sorry!

**Comment by yasirkula** [comment]
It shouldn't be when CanvasScaler's "Ui Scale Mode" is set to "Constant Pixel Size". In the worst case, RectTransformUtility.GetWorldCorners and Camera.WorldToScreenPoint should work.
