### ISSUE TITLE
Project Settings are changed after Build & are reseted after Playing In Editor

### ISSUE THREAD

**Issue by andrewio** [yasirkula/UnityNativeGallery#106]
There is annoying issue for git vcs.

Next 2 string are added to ProjectSettings.asset when I am building & they are removed when I test my project in Editor. I guess it is related with your Asset, because when building related files are loaded. 

Am I right? Can you make something with it? 
So ideal case: these string are added only once and are never deleted again.

  bundleVersion: 1
  preloadedAssets:
    {fileID: 4800000, guid: e7c77f6eaab324a819efdc13b8125a39, type: 3}
  **_{fileID: 2784158946544396181, guid: fb648f864e7b64e9c84dd099be2ea5ec, type: 2}
  {fileID: 4800000, guid: c9f956787b1d945e7b36e0516201fc76, type: 3}_**
  metroInputSource: 0
  wsaTransparentSwapchain: 0
  m_HolographicPauseOnTrackingLoss: 1

**Comment by yasirkula** [comment]
I haven't experienced this issue myself. I don't alter Project Settings in any way in my scripts, this must be Unity's doing.

**Comment by andrewio** [comment]
> I haven't experienced this issue myself. I don't alter Project Settings in any way in my scripts, this must be Unity's doing.

Hmm, I haven't experienced that Unity behaves such on other projects without your plugin.

**Comment by yasirkula** [comment]
I am not manually modifying Project Settings in any way, so I'm closing this Issue. This is really out of my hands.

**Comment by andrewio** [comment]
> I am not manually modifying Project Settings in any way, so I'm closing this Issue. This is really out of my hands.

I checked this point in Editor, really, this is ARCore behavior. Thank you for answers.
