### ISSUE TITLE
iOS pickup video , Auto compressed to H265?

### ISSUE THREAD

**Issue by oOtroyOo** [yasirkula/UnityNativeGallery#107]
I want to pickup a video and upload to website and play on web .  on iOS ,it has been compressed to H265 . witch is not compatible to most browsers (sound only). 

 Can I change that to H264?

by the way .
Is there any methods to compress video on Android ?

**Comment by yasirkula** [comment]
Video can't be compressed with NativeGallery on Android. If it was up to me, I wouldn't compress the picked video on iOS either but this is done automatically by iOS and there is no way to skip it.

You may be able to change the compression format, though. You can try commenting out these lines, for example: https://github.com/yasirkula/UnityNativeGallery/blob/8c8139ac393d226144ff26d4cde9ca7f6d687ba7/Plugins/NativeGallery/iOS/NativeGallery.mm#L314-L318

If it doesn't work, try giving `imagePicker.videoExportPreset` a different value.
