### ISSUE TITLE
AndroidVideoMedia: Error opening extractor: -10002 

### ISSUE THREAD

**Issue by andrewio** [yasirkula/UnityNativeGallery#108]
Hi, I have black texture when I try to load Video to Render Texture and Play with default VideoPlayer class by Unity. iOS works great, but on Android there is some issue. 

What the problem?

Environment:
Unity 2019.3.5f, Android 10, Samsung Galaxy A71.

So picked Video was recorder on this device previously.

Here ADB LOG:
```
9633 I Unity   : onResume
03-20 15:08:50.412  9633  9660 D Unity   : SetWindow 0 0x7c46bb8010
03-20 15:08:50.412  9633  9660 D Unity   : SetWindow 0 0x7c46bb8010
03-20 15:08:50.421  9633  9633 I Unity   : windowFocusChanged: true
03-20 15:08:50.421  9633  9660 D Unity   : [EGL] Attaching window :0x7c46bb8010
03-20 15:08:50.445  9633  9660 D Unity   : ANativeWindow: (1080/2307) RequestedResolution: (0/0) RenderingResolution: (0/0) EGLSurface: (1080/2307)
03-20 15:08:50.446  9633  9660 I Unity   : 2222 
03-20 15:08:50.446  9633  9660 I Unity   : (Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)
03-20 15:08:50.446  9633  9660 I Unity   : 
03-20 15:08:50.466  9633  9660 D Unity   : Sensor :        Accelerometer ( 1) ; 0.002394 / 0.00s ; icm4x6xx Accelerometer Non-wakeup / TDK-Invensense 
03-20 15:08:50.473  9633  9660 D Unity   : Choreographer available: Enabling VSYNC timing
03-20 15:08:50.587  9633  9660 I Unity   : Video Path: /storage/emulated/0/DCIM/Camera/20200318_230630.mp4
03-20 15:08:50.587  9633  9660 I Unity   : MediaControl:<PickVideo>b__7_0(String)
03-20 15:08:50.587  9633  9660 I Unity   : MediaPickCallback:Invoke(String)
03-20 15:08:50.587  9633  9660 I Unity   : NativeGalleryNamespace.NGMediaReceiveCallbackAndroid:MediaReceiveCallback(String)
03-20 15:08:50.587  9633  9660 I Unity   : System.Action:Invoke()
03-20 15:08:50.587  9633  9660 I Unity   :  
03-20 15:08:50.587  9633  9660 I Unity   : (Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)

03-20 15:08:50.609  9633  9660 I Unity   : MediaPickCallback:Invoke(String)
03-20 15:08:50.609  9633  9660 I Unity   : NativeGalleryNamespace.NGMediaReceiveCallbackAndroid:MediaReceiveCallback(String)
03-20 15:08:50.609  9633  9660 I Unity   : System.Action:Invoke()
03-20 15:08:50.609  9633  9660 I Unity   :  
03-20 15:08:50.609  9633  9660 I Unity   : (Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)
03-20 15:08:50.609  9633  9660 I Unity   : 
**03-20 15:08:50.609  9633  9675 W Unity   : AndroidVideoMedia: Error opening extractor: -10002** 
03-20 15:08:50.609  9633  9675 W Unity   : (Filename: ./PlatformDependent/AndroidPlayer/Modules/Video/Private/AndroidVideoMedia.cpp Line: 469)
```

**Comment by yasirkula** [comment]
I don't find VideoPlayer stable on Android, especially on low-end devices. So, I don't think that this issue is caused by NativeGallery. Please check if `/storage/emulated/0/DCIM/Camera/20200318_230630.mp4` plays without any issues when opened via device's file browser. If so, this issue is caused by VideoPlayer.

**Comment by andrewio** [comment]
Yes, Video is played from File Browser & with Quick Time on Mac OS.

Here meta info, if it makes sense:

<img width="591" alt="Screenshot 2020-03-20 at 21 23 28" src="https://user-images.githubusercontent.com/5120782/77194583-4b3a5c80-6af1-11ea-971f-e3981aa8e4c6.png">

<img width="595" alt="Screenshot 2020-03-20 at 21 23 55" src="https://user-images.githubusercontent.com/5120782/77194595-4ecde380-6af1-11ea-81c5-345e529254c4.png">

**Comment by yasirkula** [comment]
As I said, it means that this is a VideoPlayer bug, not NativeGallery issue. Googling "Error opening extractor: -10002" yields a number of hits, you may find them useful.

**Comment by andrewio** [comment]
> As I said, it means that this is a VideoPlayer bug, not NativeGallery issue. Googling "Error opening extractor: -10002" yields a number of hits, you may find them useful.

Thank you. After some hours of researching I got facepalm. 

Error can be fixed by deleting "file://" prefix from path.

Android:
Wrong path: "file:///storage/emulated/0/DCIM/Camera/20200318_230630.mp4"
Right Path: "/storage/emulated/0/DCIM/Camera/20200318_230630.mp4"

iOS: doesn't matter. Both path types are working.

**Comment by yasirkula** [comment]
Glad it is working ^^
