### ISSUE TITLE
Android Emulator permisson

### ISSUE THREAD

**Issue by mertct11** [yasirkula/UnityNativeGallery#109]
Selam,
Öncelikle geliştirme için teşekkürler, bir sorum olacak.screen shot alma ile ilgili örnek kodu ve scriptleri projeme ekledim unityde çalıştırdığımda izin durumu : granted , screen shot save succesfully. Gibi logları aldım. Fakat genymotion a apk alıp attığımda save buttonuna bastıgımda izin ile ilgili bir şey sormasını bekledim fakat sormadı ve gallery e fotoğraf kaydetmedi. Emulator oldugu için logları nereden okuyacağımı da bilemedim. Yardımcı olur musunuz? 

Hi,
First of all, thanks for the development, I have a question. I have added sample code and scripts for taking screen shots to my project. When I run unity permission status: granted, screen shot save succesfully. I got the logs like. But when I took the apk to genymotion and pressed the save button, I waited for him to ask about the permission, but he did not ask and did not save the photo to the gallery. Since it is an emulator, I did not know where to read the logs. Could you help?

**Comment by yasirkula** [comment]
Eğer Player Settings'te Write Permission'ı External (SD Card) yapmadıysanız yapın. Eğer zaten yaptıysanız, logcat log'larını görmeden kesin bir şey diyemeyeceğim. Bunun için google'a "genymotion logcat" yazınca şöyle bir şey çıktı belki işinize yarar: https://www.quora.com/How-do-I-view-app-logs-running-on-a-Genymotion-emulator-virtual-device

**Comment by mertct11** [comment]
Player settings ten write permisson u external cd yapınca oldu çok teşekkürler
