### ISSUE TITLE
Function name conflict with other plugin.

### ISSUE THREAD

**Issue by foundway** [yasirkula/UnityNativeGallery#11]
Hi,

While UnityNativeGallery working great and we all loved it. We noticed a conflict with other plugins (i.e.  https://assetstore.unity.com/packages/tools/integration/image-and-video-picker-28597). Our theory is that both plugin has static extern function called _PickImage. Does anyone know a way to workaround this?

**Comment by yasirkula** [comment]
You should change the name of _PickImage in both Plugins/NativeGallery/NativeGallery.cs and  Plugins/NativeGallery/iOS/NativeGallery.mm.

**Comment by yasirkula** [comment]
Added _NativeGallery prefix to all iOS functions with the latest commit f0f9b2af94334d9a5cff4725995c13c19691cf71
