### ISSUE TITLE
I think the better way on Android is to request permission when needed.

### ISSUE THREAD

**Issue by Schrodinger123** [yasirkula/UnityNativeGallery#113]
Awesome work with this plugin, but I think it's not a good way to ask premissions when player launch the game first time, If you set Write Permission to External in player settings.

I just add this to my game:

`
Permission permission = NativeGallery.SaveImageToGallery(screenshot, "blablabla", System.DateTime.Now.ToString("MMMM-yyyy-HH:mm:ss") + ".jpg");
        if (permission == Permission.Denied)
        {
            Debug.Log("Denied");

#if !UNITY_EDITOR && UNTIY_ANDROID
            if (!UnityEngine.Android.Permission.HasUserAuthorizedPermission(UnityEngine.Android.Permission.ExternalStorageWrite))
            {
                UnityEngine.Android.Permission.RequestUserPermission(UnityEngine.Android.Permission.ExternalStorageWrite);
            }
#endif
        }
        else if (permission == Permission.Granted)
        {
            Debug.Log("Granted");
        }
        else if (permission == Permission.ShouldAsk)
        {
            Debug.Log("ShouldAsk");
        }
`

Now, I turn my Write Permission back to Internal so it won't ask when I launch game, and it will ask premission when you don't have it.

Hope you can add this to plugin, then Android don't even need to setup XDDD

**Comment by yasirkula** [comment]
Unity automatically requests permissions at startup (not NativeGallery) but you can change this behaviour by adding a SkipPermissionsDialog metadata to AndroidManifest: https://docs.unity3d.com/Manual/android-manifest.html
