### ISSUE TITLE
Saving video on iOS problem

### ISSUE THREAD

**Issue by Hitomilras** [yasirkula/UnityNativeGallery#114]
Hello.

I trying to save video on iOS and get error in some thread.
Something  like  a "Bad access" (i will  update this thread with more information tomorow).

My team already created project using UnityNativeGallery, and saving video on iOS worked great :)

May be i  did something wrong?
Does saving video on iOS is officially supported?

**Comment by yasirkula** [comment]
Closed due to inactivity (missing logs).
