### ISSUE TITLE
a little question

### ISSUE THREAD

**Issue by 14king** [yasirkula/UnityNativeGallery#116]
hi guys ,where is NativeGallery.jar source project?  or can u add a method that we can open the phone album directly ? thx

**Comment by yasirkula** [comment]
It is available here: https://github.com/yasirkula/UnityNativeGallery/tree/master/.github/JAR%20Source

**Comment by 14king** [comment]
> It is available here: https://github.com/yasirkula/UnityNativeGallery/tree/master/.github/JAR%20Source

thx guys
