### ISSUE TITLE
NativeGallery.LoadImageAtPath load failed.

### ISSUE THREAD

**Issue by dw8869** [yasirkula/UnityNativeGallery#118]
Hello,

Follow the example well, but load failed.
NativeGallery.LoadImageAtPath ->Texutre2D is null..

log:
05-08 12:44:32.036: E/Unity(23972): UnauthorizedAccessException: Access to the path "/storage/emulated/0/DCIM/Screenshots/Screenshot_20200507.jpg" is denied.
05-08 12:44:32.036: E/Unity(23972):   at System.IO.FileStream..ctor (System.String path, System.IO.FileMode mode, System.IO.FileAccess access, System.IO.FileShare share, System.Int32 bufferSize, System.Boolean anonymous, System.IO.FileOptions options) [0x0019e] in <567df3e0919241ba98db88bec4c6696f>:0 
05-08 12:44:32.036: E/Unity(23972):   at System.IO.FileStream..ctor (System.String path, System.IO.FileMode mode, System.IO.FileAccess access, System.IO.FileShare share) [0x00000] in <567df3e0919241ba98db88bec4c6696f>:0 
05-08 12:44:32.036: E/Unity(23972):   at (wrapper remoting-invoke-with-check) System.IO.FileStream..ctor(string,System.IO.FileMode,System.IO.FileAccess,System.IO.FileShare)
05-08 12:44:32.036: E/Unity(23972):   at System.IO.File.OpenRead (System.String path) [0x00000] in <567df3e0919241ba98db88bec4c6696f>:0 
05-08 12:44:32.036: E/Unity(23972):   at System.IO.File.ReadAllBytes (System.String path) [0x00000] in <567df3e0919241ba98db88bec4c6696f>:0 
05-08 12:44:32.036: E/Unity(23972):   at NativeGallery.LoadImageAtPath (System.String imagePath, System.Int32 maxSize, Syst
05-08 12:44:32.683: E/Unity(23972): OPENGL NATIVE PLUG-IN ERROR: GL_OUT_OF_MEMORY: Not enough memory left to execute command
05-08 12:44:32.683: E/Unity(23972):  
05-08 12:44:32.683: E/Unity(23972): (Filename: ./Runtime/GfxDevice/opengles/GfxDeviceGLES.cpp Line: 348)

**Comment by yasirkula** [comment]
If you are testing on an emulator, also try testing on a real device. At the moment, I don't know why this issue might be occurring.

**Comment by yasirkula** [comment]
In addition to the maxSize tweak above, can you check if the file's full path is "/storage/emulated/0/DCIM/Screenshots/Screenshot_20200507.jpg" and not something else? You may have to use a file browser app to see the full path.

**Comment by dw8869** [comment]
Maybe conflict between the plugins.
Solved this problem.

**Comment by dw8869** [comment]
Testing on real device, correct path.
I don't know why this problem.
But, I moved to a new project and solved it.

**Comment by yasirkula** [comment]
Glad to hear it! Feel free to reopen the issue when it happens again. In that case, please also provide [this info](https://github.com/yasirkula/UnityNativeGallery/issues/118#issuecomment-626606551).
