### ISSUE TITLE
Undefined symbols for architecture arm64:

### ISSUE THREAD

**Issue by soqman** [yasirkula/UnityNativeGallery#12]
Undefined symbols for architecture arm64:
  "__ScreenshotWriteToAlbum", referenced from:
      _NativeGallery__ScreenshotWriteToAlbum_m1836878830 in Bulk_Assembly-CSharp-firstpass_0.o
      _NativeGallery_SaveToGallery_m178977206 in Bulk_Assembly-CSharp-firstpass_0.o
     (maybe you meant: _NativeGallery__ScreenshotWriteToAlbum_m1836878830)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by yasirkula** [comment]
_ScreenshotWriteToAlbum was renamed in a recent update. I am guessing that deleting the Plugins/NativeGallery folder and then reimporting the plugin will solve the issue. Also make sure that you deselect *Append* for the first build after reimporting the plugin.
