### ISSUE TITLE
Unity Package Manager Page - Links are not working

### ISSUE THREAD

**Issue by andrewio** [yasirkula/UnityNativeGallery#120]
Hi, next links are not working in Unity Package Manager Page:

- View documentation
- View changelog
- View licenses

Screenshot: http://joxi.ru/nAyOVGptj09Yxm

Please, fix it.

Best Regards.

**Comment by yasirkula** [comment]
Thank you for the feedback.

As far as I understand, these files need to be inside a `Documentation~` folder but I'm not planning to change the layout of the plugin. Currently, all files reside inside Plugins/NativeGallery, similar to Asset Store and NativeGallery.unitypackage layout and I'm happy with that. There is already a README.txt file inside Plugins/NativeGallery, keeping a duplicate inside `Documentation~` is not something I'm considering.

When Package Manager supports reading the documentation, changelog and license urls from package.json, I can add these urls. Until then, we can keep this Issue open.

**Comment by yasirkula** [comment]
From [2020.2 changelog](https://unity3d.com/unity/whats-new/2020.2.0):

> Package Manager: Added changelogUrl and licensesUrl as optional properties that can be specified in the package.json of a custom package. If specified, the auto-generated changelog and license links will be replaced with custom URLs.

I guess the only thing missing now is the ability to customize *View documentation*.

**Comment by yasirkula** [comment]
I've added **documentationUrl**, **changelogUrl** and **licensesUrl** to [TextureOps' package.json](https://github.com/yasirkula/UnityTextureOps/blob/master/package.json). "documentationUrl" should work on 2020.1+ and the rest should work on 2020.2+. Can you give it a try and let me know if it works? Then, I'll make this change on all my repositories.

**Comment by andrewio** [comment]
It Works for Unity 2021.1, but for changelog this link is more appropriate as I can see: https://github.com/yasirkula/UnityTextureOps/releases

**Comment by yasirkula** [comment]
It's a tough choice. Releases do have version labels but don't necessarily mention all the changes that are shown in commits page. But I guess having version labels makes more sense.
