### ISSUE TITLE
Multiple Selection From Gallery [Feature Request]

### ISSUE THREAD

**Issue by ctykaya** [yasirkula/UnityNativeGallery#121]
Hello yasirkula, 

We used this plugin in some many different projects so thanks for developing it. Is it possible to add some new features such as multiple selection from gallery. User can select multiple images from their gallery.  Thanks.

**Comment by yasirkula** [comment]
You can use GetImagesFromGallery and GetVideosFromGallery on Android: https://github.com/yasirkula/UnityNativeGallery#b-retrieving-media-from-galleryphotos. This feature is not supported on iOS and old Android versions.
