### ISSUE TITLE
In the test capture, within the'pickImage (int maxSize)' function How is the'path' of the permission specified?

### ISSUE THREAD

**Issue by Seul9** [yasirkula/UnityNativeGallery#122]
When capturing an image or video with ios, I want to know the saved path.

Unknown paths are identified during the debug test.
Could you help me?

The debug log is as follows.

<img width="565" alt="스크린샷 2020-06-18 오후 4 47 17" src="https://user-images.githubusercontent.com/66583923/84992839-674aaa00-b183-11ea-81bc-22aabfc680a4.png">
<img width="833" alt="스크린샷 2020-06-18 오후 4 43 21" src="https://user-images.githubusercontent.com/66583923/84992851-6c0f5e00-b183-11ea-8958-453b898668bc.png">

**Comment by yasirkula** [comment]
You need to look at the log that starts with "Image path:". I don't know why there is a log that starts with "callback:".

**Comment by Seul9** [comment]
> "이미지 경로 :"로 시작하는 로그를 확인해야합니다. 왜 "콜백 :"으로 시작하는 로그가 있는지 모르겠습니다.
Thank you for answer.


The path starting with'image path: 'is:

However, the middle underline is changed every time I debug, so I don't know if this is the correct path.

Where is this route coming from?
<img width="853" alt="스크린샷 2020-06-18 오후 5 16 22" src="https://user-images.githubusercontent.com/66583923/84996151-db874c80-b187-11ea-9058-05e5b3deecd4.png">

**Comment by yasirkula** [comment]
Here: https://github.com/yasirkula/UnityNativeGallery/blob/4d987032836d0059060c3e73366bbc041be58a6c/Plugins/NativeGallery/NativeGallery.cs#L141

That whole path is simply Application.temporaryCachePath. I don't know if it is normal for the middle part to change everytime.

**Comment by Seul9** [comment]
If so, is that path the last one saved?

`
private static string SelectedVideoPath
	{
		get
		{
			if( m_selectedVideoPath == null )
			{
				m_selectedVideoPath = Path.Combine( Application.temporaryCachePath, "pickedVideo" );
				Directory.CreateDirectory( Application.temporaryCachePath );
			}

			return m_selectedVideoPath;
		}
`

**Comment by yasirkula** [comment]
Yes, the same path is used until you quit the game and then restart it. Only the extension of the path can change.
