### ISSUE TITLE
PBXProject.GetUnityTargetName doesn't work with Unity 2019.4

### ISSUE THREAD

**Issue by hippogamesunity** [yasirkula/UnityNativeGallery#123]
https://docs.unity3d.com/ScriptReference/iOS.Xcode.PBXProject.GetUnityTargetName.html

**Comment by hippogamesunity** [comment]
This line should be fixed:
string targetGUID = pbxProject.TargetGuidByName( PBXProject.GetUnityTargetName() );

**Comment by yasirkula** [comment]
GetUnityTargetName shouldn't execute on 2019.3 or later, you may be using an older version of the plugin:

https://github.com/yasirkula/UnityNativeGallery/blob/4d987032836d0059060c3e73366bbc041be58a6c/Plugins/NativeGallery/Editor/NGPostProcessBuild.cs#L31-L35

**Comment by hippogamesunity** [comment]
Yes, I'm on the old version. Sorry.
