### ISSUE TITLE
ArgumentException: Texture '' is not readable, the texture memory can not be accessed from scripts. You can make the texture readable in the Texture Import Settings.

### ISSUE THREAD

**Issue by AdelKanso** [yasirkula/UnityNativeGallery#125]
i'm using get image from gallery.
i got the image and set it to image ui , and this works well.
but i want to convert the texture (imageUI texture, or the incoming texture from gallery) to base64 so while testing on android this error came : "ArgumentException: Texture '' is not readable, the texture memory can not be accessed from scripts. You can make the texture readable in the Texture Import Settings."
i'm using this code to convert texture to base64:
string base64image=Convert.ToBase64String(texture.EncodeToPNG());

**Comment by yasirkula** [comment]
You should set the markTextureNonReadable parameter of LoadImageAtPath to false.

**Comment by AdelKanso** [comment]
Thank you.
