### ISSUE TITLE
test project doesnt work from some reason

### ISSUE THREAD

**Issue by shacharoz** [yasirkula/UnityNativeGallery#126]
1. set up a new unity empty project.
2. clean import native gallery package from asset store.
3. to the main camera, I add a new script that has this code:

public UnityEngine.UI.Text logger;
public void SaveScreenNow()
    {
        logger.text = "Permission 1: " + NativeGallery.RequestPermission();

        StartCoroutine(TakeScreenshotAndSave());
    }

    private IEnumerator TakeScreenshotAndSave()
    {
        yield return new WaitForEndOfFrame();

        Texture2D ss = new Texture2D(Screen.width, Screen.height, TextureFormat.RGB24, false);
        ss.ReadPixels(new Rect(0, 0, Screen.width, Screen.height), 0, 0);
        ss.Apply();

        // Save the screenshot to Gallery/Photos
        logger.text = "Permission 2: " + NativeGallery.SaveImageToGallery(ss, "GalleryTest", "Image.png", NativeGalleryError);

        // To avoid memory leaks
        Destroy(ss);
    }
    private void NativeGalleryError(string result_error)
    {
        Debug.Log(result_error);
        logger.text = result_error;
    }

4. this is your code copied from the readme. 
5. I add a button and connect OnClick to SaveScreenNow()
6. i add a text field and link it to the logger field.

when i run this app on the unity editor, everything works as expected.
when i install it on the phone, it says that the permission is granted , but i cant find the image.
i can see a new folder called GalleryTest on my file manager, but it is empty from images.

any ideas what could get wrong? if you want i can send here the project files.

**Comment by yasirkula** [comment]
Can you use logcat and see if there are any meaningful error messages there?

**Comment by yasirkula** [comment]
Closed due to inactivity.
