### ISSUE TITLE
Asset stopped working. Not asking for permissions.

### ISSUE THREAD

**Issue by GeorgeMincila** [yasirkula/UnityNativeGallery#127]
Hi,

I have been using your asset in my app for a while now. It seems to not be working in my case anymore. 

This, below comes out as "Denied"
`NativeGallery.Permission permission = NativeGallery.CheckPermission();`

This, below, get's called but nothing happens.
`permission = NativeGallery.RequestPermission();`

Any idea what is happening?

Thank you,
George

**Comment by yasirkula** [comment]
The WRITE_EXTERNAL_STORAGE permission may have been removed from your AndroidManifest.xml in an update or you may have denied the Storage permission with Don't Ask Again selected by mistake.

**Comment by GeorgeMincila** [comment]
Appreciate the quick reply. Indeed, I found the Permissions to be Denied in the Settings > Apps section. I do not remember ever denying it, but who knows, maybe at some point.

As far as I understand, there is not way of requesting again from the app when this is the case and I have to instruct users to manually allow it.

**Comment by yasirkula** [comment]
When user selects "Don't ask again", yes. In addition to briefing the user about the permission, you can also call `NativeGallery.OpenSettings()` to directly open app's permission Settings (also see [NativeGallery.CanOpenSettings](https://github.com/yasirkula/UnityNativeGallery#c-runtime-permissions)).

**Comment by GeorgeMincila** [comment]
Oh, that sounds nice. Appreciate the suggestion. Will do just that.
