### ISSUE TITLE
Is there a workaround for loading audio files?

### ISSUE THREAD

**Issue by ffarall** [yasirkula/UnityNativeGallery#129]
I'm trying to find a plugin for calling the native file pickers on iOS and Android, to load audio files into my app. From what I read, it'd be a similar functionality to this one, but for audio files instead of videos/photos. Do you know of a workaround for it? Like maybe changing the MIME type or something like that.
The native file pickers that I'm trying to open look like this:
![WhatsApp Image 2020-07-26 at 22 17 12](https://user-images.githubusercontent.com/37149322/88497810-cdeb9080-cf97-11ea-9800-e0922e2232ec.jpeg)
On iOS.

![WhatsApp Image 2020-07-26 at 23 21 23](https://user-images.githubusercontent.com/37149322/88497813-cf1cbd80-cf97-11ea-8f20-648ef73cfa1e.jpeg)
On Android.

**Comment by yasirkula** [comment]
On Android, NativeGallery has a _GetAudioFromGallery_ function but it is _private_ because it is not supported on iOS and I am not planning to fix any issues (if any) with that function. Feel free to give it a try by making it **public**, though: https://github.com/yasirkula/UnityNativeGallery/blob/a25890d7ca32b5fd38c331b86e425b9ec0a55762/Plugins/NativeGallery/NativeGallery.cs#L309-L312

In your Awake/Start function, you should probably call the following function:

```csharp
using( AndroidJavaClass ajc = new AndroidJavaClass( "com.yasirkula.unity.NativeGalleryMediaPickerFragment" ) )
	ajc.SetStatic<bool>( "preferGetContent", true );
```

On iOS, you can try using this shiny new plugin: https://github.com/yasirkula/UnityiOSFilePicker/

**Comment by yasirkula** [comment]
I've just added Android support to my native file picker. You should be able to use it on both platforms now: https://github.com/yasirkula/UnityNativeFilePicker

**Comment by ffarall** [comment]
That's great news! It'll be better for keeping things cross platform and not having to use different tools depending on the OS. Having said that though, the workaround you previously recommended has been working perfectly so far, so great job!

**Comment by cyberjj999** [comment]
@ffarall Hey, sorry for reviving this thread after awhile, but have you found a way to actually play the audio in the scene? I've been searching for hours and can't find a working solution. Most suggested using WWW which is already obsolete. Using UnityWebRequestMultimedia.GetAudioClip(path, AudioType.OGGVORBIS) seems to give me some error as well.

Would love to hear from you, Cheers!

**Comment by ffarall** [comment]
@cyberjj999 I did, yes. I used UnityWebRequestMultimedia. Here's the code:

```
private IEnumerator ChangeAudioClip()
    {
        if(music == null)
        {
            string url = "file://" + _filePath;
            UnityWebRequest www = UnityWebRequestMultimedia.GetAudioClip(url, AudioType.MPEG);
            yield return www.SendWebRequest();

            if (!string.IsNullOrEmpty(www.error))
            {
                NPBinding.UI.ShowToast(www.error, VoxelBusters.NativePlugins.eToastMessageLength.LONG);
            }

            music = DownloadHandlerAudioClip.GetContent(www);
        }

        filePickerController.currentClip = sourceControlled.clip = music;
    }
```

The method ChangeAudioClip is called as a callback with `StartCoroutine(ChangeAudioClip())` when a button is pressed, and `music` is an `AudioClip` variable. `filePath` had the path received from the FilePicker if I'm not mistaken, and then finally in the last line I set the `Clip` I was using as my current clip, to `music`.

**Comment by cyberjj999** [comment]
@ffarall Hey man, I genuinely appreciate your response even though I revived an old thread. I have actually done some digging up and found a solution that is similar to yours.
I appreciate your response nonetheless, thanks and cheers man!
