### ISSUE TITLE
Open Gallery/Photos

### ISSUE THREAD

**Issue by andrewio** [yasirkula/UnityNativeGallery#130]
As I remembered you said that it's not impossible to show preview with last media like on iOS Camera App.

So is it possible to just open Gallery/Photos app or Open Last Media in Gallery/Photos app? (like your OpenSettings())

**Comment by yasirkula** [comment]
Not with NativeGallery :D

**Comment by andrewio** [comment]
> Not with NativeGallery :D

Do you have a knowledge about other plugin (free/paid) which can do this?

**Comment by yasirkula** [comment]
I might have seen a GitHub plugin in the past but I'm not sure if it was this one: https://github.com/Andy-Roger/UnityAndroidNativeFileOpener

**Comment by AQ1991** [comment]
@yasirkula Need help when ever i upload an image from camera and apply it to my raw image in the canvas it gets stretched badly. Am i missing something or am i doing some thing wrong?

**Comment by yasirkula** [comment]
RawImage doesn't preserve aspect ratio. But you can create a Sprite from the Texture and assign it to an Image object that has Preserve Aspect option enabled.

**Comment by AQ1991** [comment]
> RawImage doesn't preserve aspect ratio. But you can create a Sprite from the Texture and assign it to an Image object that has Preserve Aspect option enabled.

Thank you will try this.
