### ISSUE TITLE
Android Setup "if your app won't be saving media to the Gallery but instead just reading media from it"

### ISSUE THREAD

**Issue by FoxySeta** [yasirkula/UnityNativeGallery#132]
> Declare the WRITE_EXTERNAL_STORAGE permission manually in your Plugins/Android/AndroidManifest.xml file with the tools:node="replace" attribute as follows: <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" tools:node="replace"/>

To do that, shouldn't you add the `tools` namespace to the `manifest` element first? My project won't build for Android otherwise.

**Comment by yasirkula** [comment]
You're right, I've updated the FAQ now.
