### ISSUE TITLE
PickImageOrVideo() => How to detect the type of picked media in callback?

### ISSUE THREAD

**Issue by andrewio** [yasirkula/UnityNativeGallery#133]

**Comment by yasirkula** [comment]
There is a native function called `MimeTypeMap.getSingleton().getMimeTypeFromExtension` that returns the mime type of the file extension (extension must be in lower-case). If the mime type starts with "image", then it is an image. If it starts with "video", then it is a video. If it is null, empty or doesn't start with any of these, then you must check the extension manually to determine the file type.

I actually have a C# wrapper function to call the getMimeTypeFromExtension method in [this plugin](https://github.com/yasirkula/UnityNativeFilePicker) (ConvertExtensionToFileType) but there is no such function on NativeGallery. However, you can use AndroidJavaClass/AndroidJavaObject to call this function from C#.

**Comment by andrewio** [comment]
> P.S. I might add a function to make this process easier on NativeGallery.

Would be awesome.

**Comment by yasirkula** [comment]
Will you be using this function on iOS, as well?

**Comment by andrewio** [comment]
> Will you be using this function on iOS, as well?

On Both: iOS & Android.

**Comment by yasirkula** [comment]
Can you import the unitypackage inside this [zip archive](https://github.com/yasirkula/UnityNativeGallery/files/5051157/NativeGallery.zip) to your project and give `NativeGallery.GetMediaTypeOfFile` a go (on both Android and iOS preferably)? It should return Image, Video or Audio; or none of those if the media's type can't be determined.

**Comment by yasirkula** [comment]
There was an issue in the code. I've fixed it and pushed an update.
