### ISSUE TITLE
DateTime picker doesn't appear on IOS

### ISSUE THREAD

**Issue by AdelKanso** [yasirkula/UnityNativeGallery#137]
how to solve this error

![a](https://user-images.githubusercontent.com/53182602/90962330-e4620a80-e4b7-11ea-9ada-21a6e88c3fd4.jpeg)

**Comment by yasirkula** [comment]
NativeGallery lets you pick images and videos. If you are picking a date (DateTime) with another plugin, then probably you've reported this issue to the wrong repository.

**Comment by AdelKanso** [comment]
I'm very sorry for this mistake...
thank you
