### ISSUE TITLE
Memory leak in NGMediaReceiveCallbackAndroid.cs

### ISSUE THREAD

**Issue by emklasson** [yasirkula/UnityNativeGallery#138]
Hi and many thanks for creating this project. It's great!

There's a minor memory leak in NGMediaReceiveCallbackAndroid as you only Destroy the callbackHelper component and not the GameObject it's attached to.

To fix it, just change the two Destroy calls to operate on callbackHelper.gameObject instead.

Cheers!

**Comment by yasirkula** [comment]
Nice catch! Same thing happens on some of my other plugins, as well. Will fix in the next update.
