### ISSUE TITLE
Image Picker not showing up

### ISSUE THREAD

**Issue by thinhsuper** [yasirkula/UnityNativeGallery#139]
**Description of the bug**
`[Presentation] Attempt to present <UIImagePickerController: 0x1189cb600> on <UnityDefaultViewController: 0x1130e4ae0> (from <UnityDefaultViewController: 0x1130e4ae0>) which is already presenting <FloatingPanel.FloatingPanelController: 0x113070310>
`
**Reproduction steps**
I am using Unity to implement Vuforia’s Cloud Recognition then embed the scene in my Swift project’s View Controller

**Platform specs**
Xcode: 12
iOS 14

![image](https://user-images.githubusercontent.com/42728774/93770280-2e204b00-fc46-11ea-9ab3-b3a780b93b08.png)

I think the problem goes here but I don't know how to get the topViewController from here! Any suggesstion @yasirkula  ? Thank you so much.

**Comment by yasirkula** [comment]
It says that Unity view is already presenting a floating panel. Is this your doing or perhaps Vuforia's doing? Can you see any native user interface on top of Unity view while testing your app?

**Comment by thinhsuper** [comment]
My doing, I put some floating buttons overlay the unity view. I don't have an experience of the objectiveC to fix this issue :(
- How can I get my FloatingPanelController from here to present the picker in ?
- Or can I close the FloatingPanel from here ?

**Comment by yasirkula** [comment]
I don't have any native UI experience either, apart from my google experience. [According to this](https://developer.apple.com/forums/thread/45898), you may resolve this issue as follows:

- add the following function to NativeGallery.mm:

```objc
+ (UIViewController *)getParentVC:(UIViewController *)root{
    UIViewController* parentController = root;
    while( parentController.presentedViewController &&
          parentController != parentController.presentedViewController ){
        parentController = parentController.presentedViewController;
    }
    return parentController;
}
```

- change `UIViewController *rootViewController = UnityGetGLViewController();` as follows: `UIViewController *rootViewController = [self getParentVC:UnityGetGLViewController()];`
