### ISSUE TITLE
Large size images turns the screen black for a while

### ISSUE THREAD

**Issue by AdelKanso** [yasirkula/UnityNativeGallery#140]
Hey man, how are you doing?
I was importing a large size image(Image taken by phone camera), I've noticed that the app freeze for a while and the screen goes black and then it will be imported.
It's not the best user experience... if you have any suggestions or a solution for it...
Regards
Adel

**Comment by yasirkula** [comment]
I can't tell why screen goes black as it doesn't happen to me. However, to reduce the delay, you can pass a sufficiently small maxSize parameter to LoadImageAtPath.

**Comment by AdelKanso** [comment]
Thank you
