### ISSUE TITLE
Regarding Video Path

### ISSUE THREAD

**Issue by ragson** [yasirkula/UnityNativeGallery#144]
Hiii
i have an issue with this NativeGallery.GetVideoFromGallery function when i try pick different videos .it returns same path like PickedVideo.Mp4 .i want different paths for different videos how can i acheive that

**Comment by yasirkula** [comment]
NativeGallery copies the selected video to the same location in order not to clutter the cache. You can simply rename the file with File.Move and give it a unique name (e.g. add a timestamp).

**Comment by ragson** [comment]
Ok i got it thank you
