### ISSUE TITLE
Why we need to have write permission only to access the gallery image, if i am not saving any files in my external storage.

### ISSUE THREAD

**Issue by PradeepHGK** [yasirkula/UnityNativeGallery#147]
**Description of the bug**

When i tried disabling the external permission, not able to access it 

**Platform specs**
- Unity version: *e.g. 2019.3.7f1*
- Platform: *e.g. Android, iOS, Windows*
- Device: *if Platform is Android or iOS, please provide the model and the OS version of your device; e.g. Samsung Galaxy S8, Android 10*
- Asset Store

**Comment by yasirkula** [comment]
If you are saving files to Gallery, regardless of whether that file is saved to an SD card or the built-in storage, you must declare WRITE_EXTERNAL_STORAGE permission. External storage doesn't always mean SD card (see the official note [here](https://developer.android.com/reference/android/os/Environment#getExternalStorageDirectory())).

If you are only trying to get media from Gallery, I'll have to see 1) your code snippet and 2) the error messages logged to logcat (you can use Unity's [Android Logcat](https://docs.unity3d.com/Packages/com.unity.mobile.android-logcat@0.1/manual/index.html) package for it).

**Comment by PradeepHGK** [comment]
Thanks for your time to reply sir, please check the below snipper which we are using to get the image, other than this no other methods are used.
 
```C#
NativeGallery.Permission permission = NativeGallery.GetImageFromGallery((path) =>
```

**Comment by yasirkula** [comment]
Is NativeGallery up-to-date?

**Comment by PradeepHGK** [comment]
![image](https://user-images.githubusercontent.com/22808627/98512508-6c240d80-228c-11eb-9d45-97d1a645c11d.png)
I am having the above version in unity, should i need to use upgrade it to v1.6.0 which is in the release?

**Comment by PradeepHGK** [comment]
if I upgrade it to the latest version, can I remove the external permission for android to only to get the images from the gallery?

**Comment by yasirkula** [comment]
Why did you post DotNet Photon Client Library's release notes 😄 ? Honestly, GetImageFromGallery has been asking for only the read permission for quite a while but I'd still recommend you to update the plugin. Perhaps it will somehow resolve the issue. Since you are only using GetImageFromGallery, you can remove WRITE_EXTERNAL_STORAGE permission.

**Comment by PradeepHGK** [comment]
oh sorry, let me check  and update you

**Comment by PradeepHGK** [comment]
Thank you @yasirkula It worked after the update.
