### ISSUE TITLE
EXC_BAD_ACCESS in IOS14

### ISSUE THREAD

**Issue by bit-pete** [yasirkula/UnityNativeGallery#148]
I've got EXC_BAD_ACCESS in IOS14 when using NativeGallery.SaveVideoToGallery. It's working well on iOS below version 14 and in Android. Before this, i use NatCorder for saving video to videoPath. I tried using videoPath instead of $"{videoPath}" and it got same error.

    public void Exit()
    {
        FirebaseAnalytics.Instance.LogEventCloseShare();
        currentState = CaptureScreenState.Idle;
        setDebugText("Idle");
        videoPlayer.Stop();
        AudioManager.Instance.UnmuteSFX();

        ARrenderTexture.Release();

        if(shareMode == ShareMode.ScreenShot)
        {
            if (snapshotPath == null){
                snapshotPath = Path.Combine(Application.persistentDataPath, System.DateTime.Now.ToString("yyyyMMdd_hhmmss") + ".png");
                File.WriteAllBytes(snapshotPath, snapShotTexture2D.EncodeToPNG());
            }
            NativeGallery.SaveImageToGallery($"{snapshotPath}", "ShareJoy", Path.GetFileName(snapshotPath), DeleteFileAfterSaveToGallery);
            Debug.Log("SaveImageToGallery : " + $"{snapshotPath}");
        }
        else if (shareMode == ShareMode.RecordVideo)
        {
            NativeGallery.SaveVideoToGallery($"{videoPath}", "ShareJoy", Path.GetFileName(videoPath), DeleteFileAfterSaveToGallery);
            Debug.Log("SaveVideoToGallery : " + $"{videoPath}");
        }
    }

This is some of my log file : 
[https://www.codepile.net/pile/jwRo1kZ3](url)

I'm using :
- Unity version:  2019.3.4f1
- Platform: iOS
- Device: iPhone SE (iOS 14.0)
- Xcode : 12.0 beta

**Comment by yasirkula** [comment]
Can you try waiting 10 seconds before saving the video (via a coroutine) just to see if it resolves the issue?

**Comment by bit-pete** [comment]
Sorry, I fixed it. It wasn't your assets. The issue is caused by Unity VideoPlayer.
