### ISSUE TITLE
Access to Files folder and iCloud documents (iOS)

### ISSUE THREAD

**Issue by hippogamesunity** [yasirkula/UnityNativeGallery#149]
**Description of the bug**

The problem occurred a few days ago - probably Apple has renewed its Guidelines.
According to App Store Review Guidelines "the application that enables users to view and select files from Photos folder also should offer items from the Files app and the user's iCloud documents". Without access to Files and iCloud Apple reviewers reject application.  
Is there any option to add access to these Files and iCloud folder, not only to Photos? 

Thank you in advance.

**Comment by yasirkula** [comment]
You can use NativeFilePicker for this: https://github.com/yasirkula/UnityNativeFilePicker. I'm not planning to include this feature in NativeGallery. If this guideline is really what it states, then it will be hassle for a lot of developers.

**Comment by hippogamesunity** [comment]
Thanks for your response! BTW It would be cool to specify what are PICK options for File Picker on different platforms, I mean in that asset description.

**Comment by yasirkula** [comment]
By pick options, do you mean iCloud, Files and etc? If so, these providers depend on the installed apps. I use UIDocumentPickerViewController API and then OS decides which apps to show on the presented UI.
