### ISSUE TITLE
Images not loading on iOS14 (14.1 && 14.2)

### ISSUE THREAD

**Issue by andpanda** [yasirkula/UnityNativeGallery#150]
First of all, thank you for this amazing plugin we have been using it for a while.
We have updated it a while ago for the ios permissions changes, but recently a coworker of mine noticed that some images are not loading.
After a bit of testing I have noticed that the files taken from my front or back camera would not load and screenshots or other images from internet that are on my gallery would load fine.

So I have debug it and found that the images that are not loading the path is coming like this: 
"file:///var/mobile/Containers/Data/Application/70141B11-4C87-4C78-AFFE-B3526248336C/Library/Caches/pickedMedia1.heic"

And the working one are coming like that:
"file:///var/mobile/Containers/Data/Application/70141B11-4C87-4C78-AFFE-B3526248336C/Library/Caches/pickedMedia1.png"

Notice that the file extension .heic is what is causing the problem on unity file loader. (I am using the old WWW LoadImageIntoTexture)

I did even knew about this .heic format, this is something new? Do I need to convert this file format to .jpeg or something?
Thanks in advance.

NativeGalleryVersion: 1.6.0
Iphone 8, iOS 14.1 and 14.2

**Comment by yasirkula** [comment]
HEIC is a highly efficient image compression format. Unity's _LoadImageIntoTexture_ function probably works with png and jpeg images only. But you should be able to load this image with **NativeGallery.LoadImageAtPath**. LoadImageAtPath also fixes any orientation issues on loaded images and supports downsampling the image before creating the Texture2D (via _maxSize_ parameter). So, is there a specific reason you aren't using this cool LoadImageAtPath function 😸 ?

**Comment by andpanda** [comment]
Thank you very much! Love you. <3
The reason is that I was not aware of this lovely funciton.

The code is much nicer now, I was having to do so much work around with the returned path.
