### ISSUE TITLE
Multiple pick images not possible at Android.

### ISSUE THREAD

**Issue by soonsoon2** [yasirkula/UnityNativeGallery#151]
**Description of the bug**

A clear and concise description of what the bug is. Before reporting a bug, please do a quick search in Issues to see if it is already reported. If the documentation has a FAQ (Frequently Asked Questions), please also check out the entries there.

**Reproduction steps**

If possible, providing reproduction steps would be very helpful while pinpointing the issue. You can also post screenshots if you think they would be helpful.

**Platform specs**

Please provide the following info if this is a Unity 3D repository.

- Unity version: 2020.1.9f1
- Platform: Android 
- Device: Galaxy note 10+

I tried the pick multiple images at Iphone,it is worked well. 

But same function is not working at Android.
Just image was picked each a once.

I tried permission check with "CanSelectMultipleFilesFromGallery()" 
It show no error.

Please tell me how solve this problem.

Thanks.

**Comment by yasirkula** [comment]
Perhaps the app that you used to pick multiple images doesn't support picking multiple images? Or perhaps you need to press and hold an image file to trigger multi-select but you just tapped on an image?

**Comment by yasirkula** [comment]
Closed due to inactivity.
