### ISSUE TITLE
Error loading textures from HEIC

### ISSUE THREAD

**Issue by roger-o3h** [yasirkula/UnityNativeGallery#152]
**Description of the bug**

Calling `LoadImageAtPath()` on an HEIC image fails, logging an error 
```
libpng error: [00][00][00][00]: missing IHDR
```

**Reproduction steps**

If possible, providing reproduction steps would be very helpful while pinpointing the issue. You can also post screenshots if you think they would be helpful.

**Platform specs**

Please provide the following info if this is a Unity 3D repository.

- Unity version: 2019.4.5f1
- Platform: iOS 14.1
- Device: iPhone 11
- How did you download the plugin: Unity Package Manager from github repo

**Additional info**

I stepped through the Objective-C side of things and it seems to work; it creates a UIImage, scales it, and uses `UIImagePNGRepresentation()` to recompress to PNG.

However, I think it's when the texture tries to read it in, via `result.LoadImage( File.ReadAllBytes( loadPath ), markTextureNonReadable )` that there's a parse error.

I modified the code to be able to get the converted PNG and it opens on MacOS Preview... one thing I'm noticing about it is that it was not resized as requested to under 2048*2048, but it should still be within the max system texture size at 3024x4032.

**Comment by roger-o3h** [comment]
Two updates:
1. Correcting the scaling did not help the issue. I thought the maxSize parameter was total pixels, but realized debugging that it was max pixels per side. Even using 1024 as this parameter produced the same error.
2. It would be extremely helpful to provide access to the file converted by `LoadImageAtPath()` before it's loaded into a texture. That is, it would be great to split that method in two so that I could call the rescaling/conversion method and get a new file back, without trying to load it into a Texture.

Sorry that neither of these help solve the issue thus far...

**Comment by roger-o3h** [comment]
Dunno if this has anything to do with it, but looking at the output PNG, the header is only correct if the file is read big endian... not sure what Unity expects.

**Comment by roger-o3h** [comment]
Replacing `UIImagePNGRepresentation()` with `UIImageJPEGRepresentation()` seems to work as intended. I don't trust iOS's PNG encoder now...

**Comment by yasirkula** [comment]
Thank you for the detailed bug report!

I'm not planning to  create the ConvertImageAtPath function because it hasn't been requested before, so there is only little demand for the function. It is better to create that function manually, as you did.

What does the output Texture2D of LoadImageAtPath look like for the HEIC image?

**Comment by roger-o3h** [comment]
If I remember correctly it was an 8x8 pixel black or transparent texture.

**Comment by yasirkula** [comment]
I don't want to replace UIImagePNGRepresentation with UIImageJPEGRepresentation because we wouldn't be able to load transparent HEIC images that way and there could also be a quality loss for HEIC images.

Can you try commenting out these lines and see if there is any difference: https://github.com/yasirkula/UnityNativeGallery/blob/be970b2515fe1bab1b22883c63f55ba6a26a5559/Plugins/NativeGallery/iOS/NativeGallery.mm#L1391-L1406

If not, does this if condition return false when the libpng error pops up (i.e. do the code inside it get executed): https://github.com/yasirkula/UnityNativeGallery/blob/be970b2515fe1bab1b22883c63f55ba6a26a5559/Plugins/NativeGallery/NativeGallery.cs#L691

**Comment by roger-o3h** [comment]
> I don't want to replace UIImagePNGRepresentation with UIImageJPEGRepresentation because we wouldn't be able to load transparent HEIC images that way and there could also be a quality loss for HEIC images.

Oh, certainly not. I don't suggest it as a fix at all. Just trying to hone in on what the problem is.

I just ran a sample project with only NativeGallery in it, and it loaded and displayed the same HEIC images that I am having issues with, on the same version of Unity, iOS, XCode, and the same device. So, I think, even though we had not made any changes to the NativeGallery plugin, something was interfering with it. We do have a number of plugins so my guess is that there's some duplicate symbols and perhaps the wrong symbol is being called... that's my operating theory.

As it appears to be related to our project, I'll close this issue. Thank you for your suggestions and your hard work on these plugins!

**Comment by thesanketkale** [comment]
Hi @roger-o3h and @yasirkula, I am facing a similar issue while using the latest v1.7.4 of the NativeGallery plugin from the Unity Asset Store. The loaded HEIC image is displayed as a grey image when loaded on a RawImage component from an iPhone app. JPG and PNG images load normally on the raw component, but not the HEIC images taken from the iPhone camera.

How can I solve this? Am I missing something?

**Comment by ParkEunSeong** [comment]
> > 그런 식으로 매끄러운 HEIC 이미지를 로드할 수 있으므로 HEIC 이미지의 품질이 보호할 수 있으므로 UIImagePNGRepresentation을 UIImageJPEGRepresentation으로 즐기세요.
> 
> 아, 물론 그렇지 않습니다. 나는 통합으로 그것을 제안하지 않습니다. 문제가 무엇인지 알아보려고 노력하겠습니다.
> 
> NativeGallery만 포함된 샘플 프로젝트를 실행했는데, 괜찮은 버전의 Unity, iOS, XCode 및 동일한 장치에서 문제가 있는 것과 동일한 HEIC 이미지가 로드되어 표시되었습니다. 그래서 제 생각에는 NativeGallery를 변경하지 않으려고 해도 뭔가 방해가 되는 것 같습니다. 우리는 많은 항목을 가지고 있는 내용이 있거나 아마도 들여쓰기된 것입니다. 이것이 제 운영 체제입니다.
> 
> 저희 프로젝트와 관련이 있는 것 때문에 이 문제는 별로도 지역에 없습니다. 이 플러그인에 대한 여러분의 제안과 노고에 감사드립니다!

hello. The same error occurs in our project. If you have solved it, can you share the solution?
