### ISSUE TITLE
Load images automatically from the album

### ISSUE THREAD

**Issue by shacharoz** [yasirkula/UnityNativeGallery#153]
**Description of the bug**

the goal: create a dedicated in-app gallery of images. every time user gets into that page, they can see all images previously taken with the app.

is it possible to save the link to all files in my app album?  (I remember that it is not possible)
perhaps it is possible to save the link to the album then? 

I know where the app saves the files since we give it an album name. 

can I go to that folder and take all the images from there, WITHOUT the user to need to do that themselves?

**Platform specs**

- Unity version: 2019.4.2f1
- Platform: Android, iOS, 
- Device: xiaomi redmi 8
- How did you download the plugin: Asset Store

**Comment by yasirkula** [comment]
There is no guaranteed solution for this because NativeGallery.SaveImageToGallery's MediaSaveCallback may not return raw filepath if it can't be determined. If we 🤞 and assume that it will always return raw filepath, then you can simply store each saved image file's path at e.g. PlayerPrefs and access them directly using File API. For this to work on Android 10, you need to add a requestLegacyExternalStorage=true attribute to your AndroidManifest.

**Comment by shacharoz** [comment]
thank you @yasirkula , as always, a proactive answer!

i would have tried the direct filepath response, but If ios will not support this, i will just prefer to keep copy of all images...

thanks yakir

**Comment by shacharoz** [comment]
to whom it might be interesting, here is what I did.

`private void SaveImageToDisk(string file_path_name, Texture2D texture2d)
    {
            byte[] fileData = texture2d.EncodeToPNG());

        using (var fs = new FileStream(file_path_name, FileMode.Create, FileAccess.Write))
        {
            fs.Write(fileData, 0, fileData.Length);
        }
    }`

then I loaded the images from there.

**Comment by shacharoz** [comment]
to whom it might be interesting, here is what I did.


`
private void SaveImageToDisk(string file_path_name, Texture2D texture2d)
{
byte[] fileData = texture2d.EncodeToPNG());

    using (var fs = new FileStream(file_path_name, FileMode.Create, FileAccess.Write))
    {
        fs.Write(fileData, 0, fileData.Length);
    }
}`
