### ISSUE TITLE
Albums are not created in google photos.

### ISSUE THREAD

**Issue by DarkWizzy007** [yasirkula/UnityNativeGallery#154]
Hi Yasir,

Thank you for contributing a great plugin for community.
This might not be an exact issue with plugin but an extended functionality. I would like to see the album created by the plugin inside Google Photos not just Gallery. This plugin stores album inside **InternalStorage>DCIM>AlbumFolder** but I am trying to store the album inside **Internal storage>AlbumFolder** that should automatically appear inside Google Photos. 

I am using following code to get the right path.

```
string path = Application.persistentDataPath.Substring(0, Application.persistentDataPath.IndexOf("Android",StringComparison.Ordinal));

string videosPath = Path.Combine(path + "MyAlbum");
```
I am using following code to create the directory and store screenshots
```

 public static bool SaveImageLocally(Texture2D image, string path, string filename)
        {
            try
            {
                byte[] imageData = image.EncodeToJPG(70);
                Debug.LogError("Does directory exists at " + path + " ?" + Directory.Exists(path));
                if (!Directory.Exists(path))
                    Directory.CreateDirectory(path);
                string filePath = Path.Combine(path, filename);
                Debug.LogError("Save screen shot at " + filePath);
                File.WriteAllBytes(filePath, imageData);
                return true;
            }
            catch (Exception exception)
            {
                Debug.LogError("error occured " + exception.Message);
                return false;
            }
        }
```
Following code to request permission at runtime:

```
NativeGallery.Permission permission = NativeGallery.CheckPermission();
if (permission == NativeGallery.Permission.Granted) 
{
     Debug.Log("May proceed");
}
else 
{
     Debug.Log("Not allowed");
}
```
Since I am testing on Android 10, I've also added following code in Manifest because **"android:requestLegacyExternalStorage"** is by default false in Android 10+

`android:requestLegacyExternalStorage="true"
`
While creating directory inside internal storage root folder, I am getting access denied i, ssue. Although I've alrady provided Read and Write External storage permission. Asking permission at runtime as well. Do I need to write native code to access internal storage, can you please suggest any problem that you see?

**Comment by yasirkula** [comment]
I don't recommend you to pursue this path. I remember reading from a probably official documentation that Google discourages creating folders in the root directory. More importantly, on Android 11 and later, you can't create any file or folder in the root directory without using Storage Access Framework. Storage Access Framework will definitely require you to write native code and the final product might not even work as you've expected: user might need to explicitly allow you to create a folder on the root directory.

**Comment by DarkWizzy007** [comment]
@yasirkula - Yes I read same in the forums but interestingly, there are some unity application are already doing this that too in Android 10 and 11 that's why client is requesting for same. I'll try to figure out.
Do you have anything else in your mind to include the album in Google Photos?

**Comment by yasirkula** [comment]
You can try changing lines 98 and 156 in [native code](https://github.com/yasirkula/UnityNativeGallery/blob/master/.github/AAR%20Source%20(Android)/java/com/yasirkula/unity/NativeGallery.java) and rebuild the library in Android Studio.

**Comment by DarkWizzy007** [comment]
Hi Yasir,

Your project wasn't setup for gradle and setting it up could have costed me a lot time as I am a total novice with android studio. I tried other solution and fortunately it worked out for me. So far I've tested on Android 10 and below:

This code is doing that exact thing you're doing at native end.  I am using it to get the path for **Pictures Folder**

```
private string GetAndroidExternalStoragePath()
    {
        var jc = new AndroidJavaClass("android.os.Environment");
        var path = jc.CallStatic<AndroidJavaObject>("getExternalStoragePublicDirectory", 
            jc.GetStatic<string>("DIRECTORY_Pictures"))
            .Call<string>("getAbsolutePath");
        return path;
    }
    
```
   
After you get the exact path and the permission is granted, you can use file handling to store the data inside InternalStorage>Pictures

**Comment by yasirkula** [comment]
So, Google Photos doesn't look into DCIM subfolders but does look into Pictures subfolders? Honestly, I'd consider it a bug in the Google Photos app. Happy to hear that you've resolved the issue, though. I'd recommend you to test the code on an Android 11 emulator because file access using File API has changed in both Android 10 and Android 11.

**Comment by yasirkula** [comment]
With the latest commit (https://github.com/yasirkula/UnityNativeGallery/commit/c825a03c51555d0d33556554bb822f525fd0eef2), it is easier to switch from DCIM to Pictures:

```csharp
// Before
// NativeGallery.SaveImageToGallery( image, "Album", "Image.png" );

// After
using( AndroidJavaClass ajc = new AndroidJavaClass( "com.yasirkula.unity.NativeGallery" ) )
	ajc.SetStatic<bool>( "mediaSaveOmitDCIM", true );

NativeGallery.SaveImageToGallery( image, "Pictures/Album", "Image.png" );
```

**Comment by DarkWizzy007** [comment]
Hi Yasir,

Hope you're doing good.
I have a quick question regarding your Native Gallery plugin. I saw that it
supports sharing the media with some specific target for Android. My
requirement is such that I need to add some specific targets, not just one.
Would it be possible after doing some tweaks in your plugin?

Regards
Arun

**Comment by yasirkula** [comment]
**NativeShare**'s **AddTarget** function can be called multiple times, yes.

**Comment by DarkWizzy007** [comment]
Hi Yasir,

Thank you for the quick response. The version of the plugin that I am
working with has only 1 method to support a predefined target and the name
is "*SetTarget*". The "*SetTarget*" supports only 1 target at a time .
Have you extended the functionality in the newer version and added a new
method "*AddTarget"* ?

REGARDS
ARUN

**Comment by DarkWizzy007** [comment]
Thank you for answering the question.
I am sorry, I got confused between Native Gallery and Native Share and I
replied on an existing email chain. I'll keep that in mind.
