### ISSUE TITLE
Save Uploaded Video to Unity, then Render to Screen

### ISSUE THREAD

**Issue by cyberjj999** [yasirkula/UnityNativeGallery#156]
Hello. Firstly, I would like to take @yasirkula for this WONDERFUL plugin! It really took a lot of weight off my back.

I noticed that the documentation for this tool is really neat and clean, so props to @yasirkula! However, I would like to save the uploaded video to some database (which i believe requires more than the file path?) and render the video preview to the users, before they confirm that they want to send the video to the database.

I already found ways to play the video in unity within a small box (via rendertexture and rawimage) - source: https://www.youtube.com/watch?v=p7iXEZGx2Mc&t. This works perfectly if I have a mp4 file, and I manually set the aspect ratio etc.

The challenge is that all I have after the user selects the video is the path to the video. My question is
a. How can I determine the correct aspect ratio of the video from the path alone (so I can adjust the render texture to fit properly)
b. How can I get a "Video Object" from the path, which can allow me to ultimately save the Video into my database in the future.

For simplicity sake's, here a sample screenshot that can show what I want to do very quickly
![image](https://user-images.githubusercontent.com/51283594/102974778-0dfc7280-453a-11eb-9816-03b6ec775c73.png)
Steps for using
a. User clicks upload video (gallery pops up)
b. User selects the video of choice
c. The video plays inside the red panel in loop (render texture will resize the video accordingly to fit within this panel)
d. If user is satisfied, they can click send, and the file should be sent to the database.

I hope this question is clear and if I had any misunderstanding of the plugin or unity in general, please correct me as I'm a beginner haha.

Cheers and thanks in advanced!

**Comment by yasirkula** [comment]
a. You can use [NativeGallery.GetVideoProperties](https://github.com/yasirkula/UnityNativeGallery#d-utility-functions) to determine the aspect ratio.
b. I'm not sure what this "video object" is supposed to be. Can't you just upload the video file itself to the server?

**Comment by cyberjj999** [comment]
@yasirkula 
Wow, thank you very much for the very quick response.
Answering to your points
a. Thanks for the guidance
b. Aren't we only getting a string to the path of the video, but not the actual video file? I realized I had a misunderstanding regarding displaying of video on RenderTexture, it seems like it takes in a URL as well, which can be the full path to the video.

However, regarding storage to database, shouldn't I store the actual video file instead of the path?

**Comment by yasirkula** [comment]
Ah, yes you should indeed upload the video file instead of the path. I was also talking about this. I have no experience in this topic so you should google "unity upload file to server" but it is definitely possible with WWW or UnityWebRequest.

**Comment by cyberjj999** [comment]
> Ah, yes you should indeed upload the video file instead of the path. I was also talking about this. I have no experience in this topic so you should google "unity upload file to server" but it is definitely possible with WWW or UnityWebRequest.

I see. I'm positive that it is definitely possible to upload the file to database, but just to clarify incase I misunderstood you, with this plugin - we are able to get the actual file and not just the video path am I correct?

**Comment by yasirkula** [comment]
When you have a filepath that you have read access to, you basically have access to the actual file. If you didn't have access to the video file, you couldn't play the video in Unity. You can use File.ReadAllBytes to read file's bytes if necessary.

**Comment by cyberjj999** [comment]
Ahh I see. Thanks so much for clarifying!
