### ISSUE TITLE
Unity App Freezes after Picking Certain Video

### ISSUE THREAD

**Issue by cyberjj999** [yasirkula/UnityNativeGallery#157]
Hi, I'm trying to create a feature that allow users to upload video, and after they select their video, the video thumbnail will appear in the scene and the user can click on it to preview the video in full screen.
Scene Preview
![image](https://user-images.githubusercontent.com/51283594/103136123-9c1e5780-46f8-11eb-970d-777c79cacca7.png)

I'm currently facing one error
If I try to a certain type of video (that contain the Samsung Cloud Icon) , my unity app will freeze and lag - the operation will only complete after 3-5s.

Here is my code for reference
```
public RawImage thumbnailImage;

public void PickVideo()
	{
		if (NativeGallery.IsMediaPickerBusy())
        {
			Debug.Log("Media Picker Busy");
			return;
		}
			

		NativeGallery.Permission permission = NativeGallery.GetVideoFromGallery((path) =>
		{
			Debug.Log("Video path: " + path);
			if (path != null)
			{
				// Play the selected video				
				Texture thumbnailTexture = NativeGallery.GetVideoThumbnail(path);                       // Get the video thumbnail (ONLY WORK ON PHONE, WILL RETURN NULL IN EDITOR)				
				thumbnailImage.texture = thumbnailTexture;                                              // Set the texture of the rawImage to the video thumbnail				

				thumbnailImageObject.GetComponent<AspectRatioFitter>().aspectRatio = thumbnailTexture.width / thumbnailTexture.height;

                Button thumbnailImageBtn = thumbnailImageObject.GetComponent<Button>();					// Get the button component of thumbnail image
                thumbnailImageBtn.onClick.AddListener(() =>
                {					
					Handheld.PlayFullScreenMovie("file://" + path, Color.black, FullScreenMovieControlMode.CancelOnInput);
				});
            }
		}, "Select a video");

		Debug.Log("Permission result: " + permission);```

Code is simplified slightly to avoid confusion. I don't think the aspectFitter caused any issue, but picking videos (those with Samsung Cloud Logo - which I believe represents some sort of cloud backed up video), did cause lag and hang (which will work as intended after waiting for 5s, but theres still some lag.
Tested with every other video and it works fine, its not a issue with video duration too.

**Comment by yasirkula** [comment]
Can it be that the videos with Samsung Cloud icon are downloaded from the cloud during the lag?

**Comment by cyberjj999** [comment]
Oh yea, you're right. I think so. Are there any ways we can handle this such that it doesn't cause a black screen that looks like a crash in Unity?

**Comment by yasirkula** [comment]
When does this black screen appear? I thought the game froze while Unity scene was visible on screen.

**Comment by cyberjj999** [comment]
When I select the video with the Samsung Cloud Icon, the screen hangs for awhile and turn black, only until the operation is completed (when the video is downloaded), then it returns back to the scene view.

**Comment by yasirkula** [comment]
I don't think you can do anything about this black screen. As for me, I may put some sort of loading bar that appears after selecting a video. I want to confirm that the issue is caused by the download delay, though. If you omit GetVideoThumbnail line, does this affect the black screen in any way?

**Comment by cyberjj999** [comment]
Hi yasirkula. My apologies for the very late response as I missed the message due to lack of notification. 
I have tried removing the "GetVideoThumbnail" line and the black screen still remains. I am positive that it is happening because of the download delay.

Hope it helps =)

**Comment by yasirkula** [comment]
I've spent a few hours on this topic and tried a number of things but couldn't get it to work. The loading bar doesn't show up until the download is completed. Making it work would require major code refactoring which I'm not keen on doing 😞 Sorry.
