### ISSUE TITLE
editor folder is missing from package

### ISSUE THREAD

**Issue by dappledore** [yasirkula/UnityNativeGallery#16]

**Comment by yasirkula** [comment]
If you are using the unitypackage from this repository, it should be located at Plugins/NativeGallery/Editor. The Asset Store package is under review so it doesn't have the folder yet. The update should be live in a couple of days.

**Comment by dappledore** [comment]
ok thanks

**Comment by yasirkula** [comment]
Now it is live on Asset Store.
