### ISSUE TITLE
Red question mark for Gallery image - iOS 14 problem?

### ISSUE THREAD

**Issue by nategametaco** [yasirkula/UnityNativeGallery#160]
**Description of the bug**

The plugin worked fine a few weeks ago. I haven't touched the code that was interfacing with the plugin, but I believe that iOS 14 broke the gallery seeking function somehow. I have updated to your latest on the Unity Asset Store, but I am still seeing a red question mark when I try to apply the image. I am also coupling this plugin to your Image Cropper. 

To see the bug in action download: https://apps.apple.com/us/app/bubble-shooter-cash-tournament/id1543487032

Tap on the Settings gear on the Home Screen (the first screen that opens) and then tap on Profile. Then tap on the camera icon next to your temp profile photo. It will open your gallery, after you select a photo it will take the photo and bring it into the Image Cropper and you'll see that it's a red question mark. As stated before, this all worked before. 

Here is my implementation code: https://pastebin.com/EYba066s (code formatting didn't work on here)

I am seeing that the texture has a width and height of 8 for some reason...? Strange. Like I said, I haven't touched this code and it all worked a couple weeks ago. 

I am also calling your build post process method in my post processor: 
`NativeGalleryNamespace.NGPostProcessBuild.OnPostprocessBuild(BuildTarget.iOS, buildPath);`

Let me know what you think or have any tips.

**Comment by yasirkula** [comment]
You shouldn't call `bool loadedImage = texture.LoadImage(System.IO.File.ReadAllBytes(filePath), false);`. This basically tells LoadImageAtPath to get out of here, removing all its contents.

**Comment by nategametaco** [comment]
Thanks that was it. Funny, I have been using this code for a while now and it suddenly broke. I got this from another example and I always thought it was curious there was two loads.
