### ISSUE TITLE
App restarting after picking up Image

### ISSUE THREAD

**Issue by ajathunity3d** [yasirkula/UnityNativeGallery#161]
Hi, 
Great asset, 
Very easy to use,
Just one problem here is when I am picking any Image or Video from gallery, It restarts my app.
I know there must be some small thing here which I am missing, Please let me know the solution, It'll be very helpful for me.

**Comment by yasirkula** [comment]
Please see https://github.com/yasirkula/UnityNativeGallery/issues/100 and https://github.com/yasirkula/UnityNativeCamera/issues/27

**Comment by ajathunity3d** [comment]
But in long go, we can't ask users to kill there background app.

**Comment by yasirkula** [comment]
Luckily, this should mostly affect old devices with low RAM capacity. The restart is triggered by Android OS, I wish I had a say in this but I unfortunately don't.
