### ISSUE TITLE
Video Thumbnail for Online Video Path

### ISSUE THREAD

**Issue by cyberjj999** [yasirkula/UnityNativeGallery#162]
Hey man, just have 2 question
1) For the GetVideoThumbnail function, is it the expected behaviour for the thumbnail image to be null when I am running it on Unity Editor?
2) Is it possible to get a thumbnail from an online video path? i.e. dropbox/xxx/file.mp4, -> I have tested and seems like the handheld.PlayFullScreenMovie works with my online video path, but I can't seem to get the thumbnail, even when I'm on my android device. It works when I upload my own video file though.

**Comment by yasirkula** [comment]
1. Yes it is.
2. If setting captureTimeInSeconds parameter to a positive value doesn't work on Android, I'm afraid it isn't possible. On iOS, it will definitely not work. I don't know if it is possible but if it is, native source code must be modified because it works with file paths.

**Comment by yasirkula** [comment]
I don't think there is a built-in function for generating thumbnails so you'd have to use a 3rd party plugin for it. Try googling with keywords c# generate video thumbnail.

**Comment by cyberjj999** [comment]
Alright man. Thanks for the insights. Cheers!
