### ISSUE TITLE
java.lang.ClassNotFoundException: com.yasirkula.unity.NativeGalleryPermissionReceiver

### ISSUE THREAD

**Issue by siddharth3322** [yasirkula/UnityNativeGallery#163]
When I tried to save image to gallery using this code:

` // Save the screenshot to Gallery/Photos
        NativeGallery.Permission permission = NativeGallery.SaveImageToGallery(GameController.Instance.RosesSprite[roseId - 1].texture, "NameThatRose", "Rose" + roseId + ".png",
            (success, path) => Debug.Log("Media save result: " + success + " " + path));`

and I am getting this error on Android Debug Log:

`01-20 18:09:13.307 10378-10394/? E/Unity: AndroidJavaException: java.lang.ClassNotFoundException: com.yasirkula.unity.NativeGalleryPermissionReceiver
    java.lang.ClassNotFoundException: com.yasirkula.unity.NativeGalleryPermissionReceiver
        at java.lang.Class.classForName(Native Method)
        at java.lang.Class.forName(Class.java:324)
        at com.unity3d.player.UnityPlayer.nativeRender(Native Method)
        at com.unity3d.player.UnityPlayer.access$300(Unknown Source)
        at com.unity3d.player.UnityPlayer$e$1.handleMessage(Unknown Source)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:157)
        at com.unity3d.player.UnityPlayer$e.run(Unknown Source)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.yasirkula.unity.NativeGalleryPermissionReceiver" on path: DexPathList[[zip file "/data/app/com.jetfreshflowers.namethatrose-1/base.apk"],nativeLibraryDirectories=[/data/app/com.jetfreshflowers.namethatrose-1/lib/arm64, /data/app/com.jetfreshflowers.namethatrose-1/base.apk!/lib/arm64-v8a, /vendor/lib64, /system/lib64]
01-20 18:09:13.324 736-829/? D/ThermalEngine: sensor_wait: case_therm Wait done.`

How can I solve this?
Please suggest me.

**Comment by yasirkula** [comment]
Please check out the FAQ.

**Comment by siddharth3322** [comment]
Thank you sir for your quick reply :)

I think this FAQ is related to me:
**Can't access the Gallery, it says "java.lang.ClassNotFoundException: com.yasirkula.unity.NativeGallery" in Logcat**

Then how to check my project is using ProGuard or not?
Where to put ProGuard filter?
Sorry If I am asking a noob question but I can't able to find ProGuard within my Player Settings panel.

**Comment by yasirkula** [comment]
It's the Minification option in Player Settings. What is its value? To add a filter to ProGuard, you need to enable Custom ProGuard File from Player Settings.

**Comment by siddharth3322** [comment]
Where can I find the Minification option?
For your reference, I have attached my player settings screenshot:
![players settings](https://user-images.githubusercontent.com/3082151/105316340-bb6caf80-5be6-11eb-8c33-8cc93b64171f.png)

So please guide me a little bit more into this :)

**Comment by yasirkula** [comment]
What are the settings even further down there?

**Comment by siddharth3322** [comment]
here you have the publishing settings screenshot that exists at last:
![player publishing settings](https://user-images.githubusercontent.com/3082151/105317586-5f0a8f80-5be8-11eb-925f-d989ec58ae94.png)

**Comment by yasirkula** [comment]
I guess Minify option is now either R8 (Gradle?) and non-R8 (ProGuard?). Click the "Custom Proguard File" and try adding the filter there.

**Comment by siddharth3322** [comment]
As I click on the **Custom ProGuard** file, it generated a new file named "proguard-user.txt"
This file is completely empty.
So I have added this line of text:
`-keep class com.yasirkula.unity.* { *; }`
Started building a project for my Android device and hurray it worked perfectly.
I can able to save to image to my phone's local storage plus it becomes visible in the Photos section too :)

Thank you sir for your guidance 💯

**Comment by yasirkula** [comment]
You're welcome :)

**Comment by CHEN258-hub** [comment]
你好，我使用的版本是unity2018的版本，我并未在里面找到Custom Proguard File这个选项

**Comment by yasirkula** [comment]
@CHEN258-hub If there's a Minification option, you can try disabling it. The plugin already has its own embedded proguard file so manual intervention is actually no longer needed. If you're using a custom code stripper, it may also be causing this. Apart from these, I unfortunately don't know any other reasons for this to happen.

**Comment by yasirkula** [comment]
Yeah. I don't know any reasons an error like this could still be reported. I'm sure that you can't get this error on a new project. It must be something specifically related to your project but I don't know what unfortunately.

**Comment by CHEN258-hub** [comment]
好的，我再研究研究，感谢了

**Comment by yxingqin** [comment]
我这里也会报错，java.lang.ClassNotFoundException：。 尝试解包apk ，发现没有 com\yasirkula\unity\ 以及他下面的 class 文件。是因为我的项目自定义了 AndroidManifest文件吗？我讲如何 解决这个问题呢？
![image](https://github.com/yasirkula/UnityNativeGallery/assets/71218502/1ac97024-700a-4f7b-ad6b-9324635f4b88)

**Comment by yxingqin** [comment]
哦 对了，项目是使用Gradle进行打包的，需要额外的设置吗？

**Comment by yasirkula** [comment]
@yxingqin I am totally clueless why many users receive this error. It shouldn't be related to AndroidManifest. I'm also making Gradle builds without any issues. Can you create a new Unity project, import NativeGallery and see if the issue is reproducible there?

**Comment by yxingqin** [comment]
这可能和我是用的打包方式有关，感谢你的指导。我这边再去尝试尝试。 Thanks

**Comment by yasirkula** [comment]
@yxingqin If you find the culprit of the problem, please do let me know. I haven't heard back from anyone who had reported this issue in the past and I'm eager to know what causes it.

**Comment by yxingqin** [comment]
不好意思，由于繁忙现在才回复。
在我的项目中, 由于gradle的配置是自定义的，没有使用unity导出配置。
这导致NativeGallery.aar没有进入apk，所以才会报错。

之后我尝试在 Unity的build.gradle项目中配置了
```
 allprojects {
   repositories {
      // xxx
       flatDir {
           dirs 'libs'
       }
   }
}
```

```
dependencies {
// xxxx
    implementation(name: 'NativeGallery', ext:'aar')
}
```

同时将 aar 文件放置到 libs目录下, 这样build仍然会报错，`Error building Android library: Direct local .aar file dependencies are not supported`

最后在这个帖子下找到解决方案：
https://stackoverflow.com/questions/60878599/error-building-android-library-direct-local-aar-file-dependencies-are-not-supp

**Comment by yasirkula** [comment]
Thank you. I shall redirect users having the same issue to your post.
