### ISSUE TITLE
NativeGallery.GetImageFromGallery, the camera will also start

### ISSUE THREAD

**Issue by imoegirl** [yasirkula/UnityNativeGallery#164]
![Screenshot_20210125_165751](https://user-images.githubusercontent.com/57443542/105683676-dadd4280-5f2e-11eb-98d0-89c1ae8519a7.jpg)

**Comment by yasirkula** [comment]
If you are using NativeCamera, you must be calling both NativeGallery and NativeCamera functions at the same time by mistake because NativeGallery has no camera code in it.
