### ISSUE TITLE
"Select Photos.." App-Crash

### ISSUE THREAD

**Issue by Northwind877** [yasirkula/UnityNativeGallery#165]
Hi, 

I would like to save screenshots to my gallery, but in the permission screen I get the following question:

![photo_2021-01-25_20-23-58](https://user-images.githubusercontent.com/2829100/105755332-72508e80-5f4b-11eb-93a7-c66fb4648b00.jpg)

Why does it show "Select Photos..." here? I would like to only give permission to write. When I hit the button for "Select Photos.." my app crashes. The next time I start, I can save photos normally and no more permissions dialog appears.

My source code:

```
var checkPermission = NativeGallery.CheckPermission(NativeGallery.PermissionType.Write);

      if (checkPermission == NativeGallery.Permission.Denied)
      {
        NativeInput.ShowAlertBox(
          "You've denied the permission to save Real Coasters screenshots to your camera roll. Do you want to change the permission in the settings?",
          true, AlertBoxActionDelegateStaticForPermissionChangeInSettings);
      }

      if (checkPermission == NativeGallery.Permission.Granted||
          checkPermission == NativeGallery.Permission.ShouldAsk)
      {
        NativeGallery.SaveImageToGallery(screenshot, "#RealCoaster", $"Screenshot_{DateTime.Now:yyyy-dd-M--HH-mm-ss}.jpg");
        yield return null;
      }
```

It would be nice if it didn't show the "Select Photos" at all, or what am I doing wrong? do you have any idea?

Thank you!

**Comment by yasirkula** [comment]
If you compile the app with iOS 14 SDK, the "Select Photos..." option will disappear. The new permission system was introduced with iOS 14 SDK so unfortunately it requires iOS 14 SDK.

**Comment by Northwind877** [comment]
Thank you for your answer. 

I Set the target minimum iOS Version to 14.0:
![image](https://user-images.githubusercontent.com/2829100/105820271-a5ca0200-5fb9-11eb-8f59-76daf77f66ed.png)

Unfortunately, the "Select Photos..." dialog still comes. I use Unity Cloud Build for compiling and the xCode version is set to Xcode 11.3.1.

**Comment by yasirkula** [comment]
iOS 14 SDK comes with Xcode 12 so you'll need at least Xcode 12, unfortunately.

**Comment by Northwind877** [comment]
Thanks, that's it. It works now.  :) 

Of course, it would also be great if it also worked for older iOS versions.

**Comment by yasirkula** [comment]
I wish I could get rid of "_Select Photos_" on older iOS SDKs but it isn't possible, the new permission system (`PHPhotoLibrary requestAuthorizationForAccessLevel`) is introduced with iOS 14 SDK.

The crash, on the other hand, is related to how NativeGallery executes permission functions synchronously. Getting rid of the issue would require me to refactor the whole permission system so that it works asynchronously but since iOS 14 SDK resolves this issue already, this major refactoring is luckily not needed.

**Comment by yasirkula** [comment]
P.S. I'm not sure if "_Target minimum iOS Version_" is the option that determines the target iOS SDK; setting it to 14.0 may prevent the game from running on iOS 13 or below which would be a major concern.

**Comment by Northwind877** [comment]
Thanks for the great help and for the awesome work for UnityNativeGallery! 

Yes, I reset the value back to iOS 12 and I will check the version with the unity API (Device.systemVersion) and disable the camera feature in older versions.  I think that's a nice solution. I will also display a dialog that the player has to upgrade to iOS 14 to use it.

We will publish our game soon, I'll be happy to send you a link then :)

**Comment by yasirkula** [comment]
You don't have to disable the plugin on earlier iOS versions because _Select Photos..._ option only appears on iOS 14+ devices. So, on iOS 13 or earlier devices, the plugin will work fine regardless of target iOS SDK.

**Comment by Northwind877** [comment]
Ah, I got that wrong. Thanks for the hint.
I should have several test devices with different iOS versions.
