### ISSUE TITLE
Recorded and Uploaded Video does not work with Handheld.PlayFullScreenMovie

### ISSUE THREAD

**Issue by cyberjj999** [yasirkula/UnityNativeGallery#167]
Hi yasirkula,

I am using UnityNativeGallery to upload video and UnityNativeCamera to record video.
Both of which are working well and fine. However, I am currently facing a problem - it seems like the video recorded and uploaded cannot be played with `Handheld.PlayFullScreenMovie`.

To elaborate further, I am not running `Handheld.PlayFullScreenMovie` immediately after the record/upload. I am actually saving the bytes of the file, uploading it to a database, before running the `Handheld.PlayFullScreenMovie` code on network url of the online video. 
There are a few things that I can conclude
1) The video format is not corrupted - I am able to download the video file from the online url as a .mp4 and it can run perfectly on my desktop
2) There are no mistakes with my code since I created an entirely new function and hardcoded the url to see if Handheld.PlayFullScreenMovie can run

My conclusion after hours of debugging is that the file's compression method or something is not compatible with Handheld.PlayFullScreenMovie (although no errors were thrown)
I tested it with 3 online video 
"https://cdn.videvo.net/videvo_files/video/free/2012-10/small_watermarked/hd1951_preview.webm";
"https://file-examples-com.github.io/uploads/2017/04/file_example_MP4_480_1_5MG.mp4";
and
"http://techslides.com/demos/sample-videos/small.mp4";

Surprisingly, the first two online videos worked and the third video did not. Which could suggest that maybe Handheld.PlayFullScreenMovie is not compatible certain video. I honestly am very confused and unsure how I can make the video compaitible

I would sincerely appreciate any help.

**Comment by yasirkula** [comment]
I didn't even know Handheld.PlayFullScreenMovie would work with remote urls. I'd recommend you to try downloading the problematic video to Application.temporaryCachePath and then see if it will work with Handheld.PlayFullScreenMovie (add "_file://_" prefix to the path). If it does, then this function can't handle some mp4 files on remote urls. You can either try using VideoPlayer or check error messages in logcat and google the error.

**Comment by cyberjj999** [comment]
Hey yasirkula, pardon for the delayed response.
It seems like you're right, the error is due to remote URLs. It is really quite frustrating that Unity did not include any error message when the URL didn't play, took me so long to debug the problem.

Nonetheless, I have found a solution to my problem, similar to what you say, I would need to download the video first before playing it.
Here's the link that helped me (for anyone who sees this in the future): https://stackoverflow.com/questions/44042182/download-and-play-video-with-handheld-playfullscreenmovie-on-android-in-unity
Some method in the code is obsolete but the replacement can be found online easily. Do hit me up if you require any assistance.

Cheers. And thank you yasirkula for the quick response :)
