### ISSUE TITLE
Cropping Image Support?

### ISSUE THREAD

**Issue by fayyadsufyan** [yasirkula/UnityNativeGallery#17]
Dear @yasirkula ,

Is it possible "easy" to add cropping feature after selecting the image?
I want a squared resolution image that can be used as a profile picture.

Any guidelines for this?
Is there a way to integrate it with the "Android Image Cropper" plugin by ArthurHub?

Thanks in advance

**Comment by yasirkula** [comment]
Android Image Cropper looks like a large library that makes extensive use of native functions, gradle build system and AppCompatActivity. At first glance, using that library in Unity seems to involve a lot of steps.

If you really want to go that way, you will have to create a fragment that will start the CropImageActivity and pass the result to Unity. Here's how you would theoretically start that activity using the file path returned from NativeGallery in your fragment:

```java
private static final int IMAGE_CROP_REQUEST_CODE = 55476; // a number of your choice
private final String imagePath;

public ImageCropFragment()
{
	imagePath = null;
}

public ImageCropFragment( final String imagePath )
{
	this.imagePath = imagePath;
}

@Override
public void onCreate( Bundle savedInstanceState )
{
	super.onCreate( savedInstanceState );
	
	if( imagePath == null )
	{
		getFragmentManager().beginTransaction().remove( this ).commit();
	}
	else
	{
		Intent intent = CropImage.activity( Uri.fromFile( new File( imagePath ) ) ).getIntent( getContext() );
		startActivityForResult( intent, IMAGE_CROP_REQUEST_CODE );
	}
}
```

Reference: https://github.com/ArthurHub/Android-Image-Cropper/wiki/Using-built-in-CropImageActivity

**Comment by fayyadsufyan** [comment]
I am planning to crop images in Unity side after selecting the image from gallery. I think it is more easier than android native code.

**Comment by yasirkula** [comment]
I agree. And it would work on all platforms, too.

**Comment by yasirkula** [comment]
It'll be like self-promotion but after seeing that there is an absence of image cropper assets out there, I've created one myself. This time, however, I'm planning to sell it on Asset Store just to see how much money I can make from a paid asset and, of course, put some money in my pocket 😄 

If you are interested, here's the forum thread: https://forum.unity.com/threads/wip-image-cropper-multiplatform-image-cropping-solution-with-oval-mask-support.526901/

I'm closing this issue now. You can reopen it if there's something I can do.
