### ISSUE TITLE
filename of image picked?

### ISSUE THREAD

**Issue by yosun** [yasirkula/UnityNativeGallery#171]
Is it possible to get the filename of the picked image?

**Comment by yasirkula** [comment]
It is easy on Android by setting [this boolean](https://github.com/yasirkula/UnityNativeGallery/blob/c825a03c51555d0d33556554bb822f525fd0eef2/.github/AAR%20Source%20(Android)/java/com/yasirkula/unity/NativeGalleryMediaPickerFragment.java#L40) to true via AndroidJavaClass but requires considerable code refactoring on iOS (changing most lines with pickedMediaSavePath variable in NativeGallery.mm to preserve the filename).
