### ISSUE TITLE
android_requestLegacyExternalStorage="true" breaks builds for Android 9 and below

### ISSUE THREAD

**Issue by Mrmiffo** [yasirkula/UnityNativeGallery#175]
**Description of the bug**

After updating NativeGallery to the latest version our Unity project fails in the Gradle build step as android:requestLegacyExternalStorage does not exist prior to Android 10 sdk 29. We're building for Android 9 sdk 28.

**Reproduction steps**

- Set MinimumAPI level and Target API level to Android 9 API level 28 (or lower)
- Import NativeGallery plugin (latest version from Jan 2021)
- Build for Android. 

![image](https://user-images.githubusercontent.com/8545443/112619732-f1692280-8e27-11eb-99d6-a3d90129d761.png)

**Platform specs**

Please provide the following info if this is a Unity 3D repository.

- Unity version:  2019.4.18f1
- Platform:  Android
- Device: Samsung Galaxy S8, Android 9
- How did you download the plugin: Asset Store
- Gradle 6.8.3 (NOT unity built in version)

**Additional info**

See attached screenshot.

**Comment by yasirkula** [comment]
Please see the relevant FAQ entry: https://github.com/yasirkula/UnityNativeGallery#faq
