### ISSUE TITLE
image rotation after opening from gallery

### ISSUE THREAD

**Issue by dappledore** [yasirkula/UnityNativeGallery#18]
Hello,
I am using iOS 11.3 and iphone7+ . I open an image and the rotation of it is normally either 90 or 180 degrees different to the original image. 
I am putting the image into a  material like in your example and using in ARKit . Any idea why?

```
Material material = frame1.GetComponent<Renderer>().material;
if( !material.shader.isSupported ) // happens when Standard shader is not included in the build
material.shader = Shader.Find( "Legacy Shaders/Diffuse" );
if(material.mainTexture!=null) Destroy(material.mainTexture);
material.mainTexture = texture;
```

**Comment by yasirkula** [comment]
That's probably related to the orientation of the device while capturing the image. I think I can get the orientation of the image from its EXIF data and provide a helper function to rotate a Texture2D to its correct orientation.

I'm planning to implement this by the end of the week.

**Comment by dappledore-hotkey** [comment]
great!

**Comment by yasirkula** [comment]
Check out the **LoadImageAtPath** function in the latest commit.

**Comment by dappledore-hotkey** [comment]
ok i will check later

**Comment by dappledore** [comment]
i just tested it out and it works! thanks a lot

**Comment by caiocarvalho** [comment]
Hi! I am working on a game with versions for Android and Desktop. I was having the same issue with the rotation, and LoadImageAtPath worked fine for Android, but it doesn't work for Desktop. Do you have any idea of how to solve this rotation issue on Desktop? Thanks in advance

**Comment by yasirkula** [comment]
I haven't tested it myself, but the process should be similar to this:

- Import System.Drawing.dll to your project
- Use the Image class to get the correctly oriented image (see for reference: http://www.dotnet4techies.com/2014/09/reset-image-orientation-using-exif-in-c.html)
- (*optional*) Also resize the Image using the specified *maxSize*

**Comment by caiocarvalho** [comment]
Thank you, man!

**Comment by ROBYER1** [comment]
> Thank you, man!

Did you have an example of your implementation of this?
