### ISSUE TITLE
Can't I just callback images from a particular path?

### ISSUE THREAD

**Issue by JungUook** [yasirkula/UnityNativeGallery#180]
`NativeGallery.GetImageFromGallery((path)=>{},title,mime)`

You are about to call up a folder that has only a specific image in the mime portion of the code above.

Forexample
`NativeGallery.GetImageFromGallery((path)=>{},title, "image/myFolder/*")`

However, this will still navigate through all folders.

Is there any other good way?

**Comment by yasirkula** [comment]
You can't :)
