### ISSUE TITLE
Limit on picking media from gallery

### ISSUE THREAD

**Issue by ajathUnity** [yasirkula/UnityNativeGallery#181]
Is there any way to limit the amount of images or videos get picked from gallery, For example, Google allows 30 images to send at once. is there any way here to do the same, I want user to send 10 images at a time only.

**Comment by yasirkula** [comment]
Android doesn't have a parameter for it but on iOS 14+ it is possible: https://github.com/yasirkula/UnityNativeGallery/blob/d42e281c5afd47ab4dcb5bf86c9773b251f204d7/Plugins/NativeGallery/iOS/NativeGallery.mm#L551

Simply change this line to `config.selectionLimit = selectionLimit == 1 ? 1 : 10; // <- Limit is 10`
