### ISSUE TITLE
Google Play policy update (5th May) - Use of all files access permission

### ISSUE THREAD

**Issue by bor15bj** [yasirkula/UnityNativeGallery#182]
Hi yasirkula!

First of all, thank you so much for your incredible assets, they are very helpful and easy to use!

I am opening this issue because I have received some alerts for my apps when I am using Native Gallery (to download images).

The alert is:

"We've detected that your app contains the requestLegacyExternalStorage flag in the manifest file of 1 or more of your app bundles or APKs.

Developers with apps on devices running Android 11+ must use Scoped Storage to give users better access control over their device storage. To release your app on Android 11 or newer after May 5th, you must either:

Update your app to use more privacy friendly best practices, such as the Storage Access Framework or Media Store API
Update your app to declare the All files access (MANAGE_EXTERNAL_STORAGE) permission in the manifest file, and complete the All files access permission declaration in Play Console from May 5th
Remove the All files access permission from your app entirely
For apps targeting Android 11, the requestLegacyExternalStorage flag will be ignored. You must use the All files access permission to retain broad access.

Apps requesting access to the All files access permission without a permitted use will be removed from Google Play, and you won't be able to publish updates."

Are you going to update the asset so that we can continue using it? Or does the last update (13th April) cover that requirement?

More details can be found here: https://support.google.com/googleplay/android-developer/answer/10467955

Thank you so much for your time! Have a nice day!

**Comment by yasirkula** [comment]
My comment on this policy update so far: https://github.com/yasirkula/UnityNativeCamera/issues/52#issuecomment-817985562

There is an interesting paragraph in the support document you've linked, however:

> For now, if you think All files access is needed for your app, it is recommended that you don’t update your target SDK level to Android 11 (API level 30) at this time. If you target Android 10, consider using the requestLegacyExternalStorage flag.

Looks like _requestLegacyExternalStorage_ allows access to all files on Android 11+ if target SDK is set to Android 10. This might be what they are talking about. After setting target SDK to Android 11, _requestLegacyExternalStorage_ will no longer grant access to all files on Android 11+ but rather only on Android 10 devices, which is an [allowed use-case by the Android team](https://developer.android.com/about/versions/11/privacy/storage#scoped-storage).

Targetting Android 11 will be [mandatory by the end of the year](https://support.google.com/googleplay/android-developer/answer/9859152?hl=en&ref_topic=7072031#zippy=%2Ctarget-api-level-requirements-for-the-play-console). When people start setting target SDK to Android 11, there should no longer be an issue related to _requestLegacyExternalStorage_. Until that time, looking at the "For now" wording of the excerpt above, _requestLegacyExternalStorage_ shouldn't cause an issue while targeting Android 10 either.

**Comment by yasirkula** [comment]
Related: https://www.reddit.com/r/androiddev/comments/mqzls8/ominous_scoped_storage_warning_messages/

**Comment by Personuo** [comment]
On the other hand, if the target is not android11, then in August, the application can not be updated, and after November, if it is not updated, it will be removed
https://android-developers.googleblog.com/2020/11/new-android-app-bundle-and-target-api.html

**Comment by Personuo** [comment]
My understanding is that because requestLegacyExternalStorage and MANAGE_EXTERNAL_STORAGE some of the same role, so google sent an email alert, because google can not accurately determine, so together with a reminder may lead to the application update and delete.

**Comment by wesclarkemag** [comment]
Here are some basic facts for clarity about our project:

- We're targeting Android 11 (i.e API level 30)
- We're not specifying or using MANAGE_EXTERNAL_STORAGE
- WRITE_EXTERNAL_STORAGE and READ_EXTERNAL_STORAGE are specified in manifest
- NativeCamera works fine on Android 11 (Camera and Picking) and all Android versions below 10 for the same functions.
- Taking a photo (camera permission) works fine. Picking from Gallery does not work on Android 10
- Problem is specific to Android 10 (from our testing)
- If we specify _ requestLegacyExternalStorage_ in manifest, we'll get the warning from Google.

I did start looking into com.imagepicker.FileProvider provider to see if it needed extra permissions on Android 10, but this is really not my field. 

This seems like an administration FUBAR on Googles part. We're attempting to get in touch with Google for more clarity on this.

**Comment by yasirkula** [comment]
@Personuo After targeting Android 11 SDK, requestLegacyExternalStorage will have no effect on Android 11+ devices. So it would be illogical for Google to remove apps from Google Play if they use requestLegacyExternalStorage but set target API to Android 11 or later. I guess we'll have to wait for an official response from Google to clarify this matter.

@wesclarkemag I actually check if file is accessible via Java's File API and if it fails, I copy the file to temporaryCachePath. Yet it looks like, on Android 10, Java's FileInputStream works fine but C#'s File API doesn't. This is my humble conclusion, at least 🤷 

https://github.com/yasirkula/UnityNativeGallery/blob/d42e281c5afd47ab4dcb5bf86c9773b251f204d7/.github/AAR%20Source%20(Android)/java/com/yasirkula/unity/NativeGalleryMediaPickerFragment.java#L157-L188

**Comment by Personuo** [comment]
@yasirkula What google means is ,in from May, if your target is android 11 and use MANAGE_EXTERNAL_STORAGE , then you have to fill out the license application, tell google what you need to use MANAGE_EXTERNAL_STORAGE to do, whether it makes sense or not.This will determine whether your app is deleted or not


requestLegacyExternalStorage will not affect whether your app is deleted or not,requestLegacyExternalStorage just doesn't work anymore in android 11
But since requestLegacyExternalStorage is no longer useful after android11, will NativeGallery still work properly in android11?

**Comment by yasirkula** [comment]
They should've been clearer about requestLegacyExternalStorage not being related to "_All files access permission without a permitted use will be removed from Google Play, and you won't be able to publish updates_". People reading this rightly assume that requestLegacyExternalStorage will cause their apps to be removed from Google Play, the text is just confusing on that matter.

Plugin should work on Android 11 with or without requestLegacyExternalStorage.

**Comment by Personuo** [comment]
An interesting fact is that my account language is Chinese and the email I received in Chinese emphasized "<All files access permission>"
The last two sentences look like this in English:

For apps targeting Android 11, the requestLegacyExternalStorage flag will be ignored. You must use the <All files access permission> to retain broad access.

Apps requesting access to the <All files access permission> without a permitted use will be removed from Google Play, and you won't be able to publish updates."

So requestLegacyExternalStorage and <All files access permission> are different.

btw, I just started reading this message on my phone, my phone is in English, but my pc is in Chinese

**Comment by wesclarkemag** [comment]
> @Personuo After targeting Android 11 SDK, requestLegacyExternalStorage will have no effect on Android 11+ devices. So it would be illogical for Google to remove apps from Google Play if they use requestLegacyExternalStorage but set target API to Android 11 or later. I guess we'll have to wait for an official response from Google to clarify this matter.
> 
> @wesclarkemag I actually check if file is accessible via Java's File API and if it fails, I copy the file to temporaryCachePath. Yet it looks like, on Android 10, Java's FileInputStream works fine but C#'s File API doesn't. This is my humble conclusion, at least 🤷
> 
> https://github.com/yasirkula/UnityNativeGallery/blob/d42e281c5afd47ab4dcb5bf86c9773b251f204d7/.github/AAR%20Source%20(Android)/java/com/yasirkula/unity/NativeGalleryMediaPickerFragment.java#L157-L188

Seems like the exception we're having emerges from the java.io.* classes myself, not C#. But perhaps you mean the exception was captured there then handled and failed in C# code? It's... challenging to follow on Github by itself. :) 

`Image picker error: java.io.FileNotFoundException: /storage/emulated/0/DCIM/Screenshots/Screenshot_20210420-110237_Wordzee!.jpg: open failed: EACCES (Permission denied)`

**Comment by yasirkula** [comment]
All exceptions are catched in the above code. I'd be surprised if the exception you see really occurred on lines 164-165. Can you build the app in Development mode, capture the full stacktrace of the error and create a new Issue with it?

**Comment by bor15bj** [comment]
> They should've been clearer about requestLegacyExternalStorage not being related to "_All files access permission without a permitted use will be removed from Google Play, and you won't be able to publish updates_". People reading this rightly assume that requestLegacyExternalStorage will cause their apps to be removed from Google Play, the text is just confusing on that matter.
> 
> Plugin should work on Android 11 with or without requestLegacyExternalStorage.


Then what I understand is that there are two different things here:
1-The requestLegacyExternalStorage flag used in this asset is not the same as "All files access permission" and there's no problem continuing to use this asset (Android 11 devices will ignore the flag).
2-We can't still update our apps to target Android 11 (API level 30) until May.

**Comment by yasirkula** [comment]
1- That's my understanding, as well.
2- You can, why couldn't you?

**Comment by bor15bj** [comment]
> 1- That's my understanding, as well.
> 2- You can, why couldn't you?

You are right, that restriction is only applicable for apps that require "All files access permission"

I will close this issue, thank you all!
