### ISSUE TITLE
SaveToGallery editor callback

### ISSUE THREAD

**Issue by baado** [yasirkula/UnityNativeGallery#19]
hello,
for editor test, please add this code:
```csharp
#else
		if( callback != null )
			callback( null );
```
to here :)
https://github.com/yasirkula/UnityNativeGallery/blob/b7783824c26c42cbd227d8d99da759e340f2165b/Plugins/NativeGallery/NativeGallery.cs#L278

**Comment by yasirkula** [comment]
Done 😺
