### ISSUE TITLE
Android resource linking failed error

### ISSUE THREAD

**Issue by pbgame55** [yasirkula/UnityNativeGallery#191]
After installing the plugin, I get an error on compiling, details of the error:

- Android resource linking failed. 

- Execution failed for task ':processDebugResources'.

-  D:\Program Files\Unity\Filmmoovie\Temp\gradleOut\build\intermediates\merged_man1fests\debug\AndroidManifest.xml:39: error: attribute android:requestLegacyExternalStorage not found.

-   error: failed processing manifest.

- D:\Program Files\Unity\Filmmoovie\Temp\gradleOut\src\main\AndroidManifest.xml:12:7-78 Warning:

- Element meta-data#android.notch_support at AndroidManifest.xml:12:7-78 duplicated with element declared at AndroidManifest.xml:11:7-78

- D:\Program Files\Unity\Filmmoovie\Temp\gradleOut\src\main\AndroidManifest.xml:4:2-98 Warning:

- uses-permission#android.permission.READ_EXTERNAL_STORAGE was tagged at 

- AndroidManifest.xml:4 to replace another declaration but no other declaration present

I set write permission to external and a few solutions like changing the path to the manifest file did not work for me, what can I do about it?

**Comment by yasirkula** [comment]
Please see [FAQ](https://github.com/yasirkula/UnityNativeGallery#faq).
