### ISSUE TITLE
Native Gallery Issue with XCODE 12.5 12E262 after following manual method

### ISSUE THREAD

**Issue by clearsitedesigns** [yasirkula/UnityNativeGallery#194]
**Description of the bug**

**Reproduction steps**

1. Latest package from the git repo
2. Build in the unity version
3. Build in code

**Platform specs**

Please provide the following info if this is a Unity 3D repository.

- Unity version: *e.g. 2019.4.17f1
- Platform: IOS
- Device: iPhone 12PRO ios 14.5.1 (latest)
- How did you download the plugin: *e.g. Asset Store, GitHub, Package Manager. Please make sure that your asset is up-to-date* - From the repo github

**Additional info**

Issue does not appear to happen on the android build.

I've tried for about the last 4 hours to get this working. I've tried the manual process outlined your manual process since the error in the latest XCODE looks similar but I'm not getting anywhere.

https://github.com/yasirkula/UnityNativeGallery/wiki/Manual-Setup-for-iOS

Does it seem like something might have changed in the latest Xcode version perhaps? All the settings match and still every build to an iPhone 12 Pro ios 14.5.1 devices produce the following error.

 Its 16 total errors:
 
 
Showing All Issues
: "__NativeGallery_IsMediaPickerBusy", referenced from:

: _NGMediaReceiveCallbackiOS__NativeGallery_IsMediaPickerBusy_m1A933706D0F7692B6903EE7A9B5FC9ADDA51F1A8 in NativeGallery.Runtime.o

: _NGMediaReceiveCallbackiOS_Update_m1A6AA508217661179E1CA9EBB9C2B217C595E1F0 in NativeGallery.Runtime.o

: (maybe you meant: _NGMediaReceiveCallbackiOS__NativeGallery_IsMediaPickerBusy_m1A933706D0F7692B6903EE7A9B5FC9ADDA51F1A8)

: "__NativeGallery_GetVideoThumbnail", referenced from:

: _NativeGallery__NativeGallery_GetVideoThumbnail_m67187C1103D261E9F52143D7E917CA97939A3A0B in NativeGallery.Runtime.o

: (maybe you meant: _NativeGallery__NativeGallery_GetVideoThumbnail_m67187C1103D261E9F52143D7E917CA97939A3A0B)

: "__NativeGallery_GetVideoProperties", referenced from:

: _NativeGallery__NativeGallery_GetVideoProperties_m15490BBA47D7D480202BCF365228E91D891A5ECD in NativeGallery.Runtime.o

: (maybe you meant: _NativeGallery__NativeGallery_GetVideoProperties_m15490BBA47D7D480202BCF365228E91D891A5ECD)

: "__NativeGallery_PickMedia", referenced from:

: _NativeGallery__NativeGallery_PickMedia_m5241472884833F83137B5C3CFC6397556B732CDA in NativeGallery.Runtime.o

: _NativeGallery_GetMediaFromGallery_mC383E07B9E35CC3E92168E5FD9596AFB3F02F1C0 in NativeGallery.Runtime.o

: _NativeGallery_GetMultipleMediaFromGallery_mFD007A33CEAE1E85C948101FCBDFE82B9FEB3CE5 in NativeGallery.Runtime.o

: (maybe you meant: _NativeGallery__NativeGallery_PickMedia_m5241472884833F83137B5C3CFC6397556B732CDA)

: "__NativeGallery_VideoWriteToAlbum", referenced from:

: _NativeGallery__NativeGallery_VideoWriteToAlbum_mE90E4AF81DCAC29B0AE6EC9BBE754CE6709CCE7D in NativeGallery.Runtime.o

: (maybe you meant: _NativeGallery__NativeGallery_VideoWriteToAlbum_mE90E4AF81DCAC29B0AE6EC9BBE754CE6709CCE7D)

: "__NativeGallery_OpenSettings", referenced from:

: _NativeGallery__NativeGallery_OpenSettings_mAEDC55ADE8335C69F1FB1981EA1FF91D6710BAF7 in NativeGallery.Runtime.o

: _NativeGallery_OpenSettings_mAD76D7597380F0E0E5A7610CB9E13BE06237C38C in NativeGallery.Runtime.o

: (maybe you meant: _NativeGallery__NativeGallery_OpenSettings_mAEDC55ADE8335C69F1FB1981EA1FF91D6710BAF7)

: "__NativeGallery_ImageWriteToAlbum", referenced from:

: _NativeGallery__NativeGallery_ImageWriteToAlbum_m68ECB25739DB47C8883C8BE97ACDCDC2EA9F8C8F in NativeGallery.Runtime.o

: (maybe you meant: _NativeGallery__NativeGallery_ImageWriteToAlbum_m68ECB25739DB47C8883C8BE97ACDCDC2EA9F8C8F)

: "__NativeGallery_GetMediaTypeFromExtension", referenced from:

: _NativeGallery__NativeGallery_GetMediaTypeFromExtension_mB1772D19351F5B822C4FA29790E6A5E78C620EB5 in NativeGallery.Runtime.o

: _NativeGallery_GetMediaTypeOfFile_mF7A9CA2D534917B15EF249627420E71D48365B57 in NativeGallery.Runtime.o

: (maybe you meant: _NativeGallery__NativeGallery_GetMediaTypeFromExtension_mB1772D19351F5B822C4FA29790E6A5E78C620EB5)

: "__NativeGallery_GetImageProperties", referenced from:

: _NativeGallery__NativeGallery_GetImageProperties_m7208E7383AC627EEC8B87A63447B6B8261B22268 in NativeGallery.Runtime.o

: (maybe you meant: _NativeGallery__NativeGallery_GetImageProperties_m7208E7383AC627EEC8B87A63447B6B8261B22268)

: "__NativeGallery_CanOpenSettings", referenced from:

: _NativeGallery__NativeGallery_CanOpenSettings_m87481B92A27E8557F82EF70DDEE1F4F1474EBDF7 in NativeGallery.Runtime.o

: _NativeGallery_CanOpenSettings_m847639237A4E11935794EAE99D287AB837EC1BCA in NativeGallery.Runtime.o

: (maybe you meant: _NativeGallery__NativeGallery_CanOpenSettings_m87481B92A27E8557F82EF70DDEE1F4F1474EBDF7)

: "__NativeGallery_CanPickMultipleMedia", referenced from:

: _NativeGallery__NativeGallery_CanPickMultipleMedia_m7482F92F8449F098C78D1D2CB5CE26740E05240F in NativeGallery.Runtime.o

: _NativeGallery_CanSelectMultipleFilesFromGallery_m0693426E1BE05221AEB29DB7E501488657554C58 in NativeGallery.Runtime.o

: (maybe you meant: _NativeGallery__NativeGallery_CanPickMultipleMedia_m7482F92F8449F098C78D1D2CB5CE26740E05240F)

: "__NativeGallery_RequestPermission", referenced from:

: _NativeGallery__NativeGallery_RequestPermission_m2EA30B3A1C054AE33C4CF089461AC0C09924AC0B in NativeGallery.Runtime.o

: _NativeGallery_RequestPermission_mEADB867EE50805E34462DBB0D1D342DB237E7941 in NativeGallery.Runtime.o

: (maybe you meant: _NativeGallery__NativeGallery_RequestPermission_m2EA30B3A1C054AE33C4CF089461AC0C09924AC0B)

: "__NativeGallery_LoadImageAtPath", referenced from:

: _NativeGallery__NativeGallery_LoadImageAtPath_mA0D2A6A62DC01256EF74FF5C236F6806BE3F8F2A in NativeGallery.Runtime.o

: (maybe you meant: _NativeGallery__NativeGallery_LoadImageAtPath_mA0D2A6A62DC01256EF74FF5C236F6806BE3F8F2A)

: "__NativeGallery_ShowLimitedLibraryPicker", referenced from:

: _NativeGallery__NativeGallery_ShowLimitedLibraryPicker_m9EF5EB7300BD49F0B2B5567A9FE2BD0BF5F9D809 in NativeGallery.Runtime.o

: _NativeGallery_TryExtendLimitedAccessPermission_m0D1D92FB05B5C85A8AD0F96031B630C4D834B9CD in NativeGallery.Runtime.o

: (maybe you meant: _NativeGallery__NativeGallery_ShowLimitedLibraryPicker_m9EF5EB7300BD49F0B2B5567A9FE2BD0BF5F9D809)

: "__NativeGallery_CheckPermission", referenced from:

: _NativeGallery__NativeGallery_CheckPermission_mEFBFF9179DB9AEE59ACAE58B4017E185DC99901A in NativeGallery.Runtime.o

: _NativeGallery_CheckPermission_m6CBB87E6602B4B6BEAACADBCFAEBA442C7EEC4DB in NativeGallery.Runtime.o

: (maybe you meant: _NativeGallery__NativeGallery_CheckPermission_mEFBFF9179DB9AEE59ACAE58B4017E185DC99901A)

: Symbol(s) not found for architecture arm64

: Linker command failed with exit code 1 (use -v to see invocation)

**Comment by bogusindustries** [comment]
Im having similar issues after trying automated and manual modes

Description of the bug

Reproduction steps

Latest package from Unity Asset store
Build in the unity version
Build in code
Platform specs

Please provide the following info if this is a Unity 3D repository.

Unity version: 2019.4.26f1
Platform: IOS
Device: iPhone X ios 14.5.1 (latest)
How did you download the plugin: Asset Store

3 total errors:
Undefined symbols for architecture arm64:
  "__NativeGallery_PickVideo", referenced from:
      _NativeGallery__NativeGallery_PickVideo_m016D5178CBB45181DF5A0298F90779D8D3589BDC in NativeGallery.Runtime.o
      _NativeGallery_GetMediaFromGallery_mC383E07B9E35CC3E92168E5FD9596AFB3F02F1C0 in NativeGallery.Runtime.o
     (maybe you meant: _NativeGallery__NativeGallery_PickVideo_m016D5178CBB45181DF5A0298F90779D8D3589BDC)
  "__NativeGallery_PickImage", referenced from:
      _NativeGallery__NativeGallery_PickImage_m7F54B62C0B0C9357014DE9979D919AFB762F4F1A in NativeGallery.Runtime.o
      _NativeGallery_GetMediaFromGallery_mC383E07B9E35CC3E92168E5FD9596AFB3F02F1C0 in NativeGallery.Runtime.o
     (maybe you meant: _NativeGallery__NativeGallery_PickImage_m7F54B62C0B0C9357014DE9979D919AFB762F4F1A)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by yasirkula** [comment]
I honestly don't know why it suggests `_NativeGallery__NativeGallery_PickVideo` while the function is named `_NativeGallery_PickVideo`. I'd recommend you to try building the plugin on a new project to see if it succeeds.

**Comment by bogusindustries** [comment]
> I honestly don't know why it suggests `_NativeGallery__NativeGallery_PickVideo` while the function is named `_NativeGallery_PickVideo`. I'd recommend you to try building the plugin on a new project to see if it succeeds.

I'll give it a try

**Comment by bogusindustries** [comment]
What turned out to be the problem for us was when we updated from the asset store, it was somehow referencing a cache file and instead of updating, it just re-downloaded an older version of the plugin. Once we found that out and got the plugin to actually update it worked.
