### ISSUE TITLE
iOS automated setup on 2019 LTS not working

### ISSUE THREAD

**Issue by TCemAlpaydin** [yasirkula/UnityNativeGallery#197]
We have an android version and an ios version of the app. Unity exports are mainly added to native application. iOS builds do not save intended images to gallery whilst not reporting any errors in the meantime, while android does everything correctly. And the ios manual setup returns "undefined symbol" errors.
 We were not able to pinpoint the exact issue here, as unity dev is separate from ios native dev, but at least the automated setup for ios doesn't seem to work. (as there are no steps for me to do with the given specs)
![ios_nativegallery_xcode_error](https://user-images.githubusercontent.com/50211446/119612425-8aa2be00-be04-11eb-85e3-8a91bfa5a00f.jpeg)

**Comment by yasirkula** [comment]
- `ios manual setup returns "undefined symbol" errors`
- `at least the automated setup for ios doesn't seem to work`

So, are both manual and automated setups not working?

**Comment by yasirkula** [comment]
After building your project using automated setup, what is the value of _UnityFramework Target_'s `Other Linker Flags`?

**Comment by PabloBuitrago** [comment]
I get the same error:

![image](https://user-images.githubusercontent.com/31513526/119644348-0d377780-be1d-11eb-99d2-f03e39cef406.png)
![image](https://user-images.githubusercontent.com/31513526/119644400-19233980-be1d-11eb-8c07-39819d0e25ab.png)


I have been working without any problem, my version of Unity (2019.4.8f1) has not changed.

The only thing that changes is the new version in iOS 14.6 an update of Xcode.

**Comment by PabloBuitrago** [comment]
![image](https://user-images.githubusercontent.com/31513526/119645017-dada4a00-be1d-11eb-80c9-7f80f75a4fde.png)

This is the value in Other Linker Flags

**Comment by TCemAlpaydin** [comment]
I am checking on the UnityFramework target thing, ios dev is not in today.

**Comment by yasirkula** [comment]
> ![image](https://user-images.githubusercontent.com/31513526/119645017-dada4a00-be1d-11eb-80c9-7f80f75a4fde.png)
> 
> This is the value in Other Linker Flags

Thanks! Can you post Other Linker Flags of other **TARGETS**, too?

**Comment by PabloBuitrago** [comment]
I don't see any. Only in UnityFramework.

![image](https://user-images.githubusercontent.com/31513526/119647764-f430c580-be20-11eb-96e1-56380469ebda.png)

**Comment by yasirkula** [comment]
Can you search all scripts in your Unity project for the term SetBuildProperty and report all usages of it to me? You can search the term in the Entire Solution via CTRL+Shift+F on Visual Studio. Afterwards, can you check if the issue can be reproduced on a new project?

**Comment by PabloBuitrago** [comment]
The only SetBuildProperty is the ENABLE_BITCODE to NO, since an external library does not work with ENABLE_BITCODE.

I've been testing a new project:

- I have changed the architecture testing Universal and ARM64 architectures (Since in my application the ARM64 architecture is required by the ARFoundation package).

- I have tried enabling ENABLE_BITCODE and disabling it.

All builds have worked correctly with a new project. I am not very clear that the error may be giving.

**Comment by PabloBuitrago** [comment]
I update the Asset in Unity Asset Store and now is working fine

**Comment by yasirkula** [comment]
It's good to hear. I'm guessing you weren't using the latest GitHub version either since GitHub and Asset Store versions are supposed to be the same.

@TCemAlpaydin Can you delete the plugin's folder completely and reimport the latest version?

**Comment by TCemAlpaydin** [comment]
Updated, thanks for the immediate response by the way.
Will see if it works today.

**Comment by PabloBuitrago** [comment]
Many Thanks, for the attention and for the help.

It's funny, yesterday I deleted the version I had and reinstalled the version from the Unity Asset Store, and it didn't work well. I have had problems with some assets that did not download the latest version (maybe that is the problem).
