### ISSUE TITLE
Picking Large files freezes app for more than 10 seconds

### ISSUE THREAD

**Issue by jayaram9877** [yasirkula/UnityNativeGallery#198]
**Description of the bug**

Whenever users selects a large video file the app freezes for few seconds( more than 10 seconds).

**Reproduction steps**
1. Select a large video file. 

**Platform specs**

Please provide the following info if this is a Unity 3D repository.

- Unity version: *e.g. 2020.3.11f1(LTS)*
- Platform: Android
- Device: One plus nord with android 11
- How did you download the plugin: Asset store

**Additional info**
NO errors or warnings in the  Log

**Comment by yasirkula** [comment]
If picked video's file path can't be determined or the path is inaccessible via File API, then the video is copied to temporaryCachePath: https://github.com/yasirkula/UnityNativeGallery/blob/0bc6c23925e899e44506f13061287b0f24735957/.github/AAR%20Source%20(Android)/java/com/yasirkula/unity/NativeGalleryMediaPickerFragment.java#L187-L188

**Comment by jayaram9877** [comment]
```
        NativeGallery.Permission permission = NativeGallery.GetVideosFromGallery((paths) =>
            {
                Debug.Log("Media path: " + paths);
                if (paths != null)
                {
                    videoPaths = paths;
                    Debug.Log(videoPath);
                    anim["SleectSubs"].speed = 1;
                    anim.Play();
                }
            }, "Select any 5 video");
```

This is my code.

**Comment by yasirkula** [comment]
Copy operation takes place in the native side, so it's inevitable regardless of how your code is structured. Out of curiosity, what does the "_Selected media uri:_ " log output?

**Comment by jayaram9877** [comment]
I am sorry i don't know how i  missed to reply this. To your question it's printing the path to file.

**Comment by yasirkula** [comment]
Yes I wanted to know what that path is.
