### ISSUE TITLE
Xcode Build Fails

### ISSUE THREAD

**Issue by ONTOPStudios** [yasirkula/UnityNativeGallery#199]
Hello there,

First of all thank you for the amazing plugin! We've been using it for some time and it's been quite seamless to work with on our apps. 

But we got stuck with a problem today, while trying to build the app, on the Xcode side. We're getting these errors:

Undefined symbol: _OBJC_CLASS_$_PHPickerViewController
Undefined symbol: _OBJC_CLASS_$_PHPickerFilter
Undefined symbol: _OBJC_CLASS_$_PHPickerConfiguration

Undefined symbols for architecture arm64:
 "_OBJC_CLASS_$_PHPickerViewController", referenced from:
   objc-class-ref in NativeGallery.o
 "_OBJC_CLASS_$_PHPickerFilter", referenced from:
   objc-class-ref in NativeGallery.o
 "_OBJC_CLASS_$_PHPickerConfiguration", referenced from:
   objc-class-ref in NativeGallery.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

This started happening when we updated to this last version available 1.6.3 . We updated because there was another error happening with the version before that we were using (probably due to Xcode update, we didn't change anything in code), so downgrading version in this case will just swap errors. Any idea of what may be causing this? Greatly appreciated of any help you can provide on this.

macOS: 11.3.1
Xcode: 12.5 (12E262)
Unity: 2019.4.18f1

Best Regards

**Comment by yasirkula** [comment]
Are you doing manual setup or automated setup?

**Comment by Noblauch** [comment]
Getting the same error here, the project is not able to compile anymore for iOS. This only occurred after we updated to Mac OS 11.4 and Xcode 12.5

**Comment by yasirkula** [comment]
Are you doing manual setup or automated setup? Does removing the plugin completely and downloading the latest version from Asset Store help? And to be sure, use Replace instead of Append after updating the plugin.

**Comment by Noblauch** [comment]
> Are you doing manual setup or automated setup? Does removing the plugin completely and downloading the latest version from Asset Store help? And to be sure, use Replace instead of Append after updating the plugin.

Thank you for your fast reply!
As I mentioned, downloading the latest version from the Asset Store (1.6.3 Package Manager) is not actually the latest version. The version there includes semantic errors on iOS (incompatible pointer).

However, after downloading the version manually (here from Github) and after that deleting the complete build and rebuilding, it works again! Since I experienced the same issues as @ONTOPStudios (exact same errors) I recommend you to delete your Unity Build as-well and rebuild it, this fixed it in my case.

Thanks again @yasirkula ! I bought you a coffee ;)

Greetings from Hamburg / Germany!

**Comment by yasirkula** [comment]
Thank you for your support! [Manual setup](https://github.com/yasirkula/UnityNativeGallery/wiki/Manual-Setup-for-iOS) requires modifying the Xcode project and one of these steps is related to PHPickerViewController (`weak_framework PhotosUI`). If you didn't modify the plugin after importing it, then you've used the automated setup which does all the hard work for you automatically (recommended approach).

**Comment by ONTOPStudios** [comment]
Hey @yasirkula ! Thank you for your fast reply and sorry for the delay. We're doing it manually since we're building Unity as a library to integrate inside a native iOS app, but we didn't do this step for the manual support you're talking about, probably it wasn't needed before. Something might have changed in this Xcode 12.5 that might require it now, or at least that looks like the best shot. We'll try this step of the Manual setup you're suggesting and will get back to you once I have any news to share.

@Noblauch Thank you for the suggestion! We tried it before but no luck. Tried both packages from Asset Store and Github releases and tried cleaning up the plugin's folder from the project and importing it again. Same error would happen in the end. Probably something in our case is different due to the setup being manual

**Comment by ONTOPStudios** [comment]
Hey @yasirkula ! Bug is fixed! Looks like it was the missing Manual setup you suggested. Something probably changed with the new Xcode version and now it requires us to do this extra step of the manual integration. Thanks for your amazing support! Cheers :)

**Comment by alienniki** [comment]
I have been struggling with this problem for 2 days now. I tried automatic and manual assembly. I connected the plugin via package manager and embedded it into the project. Building a project through Unity Editor and through CI Jenkins. I blocked the NGPostProcessBuild method call.OnPostprocessBuild. If Jenkins builds, then the OnPostprocessBuild call does not occur, respectively, the project is not being assembled. I'm trying to figure out why Unity doesn't call OnPostprocessBuild. If I find the reason, I will definitely write a solution.

**Comment by yasirkula** [comment]
@alienniki Please review the threads that come up with "jenkins OnPostprocessBuild not called" search, I hope one of the solutions resolve the issue 😃

**Comment by alienniki** [comment]
> @alienniki Please review the threads that come up with "jenkins OnPostprocessBuild not called" search, I hope one of the solutions resolve the issue 😃

I'm copying a project from the repository. The first run of the Unity build in batch mode does not cause OnPostprocessBuild, the restart does. Strange behavior. I'm figuring it out further.

**Comment by alienniki** [comment]
I added the test code to
`	public class NGPostProcessBuild : IPostprocessBuildWithReport
	{
        public void OnPostprocessBuild(BuildReport report)
        {
            Debug.Log("test>>>>");
#if UNITY_IOS
            Debug.Log("run ios>>>>");
#else
            Debug.Log("run no ios>>>>");
#endif
#if UNITY_IOS
}
}
`
First run log:
[INFO] 2022-09-16 15:52:23.039 defaults[30300:12848819] 
[INFO] The domain/default pair of (com.apple.dt.Xcode.plist, IDECustomDerivedDataLocation) does not exist
[INFO] test>>>>
[INFO] UnityEngine.StackTraceUtility:ExtractStackTrace () (at /Users/bokken/buildslave/unity/build/Runtime/Export/Scripting/StackTrace.cs:37)
[INFO] UnityEngine.DebugLogHandler:LogFormat (UnityEngine.LogType,UnityEngine.Object,string,object[])
[INFO] UnityEngine.Logger:Log (UnityEngine.LogType,object)
[INFO] UnityEngine.Debug:Log (object)
[INFO] NativeGalleryNamespace.NGPostProcessBuild:OnPostprocessBuild (UnityEditor.Build.Reporting.BuildReport) (at Assets/NativeGallery/Editor/NGPostProcessBuild.cs:95)
[INFO] UnityEditor.Build.BuildPipelineInterfaces/<>c__DisplayClass17_0:<OnBuildPostProcess>b__1 (UnityEditor.Build.IPostprocessBuildWithReport) (at /Users/bokken/buildslave/unity/build/Editor/Mono/BuildPipeline/BuildPipelineInterfaces.cs:456)
[INFO] UnityEditor.Build.BuildPipelineInterfaces:InvokeCallbackInterfacesPair<UnityEditor.Build.IPostprocessBuild, UnityEditor.Build.IPostprocessBuildWithReport> (System.Collections.Generic.List`1<UnityEditor.Build.IPostprocessBuild>,System.Action`1<UnityEditor.Build.IPostprocessBuild>,System.Collections.Generic.List`1<UnityEditor.Build.IPostprocessBuildWithReport>,System.Action`1<UnityEditor.Build.IPostprocessBuildWithReport>,bool) (at /Users/bokken/buildslave/unity/build/Editor/Mono/BuildPipeline/BuildPipelineInterfaces.cs:406)
[INFO] UnityEditor.Build.BuildPipelineInterfaces:OnBuildPostProcess (UnityEditor.Build.Reporting.BuildReport) (at /Users/bokken/buildslave/unity/build/Editor/Mono/BuildPipeline/BuildPipelineInterfaces.cs:454)
[INFO] UnityEditor.BuildPipeline:BuildPlayerInternal (string[],string,string,UnityEditor.BuildTargetGroup,UnityEditor.BuildTarget,UnityEditor.BuildOptions,string[]) (at /Users/bokken/buildslave/unity/build/Editor/Mono/BuildPipeline.bindings.cs:422)
[INFO] UnityEditor.BuildPipeline:BuildPlayer (string[],string,string,UnityEditor.BuildTargetGroup,UnityEditor.BuildTarget,UnityEditor.BuildOptions,string[]) (at /Users/bokken/buildslave/unity/build/Editor/Mono/BuildPipeline.bindings.cs:321)
[INFO] UnityEditor.BuildPipeline:BuildPlayer (UnityEditor.BuildPlayerOptions) (at /Users/bokken/buildslave/unity/build/Editor/Mono/BuildPipeline.bindings.cs:295)
[INFO] UnityEditor.BuildPipeline:BuildPlayer (string[],string,UnityEditor.BuildTarget,UnityEditor.BuildOptions) (at /Users/bokken/buildslave/unity/build/Editor/Mono/BuildPipeline.bindings.cs:290)
[INFO] UnityBuilder.ApplicationUnityBuilder:BuildPlayer (string[],string,UnityEditor.BuildTarget,UnityEditor.BuildOptions) (at Library/PackageCache/com.tortuga.unity-builder@1.4.13/Assets/unity-builder/Scripts/UnityBuilder/ApplicationUnityBuilder.cs:278)
[INFO] UnityBuilder.ApplicationUnityBuilder:PerformIOSBuild () (at Library/PackageCache/com.tortuga.unity-builder@1.4.13/Assets/unity-builder/Scripts/UnityBuilder/ApplicationUnityBuilder.cs:180)
[INFO] 
[INFO] (Filename: Assets/NativeGallery/Editor/NGPostProcessBuild.cs Line: 95)
[INFO] 
[INFO] run no ios>>>>
[INFO] UnityEngine.StackTraceUtility:ExtractStackTrace () (at /Users/bokken/buildslave/unity/build/Runtime/Export/Scripting/StackTrace.cs:37)
[INFO] UnityEngine.DebugLogHandler:LogFormat (UnityEngine.LogType,UnityEngine.Object,string,object[])
[INFO] UnityEngine.Logger:Log (UnityEngine.LogType,object)
[INFO] UnityEngine.Debug:Log (object)
[INFO] NativeGalleryNamespace.NGPostProcessBuild:OnPostprocessBuild (UnityEditor.Build.Reporting.BuildReport) (at Assets/NativeGallery/Editor/NGPostProcessBuild.cs:99)
[INFO] UnityEditor.Build.BuildPipelineInterfaces/<>c__DisplayClass17_0:<OnBuildPostProcess>b__1 (UnityEditor.Build.IPostprocessBuildWithReport) (at /Users/bokken/buildslave/unity/build/Editor/Mono/BuildPipeline/BuildPipelineInterfaces.cs:456)
[INFO] UnityEditor.Build.BuildPipelineInterfaces:InvokeCallbackInterfacesPair<UnityEditor.Build.IPostprocessBuild, UnityEditor.Build.IPostprocessBuildWithReport> (System.Collections.Generic.List`1<UnityEditor.Build.IPostprocessBuild>,System.Action`1<UnityEditor.Build.IPostprocessBuild>,System.Collections.Generic.List`1<UnityEditor.Build.IPostprocessBuildWithReport>,System.Action`1<UnityEditor.Build.IPostprocessBuildWithReport>,bool) (at /Users/bokken/buildslave/unity/build/Editor/Mono/BuildPipeline/BuildPipelineInterfaces.cs:406)
[INFO] UnityEditor.Build.BuildPipelineInterfaces:OnBuildPostProcess (UnityEditor.Build.Reporting.BuildReport) (at /Users/bokken/buildslave/unity/build/Editor/Mono/BuildPipeline/BuildPipelineInterfaces.cs:454)
[INFO] UnityEditor.BuildPipeline:BuildPlayerInternal (string[],string,string,UnityEditor.BuildTargetGroup,UnityEditor.BuildTarget,UnityEditor.BuildOptions,string[]) (at /Users/bokken/buildslave/unity/build/Editor/Mono/BuildPipeline.bindings.cs:422)
[INFO] UnityEditor.BuildPipeline:BuildPlayer (string[],string,string,UnityEditor.BuildTargetGroup,UnityEditor.BuildTarget,UnityEditor.BuildOptions,string[]) (at /Users/bokken/buildslave/unity/build/Editor/Mono/BuildPipeline.bindings.cs:321)
[INFO] UnityEditor.BuildPipeline:BuildPlayer (UnityEditor.BuildPlayerOptions) (at /Users/bokken/buildslave/unity/build/Editor/Mono/BuildPipeline.bindings.cs:295)
[INFO] UnityEditor.BuildPipeline:BuildPlayer (string[],string,UnityEditor.BuildTarget,UnityEditor.BuildOptions) (at /Users/bokken/buildslave/unity/build/Editor/Mono/BuildPipeline.bindings.cs:290)
[INFO] UnityBuilder.ApplicationUnityBuilder:BuildPlayer (string[],string,UnityEditor.BuildTarget,UnityEditor.BuildOptions) (at Library/PackageCache/com.tortuga.unity-builder@1.4.13/Assets/unity-builder/Scripts/UnityBuilder/ApplicationUnityBuilder.cs:278)
[INFO] UnityBuilder.ApplicationUnityBuilder:PerformIOSBuild () (at Library/PackageCache/com.tortuga.unity-builder@1.4.13/Assets/unity-builder/Scripts/UnityBuilder/ApplicationUnityBuilder.cs:180)
[INFO] 

As you can see at the first launch Unity thinks it's not IOS

**Comment by yasirkula** [comment]
I haven't used Jenkins or Unity's command line arguments so I really can't tell. I'd recommend searching about this issue online.

**Comment by jgitt** [comment]
For anyone with same issue as @alienniki where this error appears in Jenkins, I think it may be an issue with Unity being run in batch mode.

UNITY_IOS doesn't seem to behave consistently when being run in batch mode -- meaning the initial clean build results in UNITY_IOS being false, whereas subsequent builds may return true.

My quick fix was just to make a copy of the *NGPostProcessBuild* class inside *NGPostProcessBuild.cs* and replace the UNITY_IOS directives with UNITY_EDITOR_OSX.
