### ISSUE TITLE
Moving GIF on iOS

### ISSUE THREAD

**Issue by nathanqueija** [yasirkula/UnityNativeGallery#2]
Hi!
First I'd like to thank you for your work. Awesome!
Is ti possible or there is any workaround to save gif files to the gallery on iOS?
On Android it works fine, but on iOS I get the following error:

Error Domain=AVFoundationErrorDomain Code=-11828 "Cannot Open" UserInfo={NSUnderlyingError=0x1c0658810 {Error Domain=NSOSStatusErrorDomain Code=-12847 "(null)"}, NSLocalizedFailureReason=This media format is not supported.

**Comment by yasirkula** [comment]
Can you try changing lines **12-15** of *Plugins/iOS/NativeGallery.mm* as following:

```objective-c
NSData *data = [NSData dataWithContentsOfFile:path];
[[PHPhotoLibrary sharedPhotoLibrary] performChanges:^{
	PHAssetResourceCreationOptions *options = [[PHAssetResourceCreationOptions alloc] init];
	[[PHAssetCreationRequest creationRequestForAsset] addResourceWithType:PHAssetResourceTypePhoto data:data options:options];
} completionHandler:^(BOOL success, NSError * _Nullable error) {
	[[NSFileManager defaultManager] removeItemAtPath:path error:nil];
}];
```

Source: https://stackoverflow.com/a/40373739/2373034

**Comment by nathanqueija** [comment]
Hi @yasirkula. Thanks for your response.
I tried what you said but I got the following error:

/Libraries/Plugins/iOS/NativeGallery.mm:13:7: Use of undeclared identifier 'PHPhotoLibrary'

I need to import any package on the file?

Thanks

**Comment by yasirkula** [comment]
Try putting **#import <Photos/Photos.h>** to the top of *Plugins/iOS/NativeGallery.mm*. Also, I think you will have to add **Photos** framework (if exists) to "Link Binary With Libraries".

Be aware that using Photos framework requires **iOS 8** minimum.

Credits: https://stackoverflow.com/questions/26595343/determine-if-the-access-to-photo-library-is-set-or-not-phphotolibrary

**Comment by nathanqueija** [comment]
Now I get these errors:

Undefined symbols for architecture armv7:
  "_OBJC_CLASS_$_PHAssetResourceCreationOptions", referenced from:
      objc-class-ref in NativeGallery.o

I tried to change the architecture but i get the same error.
I need to link any resource?

**Comment by nathanqueija** [comment]
I got it!
I had to link Photo Library on Build Phases.
It's working now!
thanks!!!
