### ISSUE TITLE
Xcode Build error (incompatible pointer)

### ISSUE THREAD

**Issue by Noblauch** [yasirkula/UnityNativeGallery#200]
After updating Mac OS to 11.4 and Xcode to 12.5 we can't build anymore!

We have a similar bug as ONTOPStudios. However the compile errors we are getting are different.
We get two incompatible pointer errors, that prevent the Unity project to compile:
![Xcode incompatible pointer](https://user-images.githubusercontent.com/23262032/121507147-a8ffe080-c9e4-11eb-9057-686bd912369f.png)

Both errors are inside NativeGallery.mm
Error 1:
```
// Credit: https://stackoverflow.com/a/10531752/2373034
+ (void)pickMedia:(int)mediaType savePath:(NSString *)mediaSavePath {
	imagePicker = [[UIImagePickerController alloc] init];
	imagePicker.delegate = self; <––––– ERROR OCCURS HERE
	imagePicker.allowsEditing = NO;
	imagePicker.sourceType = UIImagePickerControllerSourceTypePhotoLibrary;
        [...]
```

Error 2:
```
        [...]
	else { // iPad
		popup = [[UIPopoverController alloc] initWithContentViewController:imagePicker];
		popup.delegate = self; <––––– ERROR OCCURS HERE
		[popup presentPopoverFromRect:CGRectMake( rootViewController.view.frame.size.width / 2, rootViewController.view.frame.size.height / 2, 1, 1 ) inView:rootViewController.view permittedArrowDirections:0 animated:YES];
	}
       [...]
```

I then updated native gallery, since I thought this was just a version issue, but the error stayed, I'm on the newest version.
We are blocked by this completely, I know this plugin is free and all, but any help for a workaround would be appreciated!

**Comment by yasirkula** [comment]
Your plugin is not up-to-date:

https://github.com/yasirkula/UnityNativeGallery/blob/0bc6c23925e899e44506f13061287b0f24735957/Plugins/NativeGallery/iOS/NativeGallery.mm#L574

https://github.com/yasirkula/UnityNativeGallery/blob/0bc6c23925e899e44506f13061287b0f24735957/Plugins/NativeGallery/iOS/NativeGallery.mm#L615

I've downloaded the latest version from both GitHub and Asset Store on Unity 2019.4.26f1 and both of them were up-to-date. How could you download the latest version and not have the plugin up-to-date?

**Comment by Noblauch** [comment]
![Bildschirmfoto 2021-06-10 um 12 43 46](https://user-images.githubusercontent.com/23262032/121511964-815f4700-c9e9-11eb-902f-a3b11362e364.png)
Hm strange, I updated via the package manager, and this is the version that still caused it, let me check!

**Comment by Noblauch** [comment]
Okay, I deleted the whole NativeGallery folder and reimported via the package manager, and the version still mismatches the fix. Hence the Asset Store / Package Manager version is not correct.

I downloaded the repository here and added the Native Gallery Plugin from there, now these errors are fixed, thanks for the lightning fast response!!

However now I'm getting the same errors as ONTOPStudios. I'll comment on that too. Thank you so far!

**Comment by yasirkula** [comment]
There must have been some sort of Package Manager cache issue because I've added the plugin via Package Manager to a new project and it was the up-to-date version.

![ss](https://user-images.githubusercontent.com/10211608/121517730-5fb98c00-c9f8-11eb-951a-f96ace134179.png)

**Comment by Noblauch** [comment]
> There must have been some sort of Package Manager cache issue because I've added the plugin via Package Manager to a new project and it was the up-to-date version.
> 
> ![ss](https://user-images.githubusercontent.com/10211608/121517730-5fb98c00-c9f8-11eb-951a-f96ace134179.png)

But you are Using a GIT ref to the package. I get the content from the "My Assets" category of the package manager, since I got the plugin from the asset store. I'm not sure how to handle Asset Store Asset updates as a developer, but there is certainly an issue on the content there.
![Bildschirmfoto 2021-06-10 um 14 31 03](https://user-images.githubusercontent.com/23262032/121525336-7e1f8780-c9f8-11eb-93b7-f94a2fbaaef8.png)

**Comment by yasirkula** [comment]
It must be some sort of cache issue. I've deleted Asset Store cache (just to be sure), downloaded 1.6.3 via Package Manager and the code was up-to-date.

![ss](https://user-images.githubusercontent.com/10211608/121534443-e9258a00-ca09-11eb-8a05-8f69f7776f20.png)

**Comment by yasirkula** [comment]
Could you do this one test for me when you get the chance:

- Import the plugin via Package Manager on a new Unity project and see if the code is up-to-date
- If not, delete `C:\Users\USERNAME\AppData\Roaming\Unity\Asset Store-5.x\yasirkula\ScriptingIntegration\Native Gallery for Android iOS.unitypackage`, restart Unity and download the plugin via Package Manager again. Then see if the code is up-to-date

**Comment by Noblauch** [comment]
> Could you do this one test for me when you get the chance:
> 
> * Import the plugin via Package Manager on a new Unity project and see if the code is up-to-date
> * If not, delete `C:\Users\USERNAME\AppData\Roaming\Unity\Asset Store-5.x\yasirkula\ScriptingIntegration\Native Gallery for Android iOS.unitypackage`, restart Unity and download the plugin via Package Manager again. Then see if the code is up-to-date

Indeed the code is up to date if I import it into a new Project. If you didn't upload anything in the meantime, there is probably some issue with the update workflow in existing projects. Though I never experienced something like this.

**Comment by yasirkula** [comment]
For reference, here's a related forum thread about this cache issue (seems to be a Unity bug): https://forum.unity.com/threads/package-manager-not-showing-latest-version-from-asset-store.791718/
