### ISSUE TITLE
SaveImageToGallery  report errors

### ISSUE THREAD

**Issue by JackeAstray** [yasirkula/UnityNativeGallery#201]
**Description of the bug**

The following methods are used
```
NativeGallery.SaveImageToGallery(bytes, "Screen", tempName);
```
After taking a screenshot and saving the picture to the album, an error will be reported
Platform is android 11

**Platform specs**

- Unity version: *e.g. 2019.3.3f1*
- Platform: *e.g. Android*
- Device: *Android 11*
- GitHub 1.6.3*

**Additional info**

AndroidJavaException: java.lang.NoSuchMethodError: no static method with name='SaveMedia' signature='(Lcn.jiguang.unity.push.UnityPluginActivity;ILjava/lang/String;Ljava/lang/String;)Ljava/lang/String;' in class Ljava.lang.Object;
java.lang.NoSuchMethodError: no static method with name='SaveMedia' signature='(Lcn.jiguang.unity.push.UnityPluginActivity;ILjava/lang/String;Ljava/lang/String;)Ljava/lang/String;' in class Ljava.lang.Object;
com.unity3d.player.ReflectionHelper.getMethodID(Unknown Source:167)
com.unity3d.player.UnityPlayer.nativeRender(Native Method)
com.unity3d.player.UnityPlayer.access$300(Unknown Source:0)
com.unity3d.player.UnityPlayer$e$1.handleMessage(Unknown Source:95)
android.os.Handler.dispatchMessage(Handler.java:102)
android.os.Looper.loop(Looper.java:246)
com.unity3d.player.UnityPlayer$e.run(Unknown Source:20)
UnityEngine.AndroidJNISafe.CheckException () (at <00000000000000000000000000000000>:0)
UnityEngine.AndroidJNISafe.CallStaticObjectMethod (System.IntPtr clazz, System.IntPtr methodID, UnityEngine.jvalue[] args) (at <00000000000000000000000000000000>:0)
UnityEngine.AndroidReflection.GetMethodMember (System.IntPtr jclass, System.String methodName, System.String signature, System.Boolean isStatic) (at <00000000000000000000000000000000>:0)
UnityEngine._AndroidJNIHelper.GetMethodID (System.IntPtr jclass, System.String methodName, System.String signature, System.Boolean isStatic) (at <00000000000000000000000000000000>:0)
UnityEngine.AndroidJavaObject._CallStatic[ReturnType] (System.String methodName, System.Object[] args) (at <00000000000000000000000000000000>:0)
NativeGallery.SaveToGalleryInternal (System.String path, System.String album, NativeGallery+MediaType mediaType, NativeGallery+MediaSaveCallback callback) (at <00000000000000000000000000000000>:0)
NativeGallery.SaveToGallery (System.Byte[] mediaBytes, System.String album, System.String filename, NativeGallery+MediaType mediaType, NativeGallery+MediaSaveCallback callback) (at <00000000000000000000000000000000>:0)

**Comment by yasirkula** [comment]
That's really strange. Is the issue reproducible on a new Unity project with default settings and only NativeGallery installed while using the example code?

**Comment by JackeAstray** [comment]
Thank you for your reply. I tested it in an independent project and there was no problem. It may be caused by other problems on my side.
