### ISSUE TITLE
Suggestion: move post process configurations to a scriptable object

### ISSUE THREAD

**Issue by gpiumatti** [yasirkula/UnityNativeGallery#203]
Right now, if I import the plugin via UMP, I cannot edit the code in NGPostProcessBuild.cs. Therefore, I am "stuck" using automated setup with the default values for PHOTO_LIBRARY_USAGE_DESCRIPTION, etc.

My suggestion is to move that configuration into a scriptable object (which will be created by the developer in his own Assets folder). You can then retrieve it during post processing with AssetDatabase.

This enables developers to install the plugin via UMP and configure it as desired.

**Comment by yasirkula** [comment]
Your suggestion is the proper way to do it. I'd like to address this issue in a future update but can't promise any ETA.

**Comment by yasirkula** [comment]
Addressed in https://github.com/yasirkula/UnityNativeGallery/commit/29566b888db32bc10edfe0fb6307a1049560d801
