### ISSUE TITLE
ios: Undefined symbols for architecture arm64

### ISSUE THREAD

**Issue by idamaeng** [yasirkula/UnityNativeGallery#207]
Unity: 2020.3.4f1
NativeGallery: 1.6.4
xCode: 12.5.1

Hi,
while trying to build for my iPhone, I am running into following exception:

ld: warning: arm64 function not 4-byte aligned: _unwind_tester from /Users/idamaeng/Documents/Repositories/jackpot-client/Builds/iOS/jackpot/Libraries/libiPhone-lib.a(unwind_test_arm64.o)
Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_PHPickerViewController", referenced from:
      objc-class-ref in NativeGallery.o
  "_OBJC_CLASS_$_PHPickerFilter", referenced from:
      objc-class-ref in NativeGallery.o
  "_OBJC_CLASS_$_PHPickerConfiguration", referenced from:
      objc-class-ref in NativeGallery.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Do you have any idea how to solve this issue?

Thanks in advance!

**Comment by yasirkula** [comment]
Does this help: https://github.com/yasirkula/UnityNativeGallery/issues/199

**Comment by idamaeng** [comment]
I dont know why, but reimporting did the trick?! 

Thank you for your fast reponse!
