### ISSUE TITLE
SETUP: after adding the 3 plugins (gallery, share and camera) i cannot finish the build

### ISSUE THREAD

**Issue by shacharoz** [yasirkula/UnityNativeGallery#209]
**Description of the bug**
i add the 3 plugins to my project and from then on the project cannot complete a build for android

**Reproduction steps**
- empty project for Android (built correctly). 
- add component called DlibFacedetector. (build correctly to android)
- add native gallery, share and camera to the project with the package manager (took the latest versions).
- project build shut down at the gradle part, saying "android resource linking failed."
- error messages does not seem so useful. if you want I can add them.
- do I need to change something in the player build settings (except the Write Permission in External)?

retested.
native camera - doesn't break the build.
native share - breaks it.

**Platform specs**
- Unity version: 2019.4
- Platform: Android
- Device: Samsung A20

**Comment by yasirkula** [comment]
You don't need to make any changes in Player Settings. I do need the error messages but I'm suspecting that this issue is about the `queries` entry of NativeShare: https://github.com/yasirkula/UnityNativeShare#faq

**Comment by shacharoz** [comment]
yes, i think you are right. 
i just read the docs here and found my issue. i will follow your article and report back.
https://github.com/yasirkula/UnityNativeShare#faq

**Comment by shacharoz** [comment]
ok! this article indeed fixes the issue. i had unity 2019.4 (and suffered about 1.5-3 weeks on this issue).
download just the binaries of the gradle 5.6.4 . its enough.
https://developers.google.com/ar/develop/unity/android-11-build

**Comment by shacharoz** [comment]
continuing one last step:
APK build works. but the aab doesn't.
any idea why? or should I venture into further research of the new gradle system?

thanks Yasir!

**Comment by yasirkula** [comment]
I can't comment without seeing all the error messages.

**Comment by shacharoz** [comment]
when building APK - all works.
when building AAB - errors i receive:
A. 
FileNotFoundException: Temp\gradleOut\launcher\build\outputs\bundle\release\launcher.aab does not exist
System.IO.File.Move (System.String sourceFileName, System.String destFileName) (at <eae584ce26bc40229c1b1aa476bfa589>:0)
UnityEditor.Android.PostProcessor.Tasks.BuildGradleProject.Execute (UnityEditor.Android.PostProcessor.PostProcessorContext context) (at <d76da2c9a45b4b02b93f56ae560b1d44>:0)
UnityEditor.Android.PostProcessor.PostProcessRunner.RunAllTasks (UnityEditor.Android.PostProcessor.PostProcessorContext context) (at <d76da2c9a45b4b02b93f56ae560b1d44>:0)
UnityEditor.Android.PostProcessAndroidPlayer.PostProcess (UnityEditor.BuildTarget target, System.String stagingAreaData, System.String stagingArea, System.String playerPackage, System.String installPath, System.String companyName, System.String productName, UnityEditor.BuildOptions options, UnityEditor.RuntimeClassRegistry usedClassRegistry, UnityEditor.Build.Reporting.BuildReport report) (at <d76da2c9a45b4b02b93f56ae560b1d44>:0)
UnityEditor.Android.AndroidBuildPostprocessor.PostProcess (UnityEditor.Modules.BuildPostProcessArgs args, UnityEditor.BuildProperties& outProperties) (at <d76da2c9a45b4b02b93f56ae560b1d44>:0)
UnityEditor.PostprocessBuildPlayer.Postprocess (UnityEditor.BuildTargetGroup targetGroup, UnityEditor.BuildTarget target, System.String installPath, System.String companyName, System.String productName, System.Int32 width, System.Int32 height, UnityEditor.BuildOptions options, UnityEditor.RuntimeClassRegistry usedClassRegistry, UnityEditor.Build.Reporting.BuildReport report) (at <5984c823338e4ca69b7a0ca01115425e>:0)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)

B.
UnityEditor.BuildPlayerWindow+BuildMethodException: 2 errors
  at UnityEditor.BuildPlayerWindow+DefaultBuildMethods.BuildPlayer (UnityEditor.BuildPlayerOptions options) [0x002bf] in <5984c823338e4ca69b7a0ca01115425e>:0 
  at UnityEditor.BuildPlayerWindow.CallBuildMethods (System.Boolean askForBuildLocation, UnityEditor.BuildOptions defaultBuildOptions) [0x00080] in <5984c823338e4ca69b7a0ca01115425e>:0 
UnityEngine.GUIUtility:ProcessEvent (int,intptr)

**Comment by yasirkula** [comment]
Removing which plugin resolves this AAB error?

**Comment by shacharoz** [comment]
Previously the issue was with Share.
But, I didnt try to rebuild the aab without it. Let me check

**Comment by shacharoz** [comment]
hi Yasir.
update: this solution solves the aab build issue. now both apk and aab are being built correctly.
https://answers.unity.com/questions/1781610/filenotfoundexception-tempgradleoutlauncherbuildou.html
