### ISSUE TITLE
Video not working on iOS

### ISSUE THREAD

**Issue by mubeenfahmed** [yasirkula/UnityNativeGallery#21]
I imported your asset from unity asset store, image gallery is working perfectly fine. But I am having issue displaying video. After I select the video from gallery, it starts compressing it and after compression the video is not getting displayed on the RawImage.

Kindly help I am getting following problem in my Xcode:

UnityEngine.DebugLogHandler:Internal_Log(LogType, String, Object)
UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
ImageGallery:<PickVideo>m__0(String)
MediaPickCallback:Invoke(String)
NativeGalleryNamespace.NGMediaReceiveCallbackiOS:OnMediaReceived(String)
 
(Filename: /Users/builduser/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

2018-04-11 13:10:33.353399+0500 ar[375:53933] [] <<<< AVOutputDeviceDiscoverySession (FigRouteDiscoverer) >>>> -[AVFigRouteDiscovererOutputDeviceDiscoverySessionImpl outputDeviceDiscoverySessionDidChangeDiscoveryMode:]: Setting device discovery mode to DiscoveryMode_None (client: ar)
2018-04-11 13:10:33.746004+0500 ar[375:53933] Warning: Attempt to present <AVPlayerViewController: 0x13c2d6e00> on <UIImagePickerController: 0x13c275000> whose view is not in the window hierarchy!
2018-04-11 13:10:33.750622+0500 ar[375:54387] [discovery] errors encountered while discovering extensions: Error Domain=PlugInKit Code=13 "query cancelled" UserInfo={NSLocalizedDescription=query cancelled}

**Comment by yasirkula** [comment]
I'm guessing that you are trying to play the video on a RawImage using a **VideoPlayer** component. In that case, try setting the url of the video player like this:

```
// This assumes that RawImage is already assigned to the VideoPlayer (either from the Inspector or by code)
videoPlayer.url = videoPath;
//videoPlayer.url = "file://" + videoPath; // try this if it doesn't work with just videoPath
videoPlayer.source = VideoSource.Url;
videoPlayer.Play();
```

Otherwise, if you are trying to play the video using the NativeGallery.LoadImageAtPath function, it won't work because it supports images only.

**P.S.** You can check if something is indeed wrong by first trying to play the video via `Handheld.PlayFullScreenMovie( "file://" + videoPath );`. If this works, then it should be an issue with VideoPlayer.

**Comment by mubeenfahmed** [comment]
Thanks for quick reply,
I tried handheld.PlayFullScreenMovie, but I want to do something similar to the way you displayed images on cube, I want to display videos on cube.

**Comment by yasirkula** [comment]
Try this one:

```csharp
NativeGallery.GetVideoFromGallery( ( path ) =>
{
	Debug.Log( "Video path: " + path );
	if( path != null )
	{
		// Play the video on a cube
		GameObject cube = GameObject.CreatePrimitive( PrimitiveType.Cube );
		cube.transform.position = Camera.main.transform.position + Camera.main.transform.forward * 5f;
		cube.transform.forward = -Camera.main.transform.forward;
		
		Material material = cube.GetComponent<Renderer>().material;
		if( !material.shader.isSupported ) // happens when Standard shader is not included in the build
			material.shader = Shader.Find( "Legacy Shaders/Diffuse" );

		AudioSource audioSouce = cube.AddComponent<AudioSource>();
		VideoPlayer videoPlayer = cube.AddComponent<VideoPlayer>();
		videoPlayer.renderMode = VideoRenderMode.MaterialOverride;
		videoPlayer.targetMaterialRenderer = cube.GetComponent<Renderer>();
		videoPlayer.targetMaterialProperty = "_MainTex";
		videoPlayer.audioOutputMode = VideoAudioOutputMode.AudioSource;
		videoPlayer.EnableAudioTrack( 0, true );
		videoPlayer.SetTargetAudioSource( 0, audioSouce );
		
		videoPlayer.url = path;
		videoPlayer.source = VideoSource.Url;
		videoPlayer.Play();
		audioSouce.Play();
	}
}, "Select a video" );
```

**Comment by mubeenfahmed** [comment]
Thanks its working now. Just want to ask, After selecting the video it shows me this window:

![img_0275](https://user-images.githubusercontent.com/13269229/38612707-fb58aa84-3da0-11e8-9ef8-4f4ee43ef022.png)

which I don't need. is it possible to remove the above window. So that as soon as I select the video it is displayed on the cube.

**Comment by yasirkula** [comment]
It seems like this is not possible, at least prior to iOS 11:

https://stackoverflow.com/a/5893066/2373034
https://stackoverflow.com/a/48643954/2373034

**Comment by mubeenfahmed** [comment]
https://stackoverflow.com/questions/20190485/how-to-avoid-compression-after-selecting-video-from-uiimagepickercontroller-in-i

**It says:**

With iOS 11 you can set the property videoExportPreset to AVAssetExportPresetPassthrough to get the original:

if #available(iOS 11.0, *) {
    picker.videoExportPreset = AVAssetExportPresetPassthrough
}
The "Video compression..." label just flashes for a few milliseconds and then the export is done.

@Diego Renau almost had the correct answer

**Comment by yasirkula** [comment]
To skip the video processing on iOS 11 and later, you can add the following code to [line 307 of NativeGallery.mm](https://github.com/yasirkula/UnityNativeGallery/blob/6ee1b601539b23684a487f7e1b92e18b719edbf4/Plugins/NativeGallery/iOS/NativeGallery.mm#L307):

```
if (@available(iOS 11.0, *)) {
	imagePicker.videoExportPreset = AVAssetExportPresetPassthrough;
}
```

But it won't work on earlier iOS versions (there will still be a video preview/processing step). I haven't tested it myself.

**Comment by mubeenfahmed** [comment]
I'll test it and let you know

**Comment by yasirkula** [comment]
It's nice talking with you, too. I'm closing this issue now but feel free to reopen it if you find something new.
