### ISSUE TITLE
Couldn't able to run the Android build

### ISSUE THREAD

**Issue by unbounded26** [yasirkula/UnityNativeGallery#215]
Just updated from the Asset store and couldn't able to run the Android build, it crashes at the start of the app. I get the following error which might help to debug
<img width="2452" alt="Screenshot 2021-08-13 at 6 22 47 PM" src="https://user-images.githubusercontent.com/7029364/129344097-98337dd3-40c4-41b1-8524-be33d1c08359.png">

Before updating it was working, but couldn't upload the build

**Comment by yasirkula** [comment]
Does Plugins/NativeCamera/NativeCamera.aar have a proguard.txt file in it? If so, what are its contents?

**Comment by unbounded26** [comment]
> Does Plugins/NativeCamera/NativeCamera.aar have a proguard.txt file in it? If so, what are its contents?

Plugins/NativeGallery/Android/NativeGallery.aar have the following content
<img width="248" alt="Screenshot 2021-08-14 at 10 19 07 PM" src="https://user-images.githubusercontent.com/7029364/129449305-b6bda075-3380-4e8e-a134-6568c7e6eb85.png">

**Comment by yasirkula** [comment]
It looks fine. Then I'd recommend you to check out the FAQ about Proguard in README file.

**Comment by unbounded26** [comment]
Thanks a lot for the help!

The issue was, I had NativeCamera in the project previously which later I removed, and somehow in Manifest, there was a line for the camera which was causing the issue
