### ISSUE TITLE
AndroidJavaException: java.lang.ClassNotFoundException: com.yasirkula.unity.NativeGalleryPermissionReceiver

### ISSUE THREAD

**Issue by nahunhee** [yasirkula/UnityNativeGallery#218]
Hello, I got this exception for android devices.

`AndroidJavaException: java.lang.ClassNotFoundException: com.yasirkula.unity.NativeGalleryPermissionReceiver
java.lang.ClassNotFoundException: com.yasirkula.unity.NativeGalleryPermissionReceiver
java.lang.Class.classForName(Native Method)
java.lang.Class.forName(Class.java:453)
com.unity3d.player.UnityPlayer.nativeRender(Native Method)
com.unity3d.player.UnityPlayer.access$300(Unknown Source:0)
com.unity3d.player.UnityPlayer$e$1.handleMessage(Unknown Source:95)
android.os.Handler.dispatchMessage(Handler.java:101)
android.os.Looper.loop(Looper.java:164)
com.unity3d.player.UnityPlayer$e.run(Unknown Source:20)
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.yasirkula.unity.NativeGalleryPermissionReceiver" on path: DexPathList[[zip file "/data/app/com.allthat3dmath.figures3dorigami-Z1h8oTJHRcRs5eVQEPVaZQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.allthat3dmath.figures3dorigami-Z1h8oTJHRcRs5eVQEPVaZQ==/lib/arm, /data/app/com.allthat3dmath.figures3dorigami-Z1h8oTJHRcRs5eVQEPVaZQ==/base.apk!/lib/armeabi-v7a, /system/lib, /system/vendor/lib]]
dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:93)
java.lang.ClassLoader.loadClass(ClassLoader.java:379)
java.lang.ClassLoader.loadClass(ClassLoader.java:312)
... 8 more
UnityEngine.AndroidJNISafe.CheckException () (at <e3de274dd3894b839f90ddc85455131f>:0)
UnityEngine.AndroidJNISafe.FindClass (System.String name) (at <e3de274dd3894b839f90ddc85455131f>:0)
UnityEngine.AndroidJavaClass._AndroidJavaClass (System.String className) (at <e3de274dd3894b839f90ddc85455131f>:0)
UnityEngine.AndroidJavaClass..ctor (System.String className) (at <e3de274dd3894b839f90ddc85455131f>:0)
UnityEngine.AndroidJavaProxy..ctor (System.String javaInterface) (at <e3de274dd3894b839f90ddc85455131f>:0)
NativeGalleryNamespace.NGPermissionCallbackAndroid..ctor (System.Object threadLock) (at <f7df72907000467bbed567063e7fde24>:0)
NativeGallery.RequestPermission (NativeGallery+PermissionType permissionType) (at <f7df72907000467bbed567063e7fde24>:0)
NativeGallery.SaveToGallery (System.Byte[] mediaBytes, System.String album, System.String filename, NativeGallery+MediaType mediaType, NativeGallery+MediaSaveCallback callback) (at <f7df72907000467bbed567063e7fde24>:0)
NativeGallery.SaveImageToGallery (UnityEngine.Texture2D image, System.String album, System.String filename, NativeGallery+MediaSaveCallback callback) (at <f7df72907000467bbed567063e7fde24>:0)
ScreenShot.save_openScreenShot (System.String path, UnityEngine.Sprite screenshotSprite) (at <0dae9ed946c241339f51cf41fc075485>:0)
ScreenShot.<Start>b__16_2 () (at <0dae9ed946c241339f51cf41fc075485>:0)
UnityEngine.Events.InvokableCall.Invoke () (at <923a18bb6641460ea72d7f0bd9c6022a>:0)
UnityEngine.Events.UnityEvent.Invoke () (at <923a18bb6641460ea72d7f0bd9c6022a>:0)
UnityEngine.UI.Button.Press () (at <3f085066ff464dea8eb6ad2a53479619>:0)
UnityEngine.UI.Button.OnPointerClick (UnityEngine.EventSystems.PointerEventData eventData) (at <3f085066ff464dea8eb6ad2a53479619>:0)
UnityEngine.EventSystems.ExecuteEvents.Execute (UnityEngine.EventSystems.IPointerClickHandler handler, UnityEngine.EventSystems.BaseEventData eventData) (at <3f085066ff464dea8eb6ad2a53479619>:0)
UnityEngine.EventSystems.ExecuteEvents.Execute[T] (UnityEngine.GameObject target, UnityEngine.EventSystems.BaseEventData eventData, UnityEngine.EventSystems.ExecuteEvents+EventFunction`1[T1] functor) (at <3f085066ff464dea8eb6ad2a53479619>:0)
UnityEngine.EventSystems.EventSystem:Update()`

I turned off Obfuscator, and added '-keep class com.yasirkula.unity.* { *; }' in the proguard-use.text.
Here is a screenshot of the location of progurard-use.text file.
<img width="576" alt="ScreenShot 2021-09-04 at 10 02 21 PM" src="https://user-images.githubusercontent.com/29575364/132112452-2c7b4378-e841-403b-a84b-159cd937796d.png">

Also here is my Player settings.
<img width="476" alt="ScreenShot 2021-09-04 at 10 02 45 PM" src="https://user-images.githubusercontent.com/29575364/132112462-67799143-b9db-487c-8943-3a77a67a3c9d.png">

<img width="519" alt="ScreenShot 2021-09-04 at 10 03 11 PM" src="https://user-images.githubusercontent.com/29575364/132112476-7063af2f-f310-4946-8d8b-471b32f9bf87.png">

<img width="740" alt="ScreenShot 2021-09-04 at 10 03 26 PM" src="https://user-images.githubusercontent.com/29575364/132112482-d899ffbf-a4db-4117-9f57-a36f0018842d.png">

The unity version is 2020.2.5f1.
I look forward to hearing back from your feedback.
Thank you!

**Comment by yasirkula** [comment]
`-keep class com.yasirkula.unity.* { *; }` should've been sufficient and it's actually [automatically added](https://github.com/yasirkula/UnityNativeGallery/blob/master/.github/AAR%20Source%20(Android)/proguard.txt) by NativeGallery.aar. I honestly don't know what would cause Proguard to misbehave like this.

**Comment by nahunhee** [comment]
Thank you for your comment. I found that the NativeGallery.jar file was not deleted. After I deleted that .jar file and remained .aar file, it works perfectly. Thank you!
