### ISSUE TITLE
Android: Multiple image selection opens file selection Ui instead of gallery on android

### ISSUE THREAD

**Issue by mkhizer77** [yasirkula/UnityNativeGallery#219]
Hello, 

We are trying to implement multiple image selection and on iOS it opens gallery and selection is easy for users to understand. But on android it opens this UI and it's very hard to understand for users where they can select images from. 

![Screenshot_2021-09-08-12-42-34-449_com google android documentsui](https://user-images.githubusercontent.com/90317065/132495792-67ef08fc-f05f-4821-85e5-f52c61c9c848.jpg)

But if we select a single image, user has choice to choose from fileManager, Gallery or Photos. Which is the right approach. 

![Screenshot_2021-09-08-12-46-05-906_com miui gallery](https://user-images.githubusercontent.com/90317065/132496129-c8a7ece0-fc89-455e-9fd9-fdc051e414b6.jpg)

Ideally multiple image selection should have same image picker as single image just like we have on iOS.

**Comment by yasirkula** [comment]
Picking a single image uses ACTION_PICK intent whereas picking multiple images uses ACTION_GET_CONTENT intent: https://github.com/yasirkula/UnityNativeGallery/blob/29566b888db32bc10edfe0fb6307a1049560d801/.github/AAR%20Source%20(Android)/java/com/yasirkula/unity/NativeGalleryMediaPickerFragment.java#L85-L101

ACTION_PICK doesn't allow picking multiple images and ACTION_GET_CONTENT is presented as file selection UI by the OS. AFAIK, it isn't possible to directly present the gallery UI with ACTION_GET_CONTENT.

**Comment by mkhizer77** [comment]
Thanks for your response, So from what I searched, Multiple image selection also works with ACTION_PICK. I am now struck trying to rebuild aar from the source code. Any tips on how I can rebuild on latest android studio would be really appreciated!

**Comment by yasirkula** [comment]
Where did you read that?

**Comment by mkhizer77** [comment]
I found a plugin that works as I expect, and Its using same intent! 

@TargetApi(18)
  public void browseMultipleImage(int paramInt) { this.multipleSelectCount = paramInt;
    Intent intent = new Intent("android.intent.action.PICK", MediaStore.Images.Media.EXTERNAL_CONTENT_URI);
    intent.setType("image/*");
    intent.putExtra("android.intent.extra.MIME_TYPES", new String[] { "image/*" });
    startActivityForResult(intent.putExtra("android.intent.extra.ALLOW_MULTIPLE", true).createChooser(intent, "Select Photos"), RESULT_SELECT_MULTI_IMAGE); }

**Comment by mkhizer77** [comment]
I need to verify this with your plugin, so if you can help with some pointer on how I can make the change and rebuild? I'll share if it works for me! Thanks alot

**Comment by yasirkula** [comment]
It won't work on all devices. IDK the % of devices that this works on but if you follow this path, you must be ready to encounter issues on unknown amount of devices.

- https://stackoverflow.com/questions/67367649/intent-extra-allow-multiple-not-working-with-intent-action-pick-when-i-test-on-o
- https://stackoverflow.com/questions/51780105/picking-multiple-images-on-clicking-from-gallery

You can google "unity android studio native plugin" to learn about creating a plugin with Android Studio. In summary:

- Create a new project
- Copy/add native [Java classes](https://github.com/yasirkula/UnityNativeGallery/tree/master/.github/AAR%20Source%20(Android)/java/com/yasirkula/unity) to the project
- Change `apply plugin: 'com.android.application'` to `apply plugin: 'com.android.library'`
- Delete the `applicationId`
- Build the project
- Copy **classes.jar** from the built aar to _NativeGallery.aar_

**Comment by mkhizer77** [comment]
Thanks a lot! This is supposed to be a hot fix! until we decide to implement our own customGallery!
