### ISSUE TITLE
iOS: rotation not detected

### ISSUE THREAD

**Issue by bakwc** [yasirkula/UnityNativeGallery#222]
**Description of the bug**

Rotation always zero on iOS platform (on android rotation detected correctly). Video loaded with wrong orientation.

**Reproduction steps**

```
        var properties = NativeGallery.GetVideoProperties(fileName);
        print("rotation: " + properties.rotation);
```

**Platform specs**

Please provide the following info if this is a Unity 3D repository.

- Unity version: *2020.1.7f1*
- Platform: *iOS*
- Device: *iphone12, iphone5s*
- How did you download the plugin: *e.g. Asset Store, version 1.6.4*

**Additional info**

- no additional info

**Comment by yasirkula** [comment]
Does the video play in correct orientation in Photos app? Can you copy the video from the Android device to iOS device and give it a try (if you were trying different videos)? Can you also record different videos in different orientations using your device's camera and see if they return correct orientation value? Can you see any possibly related lines in Xcode console?

**Comment by bakwc** [comment]
Currently debugging, It looks like some properties string parsing error (correct rotation in properties string, but wrong after parsing). I will let you know when find out.

**Comment by yasirkula** [comment]
You can paste the raw string here so that I can help you see what may be wrong.
