### ISSUE TITLE
Denying permission on ios returns Granted

### ISSUE THREAD

**Issue by charles-mersereau-dev** [yasirkula/UnityNativeGallery#224]
**Description of the bug**

I have a class that is in charge of taking screenshots for my game. In the method that takes the screenshot, I am checking the read permission using the Native Gallery permission check method. I immediately print the result and then check the result to determine if I can take and save the screenshot or not. 

I noticed today in the logs that before the user accepts or rejects the permission, the log has already been printed and it says the permission has been granted. This is obviously incorrect. I then deny the permission and try to take another screenshot. The log once again prints that the permission has been Granted, although it hasn't been. This causes my app to appear that it takes a screenshot, but nothing is saved in the photos.

**Reproduction steps**

Have a script that checks the read permission and prints it to the logs. Run that script and perform whatever actions will call the code.

**Platform specs**

Please provide the following info if this is a Unity 3D repository.

- Unity version: 2020.3.9f1
- Platform: iOS
- Device: iPhone X
- How did you download the plugin: Github

**Additional info**

Code to check permission and print log. ( this.Prefix() is an extension in our code )

![Screen Shot 2021-09-22 at 2 57 05 PM](https://user-images.githubusercontent.com/91216973/134405038-201d9720-c71d-47c0-a32f-91d9d1eab08a.png)

**Comment by yasirkula** [comment]
Quoting the [documentation](https://github.com/yasirkula/UnityNativeGallery#c-runtime-permissions):

> Note that NativeGallery doesn't require any permissions for picking images/videos from Photos on iOS 11+ and saving images/videos to Gallery on Android 29+, so no permission dialog will be shown in these cases and the permission functions will return Permission.Granted.

How could you even deny the Read permission? NativeGallery should never ask Read permission on your device.

**Comment by charles-mersereau-dev** [comment]
Thanks for quoting the documentation. I have to admit, I'm actually the follow up guy for this bit of code in my project so I was not aware of how that worked.

I do know that we initially were using the read permission because we were trying to store a screenshot and implement a share feature in one swoop. We realized the technical implementation we had wouldn't work because the NativeGallery save method on iOS doesn't return the file path to the image that was stored. I'm seeing now based our code changes that we should be switching our Read permission check to the Write permission check instead. 

I think there was some confusion because the NativeGallery methods implicitly ask for the permission if it has not been asked, so it appeared that the permission being asked for was the Read permission. It makes more sense now that the prompt we were seeing was actually for the write permission.
