### ISSUE TITLE
Android cannot build use 2019.4.20f1

### ISSUE THREAD

**Issue by w963963555577** [yasirkula/UnityNativeGallery#229]
A minimal project:
https://drive.google.com/file/d/1xZkM0U08nfzyodhI8ANgw_zrUb_bvnul/view?usp=sharing

Please help me.

Some screenshot:
![image](https://user-images.githubusercontent.com/17163906/139831496-66c2126b-cd08-409d-84fc-4d6b46416852.png)

![image](https://user-images.githubusercontent.com/17163906/139831634-9d05c9bc-dc83-4b75-b7e5-a1530f42ba58.png)
![image](https://user-images.githubusercontent.com/17163906/139831655-9f4040b4-58c4-4eb5-a806-c07fb2b7c96e.png)
![image](https://user-images.githubusercontent.com/17163906/139831676-df011d2c-152c-4107-8bd5-5ee896d8a06b.png)

**Comment by yasirkula** [comment]
Please see the FAQ entry related to `android:requestLegacyExternalStorage`: https://github.com/yasirkula/UnityNativeGallery#faq

As a side note, Google Play requires Target SDK to be set to at least API Level 30: https://developer.android.com/distribute/best-practices/develop/target-sdk

**Comment by w963963555577** [comment]
Can you give me an example AndroidManifest.xml file?

**Comment by yasirkula** [comment]
You'll simply remove this line from NativeGallery.aar: https://github.com/yasirkula/UnityNativeGallery/blob/2cd01a22451ea2185a55a044c0e5e2bea96ca147/.github/AAR%20Source%20(Android)/AndroidManifest.xml#L5

Yet again, you won't be able to upload your game to Google Play because you aren't using API Level 30. If you were using it, this error wouldn't show up at all.

**Comment by w963963555577** [comment]
This manifest cause NullReference error 
![image](https://user-images.githubusercontent.com/17163906/139901107-18a6e792-22bf-4baf-bb6d-c368cdec997f.png)

**Comment by yasirkula** [comment]
NativeGallery doesn't have anything to do with Assets/Plugins/Android/AndroidManifest. It has ITS OWN AndroidManifest inside NativeGallery.aar. You can open it with WinRAR or 7-zip.

**Comment by w963963555577** [comment]
OK, It works, thank you for your help.
