### ISSUE TITLE
Generalize your plugin

### ISSUE THREAD

**Issue by unbounded26** [yasirkula/UnityNativeGallery#23]
Can you generalize your functions? Like if I pass 
- image it shows images from picker and returns its path
- video it shows images from picker and returns its path
- pdf it shows images from picker and returns its path
- document it shows images from picker and returns its path

Means depending on the mime type
https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types/Complete_list_of_MIME_types

**Comment by yasirkula** [comment]
Some people may not be familiar with MIME types; I believe separating image and video related functions make things more clear. In addition, I'd rather not do a string comparison to figure out whether user wants to pick an image or video. Things are pretty clear and, hopefully, easy to use as is ^^

I've designed this plugin primarily to interact with Gallery/Photos, adding PDF/document support would probably bloat it.

**Comment by unbounded26** [comment]
Hmmmm, Yes, you are right.

Then can you do something like that as your new plugin then? Actually, there are a lot of options available on asset store, but I like your method because you do it natively without interacting with manifest and not bulking the plugin with a lot of stuff, so what are your thoughts on it

**Comment by yasirkula** [comment]
That'd be better. I don't have plans to create a PDF/document picker yet, mainly because [it is not natively supported on iOS](https://stackoverflow.com/questions/40216133/how-to-choose-any-document-file-from-device-in-objective-c-in-ios). But maybe things will change over time. Thanks for the suggestion.
