### ISSUE TITLE
关于新功能，选取相册中的图片并进行裁剪。

### ISSUE THREAD

**Issue by Timor666** [yasirkula/UnityNativeGallery#238]
请原谅我是个菜鸟，我并不擅长开发安卓。
有没有考虑这个功能，选择相册中的图片并进行裁剪。
固定分辨率或者，固定比例之类。像原生安卓裁剪图片那样。
比如这张效果图片

![image](https://user-images.githubusercontent.com/35324214/145965821-716d757d-647e-48d3-9979-885830290efb.png)

非常期待您可以完善这个功能

**Comment by yasirkula** [comment]
Absolutely: https://github.com/yasirkula/UnityImageCropper

**Comment by Timor666** [comment]
抱歉，我的google浏览器没有搜索到，现在我去尝试一下，非常感谢。所以我点击Star 哈哈
