### ISSUE TITLE
Is this work on Oculus quest ? 

### ISSUE THREAD

**Issue by ti-hardikshah** [yasirkula/UnityNativeGallery#239]
Hi, 
I just want to know is this plugin work for Oculus quest ? I am trying to create functionality for Oculus VR but getting issue with permission

**Comment by yasirkula** [comment]
I haven't tried it myself. What is happening?

**Comment by ti-hardikshah** [comment]
only dark black screenshot save. but I have resolved that issue. 

May be "Texture2D ss = new Texture2D( Screen.width, Screen.height, TextureFormat.RGB24, false );"
not working in place i am using additional camera with render texture and passing that texture for SS

` private IEnumerator TakeScreenshotAndSave()
    {
        yield return new WaitForEndOfFrame();

        RenderTexture saveTexture = renderTexture;

        yield return new WaitForEndOfFrame();

        mainCamera.SetActive(false);

        if (saveTexture != null)
        {

            RenderTexture.active = saveTexture;
            Texture2D screenShot = new Texture2D((int)(saveTexture.width), (int)(saveTexture.height), TextureFormat.RGB24, false);
            screenShot.ReadPixels(new Rect(0, 0, saveTexture.width, saveTexture.height), 0, 0);
            screenShot.Apply();

            NativeGallery.Permission permission = NativeGallery.SaveImageToGallery(screenShot, "RealEstate", "Pics.png", (success, path) => Debug.Log("Media save result: " + success + " " + path));
            Debug.Log("Permission result: " + permission);
            Destroy(screenShot);
        }
    }`

**Comment by yasirkula** [comment]
Seems like standard screenshot function doesn't work in VR then, good to hear that the issue is resolved, nicely done!

**Comment by ti-hardikshah** [comment]
@yasirkula  Is there any solution for color correction for Linear color space?  Because it looks too dark.

**Comment by yasirkula** [comment]
NativeGallery shouldn't be modifying the textures in any way. Can you assign the texture to a RawImage and compare it with the saved image?

**Comment by ti-hardikshah** [comment]
Anyway, I have resolved this issue too... 

RawImage looks good but when we save It looks dark due to the Linear/gamma color space issue. But luckily I get a solution for this issue.

`public Texture2D toTexture2D(RenderTexture rTex) {

  var tex = new Texture2D(rTex.width, rTex.height, TextureFormat.RGBA32, false, true);
  var old_rt = RenderTexture.active;
  RenderTexture.active = rTex;

  tex.ReadPixels(new Rect(0, 0, rTex.width, rTex.height), 0, 0, false);

  Color[] pixels = tex.GetPixels();
  for (int p = 0; p < pixels.Length; p++) {
    pixels[p] = pixels[p].gamma;
  }

  tex.SetPixels(pixels);

  tex.Apply(false);

  RenderTexture.active = old_rt;
  return tex;
}`
