### ISSUE TITLE
Issue Take pictures

### ISSUE THREAD

**Issue by cacdzya** [yasirkula/UnityNativeGallery#24]
Friend this is an excellent plugin thank you, I have a question, in this plugin, can I take pictures with the camera an put the picture in my texture, and if not, it will be great that you implement this too in the plugin. Thank you for all

**Comment by yasirkula** [comment]
Accessing the camera will require new permissions and is not really related to (native) gallery. Thus, I will not be adding camera functionality to this plugin.

This was the bad news. The good news is that, I might actually create a separate plugin that allows you to capture images (maybe videos as well?) with camera on Android & iOS. Let's see what will happen...

**Comment by yasirkula** [comment]
Check this out: https://github.com/yasirkula/UnityNativeCamera
