### ISSUE TITLE
Is it possible return list in place of Video picker ? 

### ISSUE THREAD

**Issue by ti-hardikshah** [yasirkula/UnityNativeGallery#247]
I want to use this functionality in Oculus VR. 
Need to access Screen Record native folder and list out all videos or last video path and upload on the server using c#. 
Is that possible using this plugin ? or any other solution or suggestion?

**Comment by yasirkula** [comment]
This plugin doesn't support getting a list of videos from Gallery, it returns only the paths of the videos that are explicitly picked by the user. I have seen custom gallery implementations on Asset Store in the past but haven't tried them myself.

**Comment by ti-hardikshah** [comment]
@yasirkula  Thanks for the update. 
Anyway, I have found a solution. 

`public static string GetAndroidInternalFilesDir() {
  string[] potentialDirectories = new string[] {
    "/mnt/sdcard",
    "/sdcard",
    "/storage/sdcard0",
    "/storage/sdcard1"
  };

  if (Application.platform == RuntimePlatform.Android) {
    for (int i = 0; i < potentialDirectories.Length; i++) {
      if (Directory.Exists(potentialDirectories[i])) {
        return potentialDirectories[i];
      }
    }
  }
  return "";
}`

` public void GetAllFiles() {

        DirectoryInfo info = new DirectoryInfo("/mnt/sdcard/Oculus/VideoShots/");
        FileInfo[] files = info.GetFiles().OrderBy(p => p.CreationTime).ToArray();

         foreach (FileInfo file in files)
         {
             Debug.Log("File Found :- "+file.FullName);
         }

    }`
