### ISSUE TITLE
video play option is available in selection tab itself

### ISSUE THREAD

**Issue by ManojBalaji3001** [yasirkula/UnityNativeGallery#25]
Dear Developer,
      Thanks for the wonderful script, it's helps a lot. In video selection process i tried to select the video from gallery the selected video ll play on gamescreen using unity video player. but in selection page itself there is an option to play the video. why the user want to play the video in 2 location? can you please tell me how to skip the video play option in selection screen. Thanks in advance

Regards
M Manoj Balaji

**Comment by yasirkula** [comment]
That is an internal feature of the native dialog on iOS. Unfortunately, it doesn't seem possible to skip it (but only speed up the compression process on iOS 11 and later). Please see this conversation: https://github.com/yasirkula/UnityNativeGallery/issues/21#issuecomment-380412215

**Comment by ManojBalaji3001** [comment]
Thanks for your reply, The media players like KM player, VLC, etc., they are directly search the videos in the mobile and showing like a playlist can you please tell me how to do like that?

**Comment by yasirkula** [comment]
You'll have to use a separate video picker solution that doesn't rely on native UI. You can search for "ios media picker github" and browse the results. This one seems promising at first glance: https://github.com/hackiftekhar/IQMediaPickerController
