### ISSUE TITLE
SaveImageToGallery returns multiple MediaSaveCallback 

### ISSUE THREAD

**Issue by yashs-devstree** [yasirkula/UnityNativeGallery#251]
**Description of the bug**

When using SaveImageToGallery function I'm getting MediaSaveCallback multiple times.

Let's say I've 5 images that a user can download so when I'm clicking on all five download buttons without waiting for 1 download to complete below-mentioned thing happens.

Save Image 1 - 1 Callback
Save Image 2 - 2 Callback
Save Image 3 - 3 Callback
Save Image 4 - 4 Callback
Save Image 5 - 5 Callback

Also, is there a way I can show images downloaded in the status/notification bar with a notification linked to a path like when we download/save anything from native apps?

**Platform specs**
- Unity version: *2021.3.0f1*
- Platform: *Android, iOS*
- How did you download the plugin: *Asset Store*

**Comment by yasirkula** [comment]
MediaSaveCallback will be invoked once per SaveImageToGallery call. Since it's called 5 times, MediaSaveCallback will be invoked 5 times in total. Is it invoked 15 times for you?

NativeGallery just saves a local image file to gallery, it doesn't download images. Since image download process is executed by another code, that code needs to handle the notification part.

**Comment by yashs-devstree** [comment]
No, it is not invoking 15 times. On 1st image download it invokes 1 time, on 2nd image download it invokes 2 times and so on. I'm attaching my download and save code below for your reference.

`private void OnClickDownloadButton()
    {
        filePath = Constants.LocalDatabaseDirectory + postID + ".jpeg";

        if (File.Exists(filePath))
        {
            NativeGallery.Permission permission = NativeGallery.SaveImageToGallery(filePath, "SmartPhotos", postID + ".jpeg", OnDownloadComplete);
            Debug.Log("Permission result: " + permission);
        }
        else
        {
            DownloadAndSavePhoto();
        }
    }

    private void DownloadAndSavePhoto()
    {
        var request = new BestHTTP.HTTPRequest(new Uri(printURL), callback: (request, response) =>
        {
            if (request.State == BestHTTP.HTTPRequestStates.Finished)
            {
                if (!response.IsSuccess)
                {
                    Debug.LogError(response.StatusCode + ": " + response.DataAsText);
                    OnDownloadComplete(false, filePath);
                    return;
                }
                Debug.Log("Photo Downloaded successfully!");
                File.WriteAllBytes(filePath, response.Data);
                OnClickDownloadButton();
            }
        });

        request.Send();
    }

    private void OnDownloadComplete(bool success, string path)
    {
        SendDownloadStatus(success);
        if (success)
        {
            Debug.Log("Kudos! Your Smart Photo downloaded successfully");
        }
        else
        {
            Debug.Log("Oh snap! Failed to download your Smart Photo");
        }
    }`

**Comment by yasirkula** [comment]
After 2 downloads, if the callback is invoked 2 times in total (not 3 times), then it's normal. As I said, one callback per SaveImageToGallery call.

**Comment by yashs-devstree** [comment]
I think there is some misunderstanding in my explanation. On the 2nd download, I'm getting callback 2 times not the 2nd time, On the 3rd download, I'm getting callback 3 times not the 3rd time, and on the 4th, I'm getting callback 4 times not the 4th time. All those times it should be called only once because it is already called for other downloads. Shouldn't the callback be deregistered after getting called so that it won't get called afterwards?

**Comment by yasirkula** [comment]
> Platform: Android, iOS

To verify, this is happening on both platforms?

**Comment by yashs-devstree** [comment]
Currently, only android because I have not tested iOS yet. I'll check and update here if I find the same for iOS as well.

**Comment by yasirkula** [comment]
On Android, SaveImageToGallery fires the callback immediately and doesn't store it in any location so it isn't possible for it to call the callback multiple times: https://github.com/yasirkula/UnityNativeGallery/blob/9ea5f5d53c53deea4ef057f2564b46342ecf2925/Plugins/NativeGallery/NativeGallery.cs#L485-L493

I'm suspecting that your OnClickDownloadButton function is invoked multiple times for unknown reasons.

**Comment by yashs-devstree** [comment]
Hmm okay, let me investigate further then. If I find anything I will update you.

**Comment by yasirkula** [comment]
I'd recommend putting a Debug.Log inside OnClickDownloadButton. My assumption is that you can reproduce this issue in the editor, as well. If not, you can check out logcat to see these logs and if Development Build is enabled, see the full stacktrace in logcat.
