### ISSUE TITLE
Rotation of loaded image is unpredictable

### ISSUE THREAD

**Issue by duong730** [yasirkula/UnityNativeGallery#254]
I loaded image from gallery and use this image as main texture of a material. But the rotation of the image change unpredictable. Example: when i load a portrait, it will become landscape, image rotate 90 deg. After some test, i think if image has large size, this issue can happen, but not sure and can not solve it.
i am using unity 2021.3.4f1 and test on my PC.

_```
public void PickImage(int maxSize)
    {
        NativeGallery.Permission permission = NativeGallery.GetImageFromGallery((path) =>
        {
            Debug.Log("Image path: " + path);
            if (path != null)
            {
                // Create Texture from selected image
                Texture2D texture = NativeGallery.LoadImageAtPath(path, maxSize);
                if (texture == null)
                {
                    Debug.Log("Couldn't load texture from " + path);
                    return;
                }
                else
                {
                    material.mainTexture = texture;
                    ES3.SaveImage(duplicateTexture(texture), "screenshot.png");
                    menuPanel.SetActive(false);
                }
            }
        });
        Debug.Log("Permission result: " + permission);
    }
```_

**Comment by yasirkula** [comment]
LoadImageAtPath uses the image's EXIF metadata to read its target rotation but only on mobile platforms. It doesn't apply rotation correction in the Editor since it's impossible without using 3rd party plugins.

**Comment by duong730** [comment]
Thank you, yasirkula. Your advice help me a lot.

**Comment by yasirkula** [comment]
Glad to hear it!
