### ISSUE TITLE
Error CS0246 The type or namespace name 'NativeGallery' could not be found (perhaps missing a using directive or an assembly reference).

### ISSUE THREAD

**Issue by Ilya171** [yasirkula/UnityNativeGallery#255]
Bro, hi!
I downloaded your plugin from the asset store
, but I can't call any of your scripts through mine

I tried to write like
"using NativeGallery " or just create an object of class NativeGallery a = new()
But my script does not see your library or your classes

**Comment by Ilya171** [comment]
Bro, all ok, i reload Unity

**Comment by yasirkula** [comment]
Happy to hear that! Let me know if anything changes!
