### ISSUE TITLE
Crash while fetching image from gallery in iOs

### ISSUE THREAD

**Issue by dipen-apptrait** [yasirkula/UnityNativeGallery#26]
I am using this plugin for android and it works like a charm. Thanks for this plugin. But now when i am trying yo use for ios it allows me to select image but after that it is crashing everytime. I have tried different device and latest os. Also i am seeing the photo gallery which means there is no issue related to peemission. I am not sure what's the exact issue. Can you please look into this?

**Comment by yasirkula** [comment]
Of course. Did you test it on an iPad or on iPhone(s) only? And can I also ask your Unity version?

**Comment by dipen-apptrait** [comment]
Yes i tried iOS 10.X and using latest unity version on mac.

**Comment by yasirkula** [comment]
I couldn't reproduce this issue so far. Can you attach the [crash log ](https://developer.apple.com/library/content/qa/qa1747/_index.html)(taken from Xcode) and the console output for reference?

**Comment by yasirkula** [comment]
Were you able to resolve the issue on your own?
