### ISSUE TITLE
Unity android build UnauthorizedAccessException: Access to the file path is denied.

### ISSUE THREAD

**Issue by mustafagamedev** [yasirkula/UnityNativeGallery#261]
**Description of the bug**
I have been using the native gallery plugin to access the media gallery of my users and then they choose to upload them using another plugin. However, on android devices i keep getting an error.
Unity android build UnauthorizedAccessException: Access to the file path is denied.
altho i have granted permission and the permission is logged as granted and the image path is logged as well.
also, i can locally use the image to display it while it is uploading however the path access is denied i tried it before and it is my first time facing this.

**Platform specs**

Please provide the following info if this is a Unity 3D repository.

- Unity version: *e.g. 2021.3.10f1*
- Platform: * Android*
- Device: *realmi *
- How did you download the plugin: *Package manager*

**Additional info**

Error : 
"Unity android build UnauthorizedAccessException: Access to the file path is denied."

**Comment by yasirkula** [comment]
Hi, may I ask the Android version, the full stacktrace and the logged filepath?

**Comment by mustafagamedev** [comment]
hello,
i attached a full log for the apk run and the error log alone 
Android Version : 10
Phone model : realme c11 
[Full log.txt](https://github.com/yasirkula/UnityNativeGallery/files/9799406/Full.log.txt)
[error staacktrace.txt](https://github.com/yasirkula/UnityNativeGallery/files/9799409/error.staacktrace.txt)

**Comment by yasirkula** [comment]
Inside BrainCloudFile.UploadFile's FileStream constructor, please specify FileAccess.Read parameter explicitly (and not FileAccess.Write or FileAccess.ReadWrite).

**Comment by mustafagamedev** [comment]
It is working perfectly thank you !
