### ISSUE TITLE
ClassNotFoundException: com.yasirkula.unity.NativeGalleryPermissionReceiver

### ISSUE THREAD

**Issue by CatAzreal** [yasirkula/UnityNativeGallery#263]
I'm aware that many people have had similar issues before, but after a bit of messing around, I still have no clue how to fix this so here I am.

**What I Tried**

-Changing directories of NativeGallery(this might be the issue because I did that before changing proguard files but I have no way to verify if it's the root cause).
-Adding "-keep class com.yasirkula.unity.* { *; }" to the custom proguard file existed in our project, as instructed in NativeGallery's FAQ.
-Adding "\<assembly fullname="NativeGalleryNamespace" preserve="all"/>" to Asset/link.xml following someone else's blog on fixing this specific NativeGallery plugin issue.
-Deleting the plugin, reimport from Package Manager.

**Platform specs**

- Unity version: *2020.3.20f1c1*
- Platform: *Android*
- Device: *Samsung Galaxy A32 5G, Android 12*
- Downloaded from: *Asset Store*(so should be the latest plugin)

**Attached Screenshot**

Custom proguard file path:
![NGproguard](https://user-images.githubusercontent.com/45586623/196633189-bbe55aed-34f0-47da-9d83-2d562d2a129d.png)
Proguard file content:
![NGproguardContent](https://user-images.githubusercontent.com/45586623/196633367-d0df0654-47d3-4586-a094-cb9d8e422123.png)
Current Native Gallery path:
![NGpath](https://user-images.githubusercontent.com/45586623/196633882-189050bb-e3a0-4d59-a20c-5fd98ba0cc8b.png)

**Error Log**

2022-10-19 15:31:31.340 31538-31616/com.\*\*\*.\*\*\* E/Unity: AndroidJavaException: java.lang.ClassNotFoundException: com.yasirkula.unity.NativeGalleryPermissionReceiver
    java.lang.ClassNotFoundException: com.yasirkula.unity.NativeGalleryPermissionReceiver
        at java.lang.Class.classForName(Native Method)
        at java.lang.Class.forName(Class.java:454)
        at com.unity3d.player.UnityPlayer.nativeRender(Native Method)
        at com.unity3d.player.UnityPlayer.access$600(Unknown Source:0)
        at com.unity3d.player.UnityPlayer$g$1.handleMessage(Unknown Source:150)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loopOnce(Looper.java:226)
        at android.os.Looper.loop(Looper.java:313)
        at com.unity3d.player.UnityPlayer$g.run(Unknown Source:20)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.yasirkula.unity.NativeGalleryPermissionReceiver" on path: DexPathList[[zip file "/data/app/~~OyUnY6B0HB55u0kICbrRBA==/com.\*\*\*.\*\*\*-VC6EIxgjp2VXW-fznEeqeQ==/base.apk"],nativeLibraryDirectories=[/data/app/~~OyUnY6B0HB55u0kICbrRBA==/com.\*\*\*.\*\*\*-V

**Comment by yasirkula** [comment]
Your screenshots look good to me. If there isn't another NativeGallery in your project that was installed by perhaps another plugin, then please unzip Plugins/NativeGallery/Android/NativeGallery.aar and verify that the missing class exists in there. If it exists, then something I'm unaware of is preventing Unity's Android build from working correctly but I unfortunately don't know what might do that.

**Comment by CatAzreal** [comment]
> please unzip Plugins/NativeGallery/Android/NativeGallery.aar and verify that the missing class exists in there (inside classes.jar). If it exists, then something I'm unaware of is preventing Unity's Android build from working correctly but I unfortunately don't know what might do that.

Sadly I see the receiver among unpacked files:
![NGunpack](https://user-images.githubusercontent.com/45586623/196665038-36471114-6e85-4204-ba61-13722a6b6370.png)

Guess I'm going to further check if anything else is preventing NativeGallery from working, thanks for the response!

**Comment by CatAzreal** [comment]
After some fiddling and consulting my colleagues, it's possible that I forgot to commit certain file(s) to our version control, resulting build.gradle not implementing NativeGallery because everything went swimmingly after my colleague got NativeGallery installed on their device.

I don't have enough time to look into what and where I got wrong so sorry if anyone else's encountering the same issue and looking for answer here.

I'm closing the thread, have a good day!

**Comment by yasirkula** [comment]
Thank you for sharing your findings and glad the issue is resolved on your end 🥳
