### ISSUE TITLE
NativeGallery functions return Permission.Denied even though I've set "Write Permission" to "External (SDCard)"

### ISSUE THREAD

**Issue by KuldipDevstree** [yasirkula/UnityNativeGallery#264]
**Description of the bug**

NativeGallery functions return Permission.Denied even though I've set "Write Permission" to "External (SDCard)"

**Reproduction steps**

i am trying to access the picture from gallery on android 13 on google pixel 6 device, its not popping any permission dialog box

**Platform specs**

Please provide the following info if this is a Unity 3D repository.

- Unity version: 2021.3.11f1
- Platform: Android
- Device: google pixel 6
- How did you download the plugin: Asset Store

**Additional info**

i have updated to letest package and tryed the fix in FAQ but it did not work

**Comment by yasirkula** [comment]
Asset Store is buggy on some Unity versions. I wouldn't expect it to be buggy on 2021 LTS but just in case, could you download the plugin from GitHub?

**Comment by KuldipDevstree** [comment]
Ok i will try from git and let you know if it fixes it or not

**Comment by Armanlone** [comment]
Hi, also added this plugin hours ago. If it can help, just add it through the Package Manager.
Here's how I did it

![image](https://user-images.githubusercontent.com/48377791/197148761-44bb6b02-6f18-4d7d-beac-670838bed7b7.png)

**Comment by KuldipDevstree** [comment]
Hi, i have added it through package manager but still same issue , i have attach the screenshot of app info it shows no permission asked
![WhatsApp Image 2022-10-21 at 3 13 59 PM](https://user-images.githubusercontent.com/85537492/197167425-391b8fdd-3eb7-49be-9e53-1a7aabe89058.jpeg)

**Comment by yasirkula** [comment]
I wonder if permission is forcefully removed by some plugin. Can you try these 2 things: 1) uninstall the app and reinstall it from scratch, 2) test the plugin on a new Unity project

**Comment by KuldipDevstree** [comment]
Hi , i have fixed this issue in my app by setting target api to 32 insted 33, this issue only occure if i build app with target api 33. Thanks for your help and pluing.

**Comment by yasirkula** [comment]
I've recently learnt that READ_EXTERNAL_STORAGE permission can no longer be asked on API Level 33. I'm working on a fix for this.

**Comment by philipgen** [comment]
Hi @yasirkula , do you have an expected timetable for this fix?
We are running issues with targeting API 33.

**Comment by yasirkula** [comment]
You're completely right, I'm sorry for my delay. This task was due weeks ago. I haven't been able to work on any of my plugins, not just NativeGallery. Among all the pending issues, this one is my top priority. I'll do my best to push an update this week.

**Comment by yasirkula** [comment]
Resolved in https://github.com/yasirkula/UnityNativeGallery/commit/46eb0decacc86a20672f9954e225e239165560cd
