### ISSUE TITLE
Saving, Screenshots, and Image paths question, milord.

### ISSUE THREAD

**Issue by Armanlone** [yasirkula/UnityNativeGallery#265]
Since the author is here, might as well ask ;)
Hi, I've been banging my head for 3 hours 😄 as to why this saving of screenshot isn't working but then after sometime, I finally saw those in my gallery.

Question is, is there a time lag for this? Or my phone is just slow?

Also, are there any "public const string ANDROID_PATH" I can get to know where are those pictures I've just saved?

Lastly, huge thanks for your plugins.

**Comment by yasirkula** [comment]
Hi!

There isn't supposed to be a lag but could you replace NativeGallery.aar with the one inside [this zip archive](https://github.com/yasirkula/UnityNativeGallery/files/9844034/NativeGallery.zip) and try again?

Images are saved to `DCIM/{Album name}`. You can get DCIM's path using [this method](https://stackoverflow.com/a/60478347/2373034) and append the album folder to it via Path.Combine.

**Comment by Armanlone** [comment]
Hi, thank you so much for replying.

Sorry for this late reply, didn't have time.

Thanks for the zip file, I haven't checked it yet, but I think your plugin seems working fine after all. And also checked the link you've added, thanks for that as well.

And can't seem to delete this as a bug. I wanted to mark it as Solved before but don't know how. Or delete this issue.

Anyway thank you for your plugins, they are very helpful.
