### ISSUE TITLE
Saving of texture as png to Android Phone's gallery.

### ISSUE THREAD

**Issue by emmanuel-dev000** [yasirkula/UnityNativeGallery#269]
Hi, as always, thanks for your Unity plugins, they are very helpful.

Situation:
I'm trying to save a Texture2D using the NativeGallery plugin. And it works fine in saving the screenshots as png in Android (the example you gave). But when I try to upload an image (same plugin too), and save it using the NativeGallery.SaveImageToGallery() there's no png saved inside the gallery nor the phone (folders of data, obb, media, and DCIM).

Problem (shorter ver.):
- How to save an uploaded texture by using the NativeGallery.SaveImageToGallery() to the Android phone? I just copied your example and the screenshot works just fine though.

Current Code:

![image](https://user-images.githubusercontent.com/110382530/204494257-f26a8f14-5876-4a26-a0a5-1bd052dd889a.png)

![image](https://user-images.githubusercontent.com/110382530/204495072-8c2a940e-ae8a-4dd4-8db2-cfba34bdcfcd.png)

Here's the whole code:
`    public void Upload() {
        NativeGallery.Permission permission = NativeGallery.GetImageFromGallery((fileLocation) => {
            if (string.IsNullOrEmpty(fileLocation)) {
                return;
            }

            Texture2D texture = NativeGallery.LoadImageAtPath(fileLocation);
            if (texture != null) {
                globalTexture = texture;
                var rect = new Rect(0, 0, texture.width, texture.height);
                var pixelsPerUnit = 100;
                var sprite = Sprite.Create(texture, rect, Vector2.zero, pixelsPerUnit, 1, SpriteMeshType.Tight);
                faceImage.sprite = sprite;
            }

            if (texture == null) {
                print("NO TEXTURE SAVED");
            }
        });
    }

    public Texture2D globalTexture; // Global variable to pass around the texture from upload to saving.

    public void ScreenshotThenSave() => StartCoroutine(TakeScreenshotAndSave());

    private IEnumerator TakeScreenshotAndSave()
    {
        yield return new WaitForEndOfFrame();

        Texture2D ss = new Texture2D( globalTexture.width, globalTexture.height, TextureFormat.RGB24, false );
        ss.ReadPixels( new Rect( 0, 0, globalTexture.width, globalTexture.height ), 0, 0 );
        ss.Apply();

        // Save the screenshot to Gallery/Photos
        NativeGallery.Permission permission =
            NativeGallery.SaveImageToGallery( ss, "AlbumName", "Image.png", ( success, path ) =>
                Debug.Log( "Media save result: " + success + " " + path ) );

        Debug.Log( "Permission result: " + permission );

        // To avoid memory leaks
        Destroy( ss );
    }`

Am I doing it right? I just changed the Screen.width and Screen.height to globalTexture.width and globalTexture.height to save the texture.

**Comment by artificial-unintelligent-programmer** [comment]
Here's the screenshot of my editor too, nothing fancy, I just drag-n-drop the script to the OnClick() of buttons:

Upload Button:
![image](https://user-images.githubusercontent.com/110382530/204496737-0d440a3a-5368-458e-9790-18e1e1b99af4.png)

Save Button:
![image](https://user-images.githubusercontent.com/110382530/204496874-4a71805b-e06a-4a9e-acee-1db698f09bfa.png)

**Comment by yasirkula** [comment]
Hi! ReadPixels reads pixels from RenderTexture.active which you aren't using in your code. In my opinion, you can pass globalTexture directly to SaveImageToGallery function, there's no need for creating a separate Texture (ss) and calling ReadPixels with it. Simply call SaveImageToGallery(globalTexture, ...). You can also remove the yield statement and convert the coroutine to a standard function.

**Comment by emmanuel-dev000** [comment]
![image](https://user-images.githubusercontent.com/110382530/204691294-fc8d264e-9ab3-47c0-8f87-ad3fbf052463.png)

Hey! It works! Thanks a ton.

**Comment by emmanuel-dev000** [comment]
I added the script in case somebody will ask/search this question or encounter this problem.

**Comment by yasirkula** [comment]
Glad to hear it 😃
