### ISSUE TITLE
LoadImageAtPath

### ISSUE THREAD

**Issue by cacdzya1995** [yasirkula/UnityNativeGallery#271]
![Captura de Pantalla 2022-12-16 a la(s) 2 12 22 p m](https://user-images.githubusercontent.com/116049839/208171745-a02d94c0-917f-452e-9d0a-c2fb78ebaee2.png)

I have a problem saving the image in a specific directory, with the LoadImageAtPath function, I can save a single image that has pickedMedia as a directory, but I need to save more images with a directory that I can name, I would like to know how I can do it. I change the string pickedmedia, but it dont work. In advance excellent plugin.

**Comment by yasirkula** [comment]
Hi, are you trying to save images that are retrieved from GetImageFromGallery?

**Comment by cacdzya1995** [comment]
Yes, i get the path from that function

**Comment by cacdzya1995** [comment]
But is on IOS, not in the editor

**Comment by yasirkula** [comment]
You can copy the image to persistentDataPath using System.IO.File.Copy function. You can set the copied file's name as you wish during this copy operation.

**Comment by cacdzya1995** [comment]
Thank you, it works
