### ISSUE TITLE
error: Permission denied when select a photo from the photo gallery IOS 16.2

### ISSUE THREAD

**Issue by mimitr** [yasirkula/UnityNativeGallery#282]
**Description of the bug**

Using the example code provided: 

```
private void PickImage( int maxSize )
{
	NativeGallery.Permission permission = NativeGallery.GetImageFromGallery( ( path ) =>
	{
		Debug.Log( "Image path: " + path );
		if( path != null )
		{
			// Create Texture from selected image
			Texture2D texture = NativeGallery.LoadImageAtPath( path, maxSize );
			if( texture == null )
			{
				Debug.Log( "Couldn't load texture from " + path );
				return;
			}

			// Assign texture to a temporary quad and destroy it after 5 seconds
			GameObject quad = GameObject.CreatePrimitive( PrimitiveType.Quad );
			quad.transform.position = Camera.main.transform.position + Camera.main.transform.forward * 2.5f;
			quad.transform.forward = Camera.main.transform.forward;
			quad.transform.localScale = new Vector3( 1f, texture.height / (float) texture.width, 1f );

			Material material = quad.GetComponent<Renderer>().material;
			if( !material.shader.isSupported ) // happens when Standard shader is not included in the build
				material.shader = Shader.Find( "Legacy Shaders/Diffuse" );

			material.mainTexture = texture;

			Destroy( quad, 5f );

			// If a procedural texture is not destroyed manually, 
			// it will only be freed after a scene change
			Destroy( texture, 5f );
		}
	} );

	Debug.Log( "Permission result: " + permission );
}
```

When I select a photo from the phone's photo library the photo library closes and the errors pop up in the Xcode debugger window: 
<img width="1180" alt="Screenshot 2023-03-06 at 10 59 28 am" src="https://user-images.githubusercontent.com/41852858/222995181-25f6c01d-8669-49cd-9d65-8bc07f746a16.png">

**Note:** The phone didn't show the "X would like to access your photos" pop-up, even though `Privacy - Photo Library Usage Description` and `Privacy - Photo Library Additions Usage Description` exist in `plist`: 
<img width="786" alt="Screenshot 2023-03-06 at 11 33 12 am" src="https://user-images.githubusercontent.com/41852858/222995376-fa4eac61-06e5-4077-9cf8-0ba74a67a414.png">

When I open `Settings -> Privacy & Security -> Photos`, it seems like the app doesn't have the access to the photo library: 
![IMG_8439](https://user-images.githubusercontent.com/41852858/222995472-c22ff844-b60b-4edf-864c-89cfc3905192.jpg)

**Reproduction steps**
1. Use the example code above, add a UI button on Unity to trigger the `PickImage` function call.
2. Click on the added button on the phone, select an image from the phone.
3. Observe that the library closes and the errors show up on the debugger.

**Platform specs**
iPhone 13Pro - iOS 16.2
Xcode 14.2

I've downloaded the plugin using the latest version of the plugin on GitHub.

**Comment by yasirkula** [comment]
It's expected for the permission popup to not show up in this case:

> Note that NativeGallery doesn't require any permissions for picking images/videos from Photos on iOS 11+

Despite the error message, does the image successfully load and show up in the scene?

**Comment by mimitr** [comment]
Apologies for the late response, all good now! Thank you!
