### ISSUE TITLE
Undefined symbol: _getPhoto and Undefined symbol: _getPhotoFromLibrary in xcode

### ISSUE THREAD

**Issue by shivambawa** [yasirkula/UnityNativeGallery#284]
works fine on but undefined sysmbol error on xocode

 

 
- Unity version: 2021.3.5*
- Platform: IOS
- Device:  iphone 13
- How did you download the plugin:  used the package manager and the github package

 
 
![Screenshot 2023-03-23 at 3 46 31 PM](https://user-images.githubusercontent.com/11889947/227172771-25105743-43ed-4c65-95ab-26ca2257ccce.png)

**Comment by yasirkula** [comment]
NativeGallery doesn't have these functions. They must be coming from another plugin.
