### ISSUE TITLE
Can not save Audio in android

### ISSUE THREAD

**Issue by laijingquan** [yasirkula/UnityNativeGallery#288]
**Description of the bug**

When I save mp3 with API NativeGallery:SaveAudioToGallery, it raise error like this:"Primary directory DCIM not allowed for contentlmedialexternallaudiolmedia;allowed directories are [Alarms, Audiobooks, Music,Notifications, Podcasts, Recordings, Ringtones"
![image](https://github.com/yasirkula/UnityNativeGallery/assets/12179026/94ac6de6-4143-437f-927a-621c02ead6c4)

Please provide the following info if this is a Unity 3D repository.

- Unity version: *e.g. 2021.3.21f1*
- Platform: *e.g. Android, iOS,
- Device: google pixel2
- How did you download the plugin: *e.g. Asset Store, GitHub, Package Manager. Please make sure that your asset is up-to-date*
version:1.7.3
**Additional info**

**Comment by yasirkula** [comment]
Wanted to let you know that this is in my to-do list.

**Comment by SandaruwanFdo** [comment]
any updates?

**Comment by yasirkula** [comment]
Download the latest version from GitHub and you should be good to go.
