### ISSUE TITLE
Save with same name without duplication

### ISSUE THREAD

**Issue by MaidinChina** [yasirkula/UnityNativeGallery#289]
While if I try to save images with the same name, I got multiple copies in the gallery. 

I tried to use GetImage function, how ever, it seems like this function is not to get the image directly but open a dialog? 

Here's my code: 
```
            NativeGallery.GetImageFromGallery((path)=>{
                if (!string.IsNullOrEmpty(path)) {
                    Debug.Log("Existing image found! ");
                    File.Delete(path);
                }

                NativeGallery.SaveImageToGallery(texture, folder, filename);
            }, filename);
```

How can I save images with the same name without duplication? Thanks!

**Comment by yasirkula** [comment]
Are you trying to overwrite the previous image? On which platforms are you trying to accomplish this?

**Comment by MaidinChina** [comment]
@yasirkula Android and iOS

**Comment by yasirkula** [comment]
On Android you can call the following code in Awake/Start and it'll attempt to overwrite the old file, if exists:

```csharp
#if UNITY_ANDROID
using( AndroidJavaClass ajc = new AndroidJavaClass( "com.yasirkula.unity.NativeGallery" ) )
    ajc.SetStatic<bool>( "overwriteExistingMedia", true );
#endif
```

This isn't possible on iOS with NativeGallery.

**Comment by MaidinChina** [comment]
Thanks @yasirkula!
