### ISSUE TITLE
No API to save the Render Texture directly as jpeg or png

### ISSUE THREAD

**Issue by ragavendranbala** [yasirkula/UnityNativeGallery#294]
If I have a image as render texture, i need to convert it as texture 2D first and then need to save it as image in local storage. While converting render texure to texture2D, Ineed to  need to perform the below

```
  public static Texture2D toTexture2D(this RenderTexture rTex)
    {
        Texture2D tex = new Texture2D(rTex.width, rTex.height,GraphicsFormat.R32G32B32A32_SFloat,0);
        var old_rt = RenderTexture.active;
        RenderTexture.active = rTex;

        tex.ReadPixels(new Rect(0, 0, rTex.width, rTex.height), 0, 0);
        tex.Apply();

        RenderTexture.active = old_rt;
        return tex;
    }
```
but I don't know the format of the texture. duie to this, the saved image is darker in color for me

**Comment by yasirkula** [comment]
I'm usually using this, if it makes any difference: `new Texture2D(rTex.width, rTex.height, TextureFormat.RGBA32)`

**Comment by ragavendranbala** [comment]
My render texture details:
format : RGB111110Float
Graphics Format : B10G11R11_UFloatPack32

Converting this render texture to texture 2d as rgba32 or the above format producing the same result not the expected color

**Comment by ragavendranbala** [comment]
My render texture details:
format : RGB111110Float
Graphics Format : B10G11R11_UFloatPack32

Converting this render texture to texture 2d as rgba32 or the above format producing the same result not the expected color

**Comment by yasirkula** [comment]
I'd recommend asking this question on Unity forums because I'm not very experienced about texture formats: https://forum.unity.com/forums/general-graphics.76/

**Comment by marvpaul** [comment]
@ragavendranbala I just copied a short code snippet of mine which I use to create a texture2d out of an RenderTexture. For some reason on Android my original RenderTexture format was not supported when I remember correctly, so I first create a new RenderTexture, copy the content of my original one and then feeding it into the Texture
`#if UNITY_ANDROID
        RenderTexture rt = new RenderTexture(imageOutput.texture.width, imageOutput.texture.height, 0, imageOutput.texture.graphicsFormat);
#else
        RenderTexture rt = new RenderTexture(imageOutput.texture.width, imageOutput.texture.height, 0, RenderTextureFormat.ARGB32);

#endif
        Graphics.CopyTexture((RenderTexture)imageOutput.texture, rt);
        RenderTexture.active = rt;
        Debug.Log(rt.format);
        Texture2D tex = new Texture2D(rt.width, rt.height);
        tex.ReadPixels(new Rect(0, 0, rt.width, rt.height), 0, 0);
        RenderTexture.active = null;
        tex.Apply();

        byte[] bytes;
        bytes = tex.EncodeToPNG();`
