### ISSUE TITLE
[Question] non image data

### ISSUE THREAD

**Issue by luigi-bar** [yasirkula/UnityNativeGallery#295]
Hi
    Many thanks for this nice plugin.
Let me ask a question: can I use this to save non  image data (like a custom format with some meta data index)? Or would it be refused by the gallery?
Any difference in android vs ios i should be aware of?
Thanks!!

**Comment by yasirkula** [comment]
Hi! This isn't possible. But [NativeFilePicker](https://github.com/yasirkula/UnityNativeFilePicker) may be helpful here.

**Comment by luigi-bar** [comment]
Thanks i will check!
