### ISSUE TITLE
UnauthorizedAccessException on some cases in Android

### ISSUE THREAD

**Issue by rotter** [yasirkula/UnityNativeGallery#30]
Hi, love the plugin, thanks for the effort!

On my game I'm getting some random "UnauthorizedAccessException" in production when some people select the photo on his gallery (Android) and I try to read it. I can't reproduce it on my end, Im getting the stacktraces on Unity analytics for a small percentage of my players.

I check the permission before calling GetImageFromGallery, and from what I see on the code of the method your plugin also checks for the permission, so I have no clue why is the exception happening, thought I should share here as an issue. If it's something I'm doing wrong I'm sorry, and please let me know how to fix :)

Exception:
UnauthorizedAccessException: Access to the path "/storage/6665-3432/DCIM/Camera/20180515_093426.jpg" is denied.

Stacktrace (edited a bit to simplify):
System.IO.File.Open (System.String path, FileMode mode) <-- exception here
(CALLBACK) MyGameScene.ProcessSelectedFilePath (System.String selectedFilePath)
(CALLBACK) MyGameScene.PhotoSelectionCallback (System.String selectedPhotoPath)
NativeGallery.GetMediaFromGallery (.MediaPickCallback callback, Boolean imageMode, System.String mime, System.String title, Int32 maxSize)
NativeGallery.GetImageFromGallery (.MediaPickCallback callback, System.String title, System.String mime, Int32 maxSize)

**Comment by rotter** [comment]
The code on my side that triggers the exception:

FileStream selectedFile = File.Open(selectedFilePath, FileMode.Open);

Regarding versions I've checked about 20 stack traces and the versions seen were Android 5, 6 and 7.

And from what I see in the stack traces there are 2 flows that get to this point/exception:
1) When the user dont have the permission initially, I ask for it, and then on "Update" after the permission flag is on I call "GetImageFromGallery"
2) When the user has already given the permission in the past, so I simply call "GetImageFromGallery" directly

**Comment by yasirkula** [comment]
You can try the following:

`FileStream selectedFile = File.Open(selectedFilePath, FileMode.Open, FileAccess.Read);`

Adding FileAccess.Read to File.Open helped me get rid of similar exceptions on a standalone Unity game in the past. Maybe the same applies to Android, as well.

**Comment by rotter** [comment]
Thanks, I will try that!

**Comment by rotter** [comment]
I think your suggestion has fixed my problem, crashes seem to have vanished recently, but I'm not completely sure yet, let me run it for a couple more days and I will write back

**Comment by rotter** [comment]
I think it's solved! Thanks a lot!

**Comment by yasirkula** [comment]
You are welcome! Hope the issue is indeed solved for good.
