### ISSUE TITLE
Exception: No such proxy method: NativeGalleryNamespace.NGMediaReceiveCallbackAndroid.OnMediaReceived(System.String)

### ISSUE THREAD

**Issue by ShenKang4181** [yasirkula/UnityNativeGallery#300]
when i use NativeGallery.GetImagesFromGallery( action );
This error occurs when you select a picture from the album and return to the software.

**Comment by yasirkula** [comment]
Can you update your plugin from GitHub? Can you reproduce this issue on a new project, as well? Are you using a custom build system of some sort that I should know of?

**Comment by ShenKang4181** [comment]
I have used the latest version of the plug-in, and there is no problem in normal use in the new project. What can I do when I use the hybridclr, and I use it normally when I don't import the hybridclr. I think I should feedback this problem to the hybridclr, but I would be very grateful if I know about the hybridclr and find out what happened when this problem occurred.

**Comment by yasirkula** [comment]
Is the issue reproducible when adding hybridclr to the new project? If not, are you using a custom code stripping solution? The plugin comes with proguard.txt that should work with Gradle builds but if you're building from Android Studio or using some sort of other build solution, they you may need to add proguard filters to that solution manually: https://github.com/yasirkula/UnityNativeGallery/blob/master/.github/AAR%20Source%20(Android)/proguard.txt

**Comment by yasirkula** [comment]
Oh, or maybe adding [Preserve attribute](https://docs.unity3d.com/ScriptReference/Scripting.PreserveAttribute.html) to NGMediaReceiveCallbackAndroid.OnMediaReceived function resolves the issue?

**Comment by ShenKang4181** [comment]
Hybridclr will fix this problem. ⸜₍๑•⌔•๑₎⸝
