### ISSUE TITLE
NativeGallery.GetImageFromGallery Not working on Windows

### ISSUE THREAD

**Issue by pei1104** [yasirkula/UnityNativeGallery#305]
**Description of the bug**

Using NativeGallery.GetImageFromGallery, 
the selection window to choose images does not pop up.
( Windows standalone build)

**Reproduction steps**

1. Call NativeGallery.GetImageFromGallery.
2. Observe that the selection window does not appear.

**Platform specs**
- Unity version: 2021.3.32f1
- Platform:  Windows 
- Device: ASUS Zenbook, Windows11
- How did you download the plugin: GitHub

**Additional info**

This works perfectly on both Android, iOS and in unity editor.

[Edit]
I just realized that this package doesn't seem to have specific support for Windows. I opened the issue because it used to work smoothly before. If there won't be any future support for Windows, feel free to close this issue. Thank you! This plugin is awesome!

**Comment by yasirkula** [comment]
Hi! Unfortunately only Android and iOS platforms are supported. Editor functionality is for preview purposes only and uses UnityEditor namespace classes.
