### ISSUE TITLE
v1.7.9 ERROR com.android.build.gradle.internal.tasks.CheckDuplicatesRunnable 

### ISSUE THREAD

**Issue by iVideoGameBoss** [yasirkula/UnityNativeGallery#309]
**Description of the bug**

I'm using Unity 2022.3.19f1. After I upgraded UnityNativeGallery plugin to version v1.7.9 and attempt to compile to android I get this error 

![Screenshot 2024-02-03 205130](https://github.com/yasirkula/UnityNativeGallery/assets/129109589/b7b0339b-4b1e-4dc7-96f9-b9de2adc154e)

As per Google we have to now be at Android level 33. The previous version of UnityNativeGallery plugin works great and complies using Android Level 33. But when you upgrade to new version of UnityNativeGallery plugin to version v1.7.9 . I have pinned it down to this plugin. 

**Reproduction steps**

Upgrade to latest release of UnityNativeGallery plugin to version v1.7.9 and attempt to create a apk file. It will show this message. Make sure you are on Android Level 33 as this is Googles new requirement going forward.

[
![Screenshot 2024-02-03 205638](https://github.com/yasirkula/UnityNativeGallery/assets/129109589/1b231ab9-3fd6-46ed-9c04-5fdd3afb2422)
](url)

**Platform specs**
Android 13

Please provide the following info if this is a Unity 3D repository.

- Unity version: 2022.3.19f1
- Platform: Android
- Device: Android Mobile Phone - Android 13 - AT&T Calypso 4*
- I download loaded the plugin from GitHub. Also tried it from Unity Package Manager. Still same issue.

**Additional info**

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':launcher:checkReleaseDuplicateClasses'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.CheckDuplicatesRunnable
   > Duplicate class com.yasirkula.unity.NativeGallery found in modules NativeGallery (NativeGallery.jar) and NativeGallery-runtime (:NativeGallery:)
     Duplicate class com.yasirkula.unity.NativeGalleryMediaPickerFragment found in modules NativeGallery (NativeGallery.jar) and NativeGallery-runtime (:NativeGallery:)
     Duplicate class com.yasirkula.unity.NativeGalleryMediaReceiver found in modules NativeGallery (NativeGallery.jar) and NativeGallery-runtime (:NativeGallery:)
     Duplicate class com.yasirkula.unity.NativeGalleryPermissionFragment found in modules NativeGallery (NativeGallery.jar) and NativeGallery-runtime (:NativeGallery:)
     Duplicate class com.yasirkula.unity.NativeGalleryPermissionReceiver found in modules NativeGallery (NativeGallery.jar) and NativeGallery-runtime (:NativeGallery:)
     Duplicate class com.yasirkula.unity.NativeGalleryUtils found in modules NativeGallery (NativeGallery.jar) and NativeGallery-runtime (:NativeGallery:)

**Comment by yasirkula** [comment]
NativeGallery.jar was upgrade to NativeGallery.aar so you'll need to delete Plugins/NativeGallery/Android/NativeGallery.jar from your project.

**Comment by iVideoGameBoss** [comment]
Thank you! that fixed it
