### ISSUE TITLE
Unity 2023 support

### ISSUE THREAD

**Issue by AlexanderLukashin** [yasirkula/UnityNativeGallery#312]
In the new version, UnityPlayer has been [changed](https://docs.unity3d.com/2023.1/Documentation/Manual/UpgradeGuide20231.html#android-unityplayer). 
As far as I understand you are using it. 
`using( AndroidJavaObject unityClass = new AndroidJavaClass( "com.unity3d.player.UnityPlayer" ) )`
Is Unity 2023 planned to be supported?

**Comment by yasirkula** [comment]
I'm only accessing a static property in that class. It seems like the class still exists but is now abstract. Perhaps the static field still remains in that class. Did you get the chance to test the plugin on Unity 2023?

**Comment by AlexanderLukashin** [comment]
You're right. I tried to build an empty project instead of my own project. Everything works fine. So the problem with building my project is something else. Thanks for the feedback.

**Comment by yasirkula** [comment]
Did your project throw an error related to UnityPlayer?

**Comment by AlexanderLukashin** [comment]
There was a problem with unityLibrary. I thought maybe these things are related. But I have already solved this problem.
FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* Where:
Script 'C:\Users\sanya\OneDrive\Documents\XRBlueprint\Library\Bee\Android\Prj\IL2CPP\Gradle\launcher\setupSymbols.gradle' line: 6

* What went wrong:
A problem occurred evaluating script.
> A problem occurred configuring project ':unityLibrary'.
   > Could not create an instance of type com.android.build.api.variant.impl.LibraryVariantBuilderImpl.
      > Namespace not specified. Specify a namespace in the module's build file. See https://d.android.com/r/tools/upgrade-assistant/set-namespace for information about setting the namespace.
        
        If you've specified the package attribute in the source AndroidManifest.xml, you can use the AGP Upgrade Assistant to migrate to the namespace value in the build file. Refer to https://d.android.com/r/tools/upgrade-assistant/agp-upgrade-assistant for general information about using the AGP Upgrade Assistant.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
A problem occurred configuring project ':launcher'.
> compileSdkVersion is not specified. Please add it to build.gradle

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.
