### ISSUE TITLE
When the Android phone pops up to confirm the authorization, click Allow and get stuck.

### ISSUE THREAD

**Issue by ShenKang4181** [yasirkula/UnityNativeGallery#313]
When using HybridCLR, when the Android phone pops up to confirm the authorization, click Allow and get stuck.
My UnityNativeGallery can be used normally
But if I use HybridCLR, I will get stuck when I click Allow.
But when I use HybridCLR, the license of AR Foundation won't get stuck.
this is my code:
public void OnbuttonUpNew( )
    {
        NativeGallery.GetImageFromGallery( OnbuttonUpNew );
    }

    public void OnbuttonUpNew( string filePath )
    {
        
    }

**Comment by yasirkula** [comment]
Could you request permission asynchronously beforehand via RequestPermissionAsync?

**Comment by ShenKang4181** [comment]
Exception: No such proxy method: NativeGalleryNamespace.NGPermissionCallbackAndroid.OnPermissionResult(System.Int32)

**Comment by ShenKang4181** [comment]
I checked the log,Exception: No such proxy method: NativeGalleryNamespace.NGPermissionCallbackAndroid.OnPermissionResult(System.Int32)，i try to add this to link.xml
<?xml version="1.0" encoding="utf-8"?>
<linker>
	<assembly fullname="NativeGallery.Runtime">
		<type fullname="NativeGalleryNamespace.NGMediaReceiveCallbackAndroid" preserve="all" />
		<type fullname="NativeGalleryNamespace.NGPermissionCallbackAndroid" preserve="all" />
	</assembly>
</linker>

**Comment by ShenKang4181** [comment]
I solved this problem, and I added in link.xml.
<?xml version="1.0" encoding="utf-8"?>
<linker>
	<assembly fullname="NativeGallery.Runtime">
		<type fullname="NativeGalleryNamespace.NGMediaReceiveCallbackAndroid" preserve="all" />
		<type fullname="NativeGalleryNamespace.NGPermissionCallbackAndroid" preserve="all" />
	</assembly>
</linker>

**Comment by ShenKang4181** [comment]
![image](https://github.com/yasirkula/UnityNativeGallery/assets/50401776/b78117ca-6e14-4979-8b6e-cb8113b25eee)

**Comment by ShenKang4181** [comment]
But thank you for trying to solve the problem. ૮₍ •ᴗ•₎ა

**Comment by yasirkula** [comment]
Ah, glad to hear it's resolved! I wonder if adding [UnityEngine.Scripting.Preserve] attribute to the NGPermissionCallbackAndroid class, its constructors and methods resolve the issue without requiring linker.xml? If so, I can make this change in the code and you'd no longer need to modify the linker file.

**Comment by ShenKang4181** [comment]
Sorry, I'm using this UnityNativeGallery added by package manager. There's no way to change this code, and the build time is too long (> 30min), so I'm sorry.
I think you can add [unityengine. scripting.preserve] directly. PreserveAttribute can prevent bytecode stripping from removing classes, methods, fields or properties.
If there is something, there is nothing. It can be ineffective, but it's better than nothing. Give it a try. What if I don't raise this question at all, or even avoid some problems?

**Comment by yasirkula** [comment]
Before building the game the next time, could you undo your link.xml change, update the plugin and see if the issue is resolved in the latest version?

**Comment by ShenKang4181** [comment]
ok i will

**Comment by ShenKang4181** [comment]
yes！i delete  link.xml and update UnityNativeGallery , Now it can be used normally 
૮₍ •ᴗ•₎ა
