### ISSUE TITLE
iOS GetImageFromGallery show all photos event if PHAuthorizationStatusLimited

### ISSUE THREAD

**Issue by zhangxiaojun92** [yasirkula/UnityNativeGallery#319]
I use NativeGallery 1.8.0 on iOS 14.8 and 17.0, get permission from user. User select "Select Photos" and choose one photo. 

But when I call `GetImageFromGallery`, show all photos for users

Thanks.

**Comment by yasirkula** [comment]
GetImageFromGallery doesn't ask permission on iOS 11 and later: https://github.com/yasirkula/UnityNativeGallery/blob/66157bd32db65439aca72ad5ed0f0fb702d6ef72/Plugins/NativeGallery/iOS/NativeGallery.mm#L118-L120

**Comment by zhangxiaojun92** [comment]
Thanks for your answer.
