### ISSUE TITLE
How to disable permission request on launch and instead use Runtime permissions

### ISSUE THREAD

**Issue by rcstamp** [yasirkula/UnityNativeGallery#321]
**Description of the bug**

We want to only ask for permission the first time the user wants to access their photos (in our case, to change profile picture). However on launch on Android, it's asking for access to the devices storage. How can we disable that? Note, we only need Read permissions.

**Comment by rcstamp** [comment]
Just adding Read permission to manifest fixed it!

**Comment by yasirkula** [comment]
This issue can be fixed by modifying AndroidManifest as follows: https://github.com/yasirkula/UnityAndroidRuntimePermissions?tab=readme-ov-file#how-to

Best wishes!
