### ISSUE TITLE
Plugin is not working for android 13 and above 

### ISSUE THREAD

**Issue by shoib-akthar** [yasirkula/UnityNativeGallery#322]
> The problem is the permissions are not being triggred but the same is working for the android 12 and below devices

**Comment by yasirkula** [comment]
If the permission functions return Granted without showing a dialog, then it's all fine and from user's perspective, even better than showing a permission dialog. See: https://github.com/yasirkula/UnityNativeGallery?tab=readme-ov-file#c-runtime-permissions

**Comment by shoib-akthar** [comment]
<img width="1791" alt="123" src="https://github.com/yasirkula/UnityNativeGallery/assets/69345139/2ee0f7a5-35b9-48c9-9d59-df33238c60de">
The above logs are from android 12 simulator and below is android 13
<img width="1790" alt="12" src="https://github.com/yasirkula/UnityNativeGallery/assets/69345139/c289b88f-d355-4175-b4be-739864d839b0">


The permissions request itself is not triggering and even after manually entering the manifest also tried manually changing the permissions from the app but the gallery is not opening

**Comment by shoib-akthar** [comment]
It's working now i tried using an automated setup for Android 13+ and did not do any changes in the test code provided for testing in a new unity project.

As described in the below link permission is not required, as it was already returning granted.
See: https://github.com/yasirkula/UnityNativeGallery?tab=readme-ov-file#c-runtime-permissions

Thanks for the help again!
