### ISSUE TITLE
Problem in saving the image or screenshot using "SaveImageToGallery" function

### ISSUE THREAD

**Issue by shuaibimran** [yasirkula/UnityNativeGallery#35]
Actually I am trying to take a screenshot and save it into the Android gallery, my code is following:
        
        NativeGallery.Permission permission = NativeGallery.CheckPermission();
        if (permission == NativeGallery.Permission.Granted) {
             Debug.Log("May proceed");
         }
        else {
             Debug.Log("Not allowed");
        }

             Debug.Log("Path is "+NativeGallery.GetSavePath("GalleryTest","My_img_{0}.png"));
             //Output ==>  /storage/emulated/0/DCIM/GalleryTest/My_img_1.png

        Texture2D ss = new Texture2D( Screen.width, Screen.height, TextureFormat.RGB24, false );
        ss.ReadPixels( new Rect( 0, 0, Screen.width, Screen.height ), 0, 0 );
        ss.Apply();
        Debug.Log("Secondlast");
        permission = NativeGallery.SaveImageToGallery( ss, "GalleryTest", "My_img_{0}.png" ) ;
        Debug.Log("Done screenshot");

but my it never save the screenshot, when i see the console, I get 2 important logs
1.My Debug log "SecondLast" was print on the console  but not the last one "Done screenshot"
2.There is an exception printed "UnauthorizedAccessException: Access to the path "/storage/emulated/0/DCIM/GalleryTest/My_img_1.png" is denied."

Important point :- I already already set the Write permissions to External (SDCard) in unity player settings. (actually I try with both settings "Internal" and "External")

**Comment by yasirkula** [comment]
Please see: https://forum.unity.com/threads/native-gallery-for-android-ios-open-source.519619/page-2#post-3533928

**Comment by yasirkula** [comment]
I'm closing this issue because the discussion continued on the forum thread.

**Comment by joshudev** [comment]
Hi @yasirkula 

I'm also getting the same error:

UnauthorizedAccessException: Access to the path "/storage/emulated/0/DCIM/GalleryTest/Myimg1.png" is denied.

However, if I restart the app, it will work fine. It only seems to be happening the first time the app is opened and the permission is granted.

Any ideas? Thanks!

**Comment by joshudev** [comment]
```
07-05 00:57:35.686  4940  4957 E Unity   : UnauthorizedAccessException: Access to the path "/storage/emulated/0/DCIM/GalleryTest/Myimg5.jpeg" is denied.
07-05 00:57:35.686  4940  4957 E Unity   :   at System.IO.FileStream..ctor (System.String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, Boolean anonymous, FileOptions options) [0x00000] in <filename unknown>:0
07-05 00:57:35.686  4940  4957 E Unity   :   at System.IO.FileStream..ctor (System.String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize) [0x00000] in <filename unknown>:0
07-05 00:57:35.686  4940  4957 E Unity   :   at System.IO.File.Create (System.String path, Int32 bufferSize) [0x00000] in <filename unknown>:0
07-05 00:57:35.686  4940  4957 E Unity   :   at System.IO.File.Create (System.String path) [0x00000] in <filename unknown>:0
07-05 00:57:35.686  4940  4957 E Unity   :   at System.IO.File.WriteAllBytes (System.String path, System.Byte[] bytes) [0x00000] in <filename unknown>:0
07-05 00:57:35.686  4940  4957 E Unity   :   at NativeGallery.SaveToGallery (System.Byte[] mediaBytes, System.String album, System.String filenameFormatted, Boolean isImage, .MediaSaveCallback callback) [0x00000] in <filename unknown>:0
07-05 00:57:35.686  4940  4957 E Unity   :   at NativeGallery.SaveImageToGallery (UnityEngine.Texture2D image, S
07-05 00:57:36.957  4940  4981 E Unity   : java.io.EOFException
07-05 00:57:36.957  4940  4981 E Unity   :
07-05 00:57:36.957  4940  4981 E Unity   : (Filename:  Line: 391)
```

Then after app restart:

07-05 01:01:29.771  5266  5283 I Unity   : Saving to gallery: /storage/emulated/0/DCIM/GalleryTest/Myimg5.jpeg

**Comment by yasirkula** [comment]
I'm guessing that GalleryTest directory was not present when the UnauthorizedAccessException was thrown. That directory is automatically created by the plugin but maybe there was a delay in your case? Well, I haven't encountered this issue myself, so I'm not sure.

What happens when you attempt to save the image a second time, without restarting the application? Does it work? If not, when you navigate to the DCIM directory, is the GalleryTest directory present there? You may have to delete the GalleryTest directory before doing these tests.

**Comment by joshudev** [comment]
Thanks for getting back @yasirkula.

What I have discovered since is that it works fine on a real device, but the error I was getting was on the Android emulators provided by Android studio. If this happens to be the case for everyone, perhaps this could be documented somewhere?

**Comment by yasirkula** [comment]
Well, my emulator's Gallery doesn't work for some reason but NativeGallery does save the image without any issues because I can see the image in Photos app. My emulator has x86 processor, though.

**Comment by yasirkula** [comment]
Possibly fixed in https://github.com/yasirkula/UnityNativeGallery/commit/ba3fbf4f4c2840d6ac2c1e1145ca14b7834660c0
