### ISSUE TITLE
Getting saved images on PC

### ISSUE THREAD

**Issue by hippogamesunity** [yasirkula/UnityNativeGallery#36]
Hi! This issue doesn't relate to your plugin, but maybe you've got an experience with it.
The problem is when I'm saving new images on Android I want to connect my phone to PC and get them (see/copy/delete). But it seems Android refresh file cache not very frequently, anyway I can't see new files on PC right away. Have to wait a few minutes, some people have reported that images become available on PC in a few days. On the other side, if I make a screenshot (using default button combination), it appears on PC right away, I just need to open screenshots folder again.

**Comment by hippogamesunity** [comment]
...and actually this C# solution worked for me:
https://stackoverflow.com/questions/38134283/how-do-i-refresh-the-android-gallery-using-unity
Not sure about Android versions compatibility.

**Comment by yasirkula** [comment]
My Java code actually calls the very same function with the same parameters, that's kinda weird: https://github.com/yasirkula/UnityNativeGallery/blob/0fafcf2082b2229f84e5e47ecd9933bf608dbb36/JAR%20Source/NativeGallery.java#L47

I'll try to reproduce the issue myself soon. Thanks for reporting this.

**Comment by hippogamesunity** [comment]
You're right, sorry, it was my fault. Had to implement my own save function that's why you MediaScanFile was not called.
