### ISSUE TITLE
Do you have a plugin contains UnityNativeGallery and UnityNativeCamera together

### ISSUE THREAD

**Issue by oOtroyOo** [yasirkula/UnityNativeGallery#38]
These two plugins are very possible to use together , and they got a lot similar code. 
It's might not a good idea to use them separately if there are similar .
such as `enum Permission` will become two different types (it can be cast to another anyway.).
and I'm not sure witch parts of the code can be combined .

**Comment by yasirkula** [comment]
I didn't want someone who just wants to e.g. save images to gallery to have to add a `<provider ... />` to his/her AndroidManifest or have their _Camera Usage Description_ and _Microphone Usage Description_ altered in Xcode (which are the requirements for NativeCamera). As you said, there are some duplicate code (even in the Java source code) but this way, people can use the plugin that they need without bothering with the requirements of the other plugin.

**Comment by oOtroyOo** [comment]
ok ,thanks
