### ISSUE TITLE
[Android] Saved image not showing in gallery

### ISSUE THREAD

**Issue by tyfurness** [yasirkula/UnityNativeGallery#39]
I can see the image being saved to the correct folder in DCIM/{folder}, but it is not showing up as an album or as a viewable picture in the gallery on device. Tested on the S6 and the OnePlus 3 and neither of them showed it.

**Comment by yasirkula** [comment]
Are there any error messages in Logcat? Are you using Gradle build system or internal build system? What is your Target SDK version and Unity version?

**Comment by tyfurness** [comment]
No error message, it does it all correctly other than actually showing it in the gallery.

Internal build system, targeting highest API, 2017.4.0f1

**Comment by yasirkula** [comment]
I'm guessing that [NativeGallery.MediaScanFile](https://github.com/yasirkula/UnityNativeGallery/blob/d16ff30c1342d5baab1295dc10736bb79dde35cf/JAR%20Source/NativeGallery.java#L49-L52) native function is not executed properly. I haven't encountered such an issue myself and am surprised to hear it happening on two distinct devices. What is the highest Android API version installed on your system?

**Comment by tyfurness** [comment]
```
private const string FILE_NAME = "Final_Image_{0}";
NativeGallery.SaveImageToGallery(txt.EncodeToPNG(), "Some Folder Name", string.Format(FILE_NAME, imageNumber), (error) => 
			{ 
				if(!string.IsNullOrEmpty(error))
				   Debug.Log("Error saving picture to album: " + error);
			});
```
![screen shot 2018-07-06 at 11 11 51 am](https://user-images.githubusercontent.com/22301882/42386428-77151090-810d-11e8-942d-31855ccf1ab1.png)

**Comment by tyfurness** [comment]
Right, my bad. I have up to API 27 installed.

**Comment by yasirkula** [comment]
I've tested the example code with Unity 2017.3.0p2, Internal build system and highest installed Target API (mine is also 27) on Galaxy S3 and it worked properly.

It's strange to not hear about this issue until now (after plentiful of downloads), which makes me wonder if the issue is related to your test devices. If they are test devices of your company, maybe some admin settings/parental control settings are affecting the plugin? Although unlikely, it is also possible that using another Unity version would solve the problem.

If you were looking at Logcat with some filters applied (e.g. only showing logs with Unity tag), try searching for error messages without using any filters.

**Comment by tyfurness** [comment]
Alright, I did get it working, sort of. On the S6 the photo does show, but it doesn't show it in it's own custom folder (despite me seeing the folder existing in the correct space). But on the OnePlus 3, it shows it in it's custom folder. So I suppose it comes down to the device/program used to look at photos. I've attached a screenshot for more clarity. The picture in the red box is the one I took an saved to the custom folder.

![screenshot_20180706-133213](https://user-images.githubusercontent.com/22301882/42393130-58cdde3a-8123-11e8-969f-e1353ad3291f.png)

I don't think there's anything you can do, but if you have any ideas, that would be helpful! 

Thanks!

Also the issue was that in my image name I didn't have `.png` at the end of it.

**Comment by yasirkula** [comment]
When _filenameFormatted_ doesn't have an extension, NativeGallery [should automatically add ".png" to it](https://github.com/yasirkula/UnityNativeGallery/blob/d16ff30c1342d5baab1295dc10736bb79dde35cf/Plugins/NativeGallery/NativeGallery.cs#L235-L236); that's unexpected, lol.

On S6, if you captured the image with a camera plugin, then the image in the red box might be a leftover of the camera app. Some camera apps save images in two different locations and don't delete those copies afterwards. If you restart the device and then see the image in its own custom folder, that should further support my theory. But in this case, we will be back to the point where NativeGallery.MediaScanFile is not executed properly. If a restart doesn't change anything, check if this topic helps you: https://forums.androidcentral.com/samsung-galaxy-s6/533997-galaxy-s6-gallery-not-showing-all-pictures.html

**Comment by tyfurness** [comment]
Yeah I thought it was weird too, however when I changed it from `private const string FILE_NAME = "Final_Image_{0}";` to `private const string FILE_NAME = "Final_Image_{0}.png";` it worked fine. When I looked on device the images with the first iteration couldn't be opened, but when I did the second iteration they were able to be opened and started showing up in the gallery.

**Comment by tyfurness** [comment]
As for the S6, restarting didn't do anything for me. And while that thing you linked would likely work, I can't expect users of the app to do that if they want to see it unfortunately. It works if the user used the 'Gallery' app, so we might just have to live with that. I'll verify on some other devices as well just to confirm it's only the S6. Thanks for the help! :D

**Comment by yasirkula** [comment]
Glad to be of help!
