### ISSUE TITLE
Gallery Open

### ISSUE THREAD

**Issue by unbounded26** [yasirkula/UnityNativeGallery#4]
- Can you implement a feature to open the **native Gallery for Android and iOS** and allow pick/select just 1 image or video and return it respectively according to the separate function call of image or video?
- Also, if image function is called show only images, and if video function is called show only videos.

It's an urgent request. So looking forward to your reply soon

**Comment by yasirkula** [comment]
Let me see what I can do.

**Comment by yasirkula** [comment]
I've updated the package.

**Comment by unbounded26** [comment]
Thanks for your quick response and implementation. Thumbs up!

I tried the RequestPermission, PickImage and PickVideo functions, but none is working. Every time the permission is denied. I tested on real devices Samsung and Xiaomi Note 4X, also on emulator Genymotion, the same result everywhere, Permission Denied.

**Comment by yasirkula** [comment]
It usually occurs when user select "Don't ask again" while denying a request. If you haven't seen a request in the lifetime of the app, then a parental control sort of thing might be blocking you from granting the requested permission.

You should go to Settings for your app and see if the Storage permission is granted. If not, grant it manually and try again. If it works, probably you had permanently declined the Storage request before. Now you can uninstall the app and then reinstall it to see the permission dialog manually.

**Comment by yasirkula** [comment]
Did you complete the following step:

> *for Android*: set **Write Permission** to **External (SDCard)** in **Player Settings**

You can verify it by checking if **android.permission.WRITE_EXTERNAL_STORAGE** exists in *PROJECT_PATH\Temp\StagingArea\AndroidManifest.xml*.

**Comment by unbounded26** [comment]
Yes, this step I was missing! 
Thanks for the help! Thumbs up!

**Comment by yasirkula** [comment]
You are welcome ^^
