### ISSUE TITLE
Please add Assembly Definition Files support.

### ISSUE THREAD

**Issue by SetoKaiba** [yasirkula/UnityNativeGallery#42]
It's currently compiled to firstpass dll. It's unable to use without a lot modification with Assembly Definition Files. Could you please rearrange your code to support Assembly Definition Files？

Just move the csharp files outside the Plugins folder. It will be ok.

**Comment by yasirkula** [comment]
I think it should be sufficient to create an assembly definition file in NativeGallery folder: https://blogs.unity3d.com/2017/11/22/unity-2017-3b-feature-preview-assembly-definition-files-and-transform-tool/

> Unity gives priority to the assembly definition files over the Predefined Compilation System.
> 
> This means that having any of the special folder names from the predefined compilation inside an assembly definition file folder will not have any effect on the compilation. Unity treats these as regular folders without any special meaning.

That should apply to vice versa?
