### ISSUE TITLE
iOS not Loading picture

### ISSUE THREAD

**Issue by andersonaraujodl** [yasirkula/UnityNativeGallery#43]
Hello!

First I'd like to thank you for the incredible work!

On android it works perfectly although I'm facing an issue on iOS. The first time I call my gallery method it asks for permission, opens the gallery, but does nothing after that. It looks like it doesn't catch the path on the first attempt, but on my second try, it doesn't matter which picture I choose, it brings the previous picture instead. Something like if it holds the picture somewhere, but never uses it, and brings it back later, on the next call.

I'm using it together with the ImageCrop made yourself, but not sure if I did something wrong! :(
Would be able to help me on this?

Thanks in advance.

**Comment by yasirkula** [comment]
Hi! It seems as if NativeGallery returns the image's path before it is written to the disk/while it is being written to the disk, but AFAIK this line ensures that image is written to the disk synchronously: https://github.com/yasirkula/UnityNativeGallery/blob/master/Plugins/NativeGallery/iOS/NativeGallery.mm#L482

Can you see any error messages in Xcode console? If you use the [example code](https://github.com/yasirkula/UnityNativeGallery#example-code) to display the selected image on a cube without using the ImageCropper plugin, does everything work properly?

**Comment by andersonaraujodl** [comment]
Thanks for you reply!
I'll try to make the suggested modification without the ImageCropper and will get back to you ASAP!

**Comment by andersonaraujodl** [comment]
Well, I've got a feedback: did all the tests and realized that there is something wrong with my logic (just couldn't figure out why it works perfect on Android and not on iOS). I'm attaching the sample bellow to see if there's something you can help with.

```
private IEnumerator CropPic()
    {
        yield return new WaitForEndOfFrame();

        bool ovalSelection = false;
        bool autoZoom = true;

        float minAspectRatio = 1, maxAspectRatio = 1;

        NativeGallery.Permission permission = NativeGallery.GetImageFromGallery((path) =>
        {
            Debug.Log("Image path: " + path);
            if (path != null)
            {
                // Create Texture from selected image
                texture = NativeGallery.LoadImageAtPath(path, 1024);

                if (texture == null)
                {
                    Debug.Log("Couldn't load texture from " + path);
                    return;
                }

                if (ImageCropper.Instance.IsOpen)
                    return;
            }
        }, LanguageManager.GetTranslation("SelectImage"), "image/png", 1024);

        newProfileInstance.previousTexture = (Texture2D) newProfileInstance.profileImage.texture;

        // If image cropper is already open, do nothing
        if (ImageCropper.Instance.IsOpen)
            ImageCropper.Instance.Hide();

        ImageCropper.Instance.Show(texture, (bool result, Texture originalImage, Texture2D croppedImage) =>
        {
            if (result)
            {
                newProfileInstance.profileImage.texture = croppedImage;

                if (croppedImage != null)
                {
                    newProfileInstance.UploadImage(ConvertImageToBytes(MakeTextureReadable(croppedImage)), croppedImage);
                    croppedTexture = croppedImage;
                }
            }
            else
            {
                croppedTexture = null;
            }
        },
        settings: new ImageCropper.Settings()
        {
            ovalSelection = ovalSelection,
            autoZoomEnabled = autoZoom,
            imageBackground = Color.clear, // transparent background
                selectionMinAspectRatio = minAspectRatio,
            selectionMaxAspectRatio = maxAspectRatio

        },
        croppedImageResizePolicy: (ref int width, ref int height) =>
        {
                //width /= 2;
                //height /= 2;
        });
    }
```

**Comment by yasirkula** [comment]
Oh, I see. You should just move `ImageCropper.Instance.Show` (in other words, all the code) into the callback function of `NativeGallery.GetImageFromGallery`, because the callback function is asynchronous on iOS and in your case, the assignation of the _texture_ variable takes place **after** the ImageCropper.Instance.Show call.

**Comment by andersonaraujodl** [comment]
It worked perfectly! I appreciate your work and your help! Thanks a lot!
