### ISSUE TITLE
Having problem loading texture

### ISSUE THREAD

**Issue by tuvirus** [yasirkula/UnityNativeGallery#44]
Hi, @yasirkula 

i'm using your example code and after picking the image the quad appears with a full color of violet, seems it loaded wrong? And i'm trying to retrieve the texture to pass it to a string64. Not sure what it is or if i'm doing something wrong. What i do is to put it into memory and pass it to string64 but zero results. I believe it is null, that is why load all in a color of violet. A little hand?

**Comment by yasirkula** [comment]
Pink objects usually indicate that their materials have unsupported shaders. You can try changing `Shader.Find( "Legacy Shaders/Diffuse" )` with a supported shader that is always included in the build.

For the string64 issue, are you trying to pass the texture to a WebGL plugin or something like this?

**Comment by tuvirus** [comment]
I worked around it. I created a new sprite using the data of the texture, so the texture was the sprite. Got that solved and i was trying to pass the texture through web services. I had to use a static returning method otherwise it wouldn't work.


Like this:


  private static string getto64(Texture2D texture)
    {

        return "data:image/jpeg;base64," + System.Convert.ToBase64String(texture.EncodeToJPG());
    }


Anyways thanks for replying. I thought you were taking some time off... hehe.. so it took me sometime, hours.

Wasn't sure what was it, but i worked it around, got what i wanted. :D


________________________________

**Comment by yasirkula** [comment]
Glad you resolved the issue on your own!
