### ISSUE TITLE
Undefined symbols for architecture arm64

### ISSUE THREAD

**Issue by ZYSHAQ** [yasirkula/UnityNativeGallery#45]
Hello,
I am using latest Xcode and unity versions and getting the following error:
Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_ALAssetsLibrary", referenced from:
      objc-class-ref in NativeGallery.o
  "_ALAssetsGroupPropertyName", referenced from:
      ___49+[UNativeGallery saveMediaOld:albumName:isImage:]_block_invoke.94 in NativeGallery.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by yasirkula** [comment]
If your **Other Linker Flags** contains `-framework AssetsLibrary`, then this issue shouldn't occur. Nevertheless, you can add AssetsLibrary framework to your project manually get rid of this error.

**Comment by ZYSHAQ** [comment]
Solved! Thank you for your prompt reply!
I tried to follow the automatic setup.

**Comment by DirtyFreddie** [comment]
Hi,

> If your **Other Linker Flags** contains `-framework AssetsLibrary`, then this issue shouldn't occur. Nevertheless, you can add AssetsLibrary framework to your project manually get rid of this error.

I have the same issue and i am not good with xcode. Can you explain to me the steps how to do that?

Thank you

**Comment by yasirkula** [comment]
Does your issue also contain the **very same sentence** `OBJC_CLASS$_ALAssetsLibrary", referenced from: objc-class-ref in NativeGallery.o`? _Undefined symbols_ can be caused by a lot of things, not just ALAssetsLibrary.

**Comment by DirtyFreddie** [comment]
I have fixed it by renaming it in the Unity project.

Thank you

**Comment by codeswapping** [comment]
Even After adding AssetLibrary framework manually, I still face the same error. I am using mac m1 for development. When I export project from unity, this library is not automatically added in other linker flags section.
