### ISSUE TITLE
iOS project build error. 

### ISSUE THREAD

**Issue by dipen-apptrait** [yasirkula/UnityNativeGallery#46]
We are not able to build iOS app and getting linker command error.
![error_1](https://user-images.githubusercontent.com/17145241/44946478-abd44c80-ae1a-11e8-8c01-dbcb793947b0.png)

Thanks.

**Comment by yasirkula** [comment]
Where is __CanOpenSettingsse defined? I couldn't find that typo in my own code.

**Comment by aisUnity** [comment]
Hey @yasirkula  can you please help me out for this error in ios we are using unity 2017.4.29f1 and xcode 10.1 , and open workspace project

"Undefined symbols for architecture arm64:
  "_Unimgpicker_show", referenced from:
      _PickeriOS_Unimgpicker_show_m2706746624 in Bulk_Assembly-CSharp_0.o
     (maybe you meant: _PickeriOS_Unimgpicker_show_m2706746624)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)"


![Screenshot 2019-10-02 at 11 37 45 AM](https://user-images.githubusercontent.com/42369862/66021703-16b5f280-e509-11e9-9bc4-c382e2dda574.png)

**Comment by yasirkula** [comment]
Looks like it is related to this plugin: https://github.com/thedoritos/unimgpicker

**Comment by aisUnity** [comment]
> Looks like it is related to this plugin: https://github.com/thedoritos/unimgpicker

Hello @yasirkula  thanks above isssue is resolve by this link : https://github.com/thedoritos/unimgpicker

well appreciated work 

thanks..
