### ISSUE TITLE
GetImageFromGallery not working

### ISSUE THREAD

**Issue by farz4d** [yasirkula/UnityNativeGallery#56]
GetImageFromGallery is not working in .NET 4.x scripting runtime version. (Unity 2018.3.2f1)

**Comment by farz4d** [comment]
> On which platform did it not work? Are there any error messages in logcat/Xcode console?

I found that it's related to Gradle Proguard Minify option. It works as I disabled this option.

**Comment by yasirkula** [comment]
You don't have to disable Proguard. Just add the following to its filters: `-keep class com.yasirkula.unity.* { *; }`

**Comment by farz4d** [comment]
Thank you for the solution. It's working now.
