### ISSUE TITLE
Video not working in gallery on Android 9.0

### ISSUE THREAD

**Issue by Hitomilras** [yasirkula/UnityNativeGallery#57]
Video moves correctly to gallery on android 9, but not playing (throw playback error). 
Any advice how we can fix it? 

Important, video works properly if not moved by UnityNativeGallery to gallery (if i try run it from file browser it works well).

**Comment by yasirkula** [comment]
Does the video not play when you open it via the native Gallery app (i.e. independent of Unity)? Or does it not play when played via VideoPlayer from within Unity? If it is the latter, can I see your code (or relevant parts of it)?

**Comment by Hitomilras** [comment]
Problem solved. Video don't play by native media player on Android 9.0 after moving to native gallery if it contains '.' (dot) in their name. But it works fine if not moved to native gallery.

**Comment by yasirkula** [comment]
That's a strange issue. I'm not sure if it is caused by NativeGallery, though. Does moving a video with a dot in its name to the gallery from your computer also result in the same issue?
