### ISSUE TITLE
Request: SaveImageToGalllery to pass direct path to the image in the gallery in the callback

### ISSUE THREAD

**Issue by batrand** [yasirkula/UnityNativeGallery#58]
NativeGallery.SaveImageToGallery accepts a callback containing an error if any happens. It would be nice to have access to the path to the file as it is saved in the gallery. Right now to access it, I have modified the private method NativeGallery.GetSavePath() to public, but it would be cleaner, I think, to receive the path as part of the callback itself.

**Comment by yasirkula** [comment]
It is not possible to receive that path on iOS, so I've decided not to expose the path on Android, either.

**Comment by batrand** [comment]
That is unfortunate :(

**Comment by Marcied** [comment]
Thank you that was not me my phone my husband
