### ISSUE TITLE
Failed to pick photo from gallery

### ISSUE THREAD

**Issue by koxta** [yasirkula/UnityNativeGallery#59]
I am trying to pick photo from gallery on android with example code
but i got an error
here is logcat
` NullReferenceException: Object reference not set to an instance of an object
02-22 14:18:37.547 25378 25396 E Unity   :   at NewBehaviourScript+<PickImage>c__AnonStorey1.<>m__0 (System.String path) [0x00000] in <filename unknown>:0
02-22 14:18:37.547 25378 25396 E Unity   :   at NativeGalleryNamespace.NGMediaReceiveCallbackAndroid.MediaReceiveCallback (System.String path) [0x00000] in <filename unknown>:0
02-22 14:18:37.547 25378 25396 E Unity   :   at NativeGalleryNamespace.NGMediaReceiveCallbackAndroid+<OnMediaReceived>c__AnonStorey0.<>m__0 () [0x00000] in <filename unknown>:0
02-22 14:18:37.547 25378 25396 E Unity   :   at NativeGalleryNamespace.NGCallbackHelper.Update () [0x00000] in <filename unknown>:0`

**Comment by yasirkula** [comment]
Can you run the code in Development Mode so that the line numbers will become visible?

**Comment by koxta** [comment]
Oh, I didn't know about development mode, so as it turned out, problem was here
`			quad.transform.position = Camera.main.transform.position + Camera.main.transform.forward * 2.5f;
`
Have no idea why, but adding quad manually solved my problem.
Thank you very much!

**Comment by yasirkula** [comment]
Glad the issue is resolved. For reference, what do you mean by adding the quad manually?

**Comment by koxta** [comment]
I have added quad in scene and referenced it.
`    [SerializeField] private GameObject quad;
     // and added it from inspector
`
instead of 
```
GameObject quad = GameObject.CreatePrimitive( PrimitiveType.Quad );
quad.transform.position = Camera.main.transform.position + Camera.main.transform.forward * 2.5f;
quad.transform.forward = Camera.main.transform.forward;
quad.transform.localScale = new Vector3( 1f, texture.height / (float) texture.width, 1f );
```
