### ISSUE TITLE
Just Open/Launch Gallery without Pick mode

### ISSUE THREAD

**Issue by axel20000** [yasirkula/UnityNativeGallery#60]
I just tested your Plugin today. It's great! I wondered if you can make a new function just to launch the native gallery without pick mode.

I just want to open the gallery after saving my image. Something like:

if ( NativeGallery.SaveImageToGallery(...) == NativeGallery.Permission.Granted ){
    NativeGallery.OpenGallery();
}

Right now I use NativeGallery.GetImageFromGallery() which is fine, but I don't really want user to pick an image but give him a chance to browse his gallery and find the recently saved image by himself.

If possible, it would be great to also give a bool parameter to SaveImageToGallery like:
bool openGalleryAfterSave = true;

NativeGallery.SaveImageToGallery(myBytes, "myfolder", "filename", openGalleryAfterSave);

Maybe to open the Gallery/Photos pointing to the saved image?

Thanks and great work!!

**Comment by yasirkula** [comment]
Thank you for the suggestion. On Android, it should easily be possible with the following code: https://stackoverflow.com/a/23821227/2373034

However, on iOS, there doesn't seem to be a documented way of launching Photos programmatically: https://stackoverflow.com/questions/10547214/is-it-possible-to-launch-redirect-the-user-to-the-native-photo-gallery-applica

I'm not thinking of adding this feature to the plugin, but thank you again for the suggestion!
