### ISSUE TITLE
CheckPermission returning ShouldAsk instead of Denied

### ISSUE THREAD

**Issue by rotter** [yasirkula/UnityNativeGallery#61]
On some Android devices I am getting a weird behavior:

If I deny the permission, then try again and mark "[X] Do not ask again" and deny again, the following times I try the permission again by calling NativeGallery.CheckPermission, instead of returning "NativeGallery.Permission.Denied", it is returning "NativeGallery.Permission.ShouldAsk" (and then I try to ask the permission and it automatically/instantly fires the "denied" callback).

This happens only on some devices. On my personal device (Mi Mix 2S @ Android 9) it doesnt happen (ie, NativeGallery.CheckPermission returns Denied), but on a Galaxy Tab A (@ Android 9 as well) this happens (ie, NativeGallery.CheckPermission returns ShouldAsk).

Any ideas why or how could I fix it?

I noticed the code below on the plugin code on the CheckPermission method, and seems to be related, but Im not sure what it means:
`if( result == Permission.Denied && (Permission) PlayerPrefs.GetInt( "NativeGalleryPermission", (int) Permission.ShouldAsk ) == Permission.ShouldAsk )
			result = Permission.ShouldAsk;`

**Comment by yasirkula** [comment]
Thank you for opening this issue. Does this issue have a negative impact on your app's user experience? I've looked here and there but couldn't really figure out why this function would act like this on some devices.

**Comment by rotter** [comment]
Hi! Thanks for the quick response.

On a "Dont ask again" Deny I show a panel explaining why the permission is needed and a button to open the settings to allow it. But with this problem I cant distinguish if it was a regular Deny or a "Dont ask again" Deny.

If there is no clear fix/bug, I can do a quick hack to check if the callback was called on the same frame as the call, and if so I assume it's a "Dont ask again" Deny scenario.

**Comment by yasirkula** [comment]
The permission result will always be obtained in the same frame because it is synchronous (Unity's main thread waits until a response is received).

Can you put some Debug.Logs here to see what `(Permission) nativeCallback.Result` returns and what is/was `PlayerPrefs.GetInt("NativeGalleryPermission")`'s value:

https://github.com/yasirkula/UnityNativeGallery/blob/477a45f2eaef85466b82b33f441c093ac541563b/Plugins/NativeGallery/NativeGallery.cs#L180-L186

**Comment by rotter** [comment]
I am not using your RequestPermission for some reason (I suspect that it's because you didnt have "readOnly" flag so I had to use an alternate solution).

It seems that the CheckPermission is tied to your RequestPermission, that's why it's nor working then? And the reason it's working on my personal device has nothing to do with the device model, but due to that I probably had a version running in the past in which I called your RequestPermission, so it is already properly initialized.

Could this be the case?

Anyway, here are the logs (for CheckPermission, on the "bugged" device): Pref value is 0, and returned permission is ShouldAsk

**Comment by rotter** [comment]
I migrated from my RequestPermission implementation to your RequestPermission method and now it's working fine :)

So no bug, sorry about creating the issue. I dont know if any change is necessary on the plugin or on the docs, as my situation was very specific, and I dont think more people will implement your CheckPermission without calling your RequestPermission.

**Comment by yasirkula** [comment]
Thanks for the feedback!
