### ISSUE TITLE
Broken in Unity 2019.3 due to PBXProject.GetUnityTargetName() being deprecated

### ISSUE THREAD

**Issue by Arke12917** [yasirkula/UnityNativeGallery#62]
PBXProject.GetUnityTargetName() is deprecated in unity 2019.3. Trying to fix, using Unity's suggested replacement results in missing arm64 symbols when compiling in Xcode.

**Comment by yosun** [comment]
I'm able to get this to work in Unity 2019.3 ... are you using the latest one?

**Comment by Arke12917** [comment]
Apologies, I can't get it to work as it's an error with unity and not an error with the package itself, native gallery was mentioned in the error log so I assumed as such. https://issuetracker.unity3d.com/issues/ios-uaal-empty-project-with-script-debugging-fails-to-build-via-xcode-because-its-missing-symbols-during-linking
