### ISSUE TITLE
UnauthorizedAccessException on iOS

### ISSUE THREAD

**Issue by MaxTyT** [yasirkula/UnityNativeGallery#63]
Hi, 
This asset works perfectly on Android, but not on iOS. Please help me to make it work on iOS.

I attach my code below. I don't even get a Log call with permission, I only get this error and nothing else:

> UnauthorizedAccessException: Access to the path "/mnt" is denied.
> at System.IO.Directory.CreateDirectoriesInternal (System.String path) [0x00000] in <filename unknown>:0 
> at System.IO.Directory.CreateDirectoriesInternal (System.String path) [0x00000] in <filename unknown>:0 
> at System.IO.Directory.CreateDirectoriesInternal (System.String path) [0x00000] in <filename unknown>:0 
> at System.IO.Directory.CreateDirectoriesInternal (System.String path) [0x00000] in <filename unknown>:0 
> at proCore.MakeScreenShot (.....

I did everything from readme and checked it twice in XCode.
I use Unity 5.6.7

> NativeGallery.Permission perm = NativeGallery.CheckPermission();
> Debug.Log(perm.ToString());
> if(perm == NativeGallery.Permission.Granted) NativeGallery.SaveImageToGallery(bytes, "RROnline", scrName+scrExtension);
> else if(perm == NativeGallery.Permission.ShouldAsk)
> {
> 	perm = NativeGallery.RequestPermission();
> 	Debug.Log(perm.ToString());
> 	if(perm == NativeGallery.Permission.Granted) NativeGallery.SaveImageToGallery(bytes, "RROnline", scrName+scrExtension);
> }
> else if(perm == NativeGallery.Permission.Denied && NativeGallery.CanOpenSettings()) NativeGallery.OpenSettings();

**Comment by yasirkula** [comment]
Your code looks very good, but I am guessing/hoping that scrName is something simple like "My Image". I have never seen /mnt path on iOS before, it is often used on Android.

Does the example code on this repo yield the same error?

**Comment by MaxTyT** [comment]
I created a clean project and your example code works just fine.
In my app I don't even see photo permission in app setting, although I created fields in info.plist.
Will give it one more try...

**Comment by MaxTyT** [comment]
So the bug was actually in proScreenshot, which I use to take screenshots. It tried to create a folder :-D
Thank you for your brilliant asset and support.
