### ISSUE TITLE
Freeze on NativeGallery.RequestPermission();

### ISSUE THREAD

**Issue by nyudeb** [yasirkula/UnityNativeGallery#64]
Hello,

I work on Unity 2019.1.4 for android and when I try to RequestPermission(), I got the window and press yes to accept and the application freeze... It work but it freeze. (I just need to leave the app and come again on it... and it work)

It was working perfectly on Unity 2018.x. 

Is there something I could do to avoid this unlimited freeze ?

**Comment by yasirkula** [comment]
I'm unable to tell, I didn't get the chance to test the plugin on Unity 2019 yet.

**Comment by pitaslayer** [comment]
Having the same issue, too!

**Comment by yasirkula** [comment]
It has been quite some time but I might've resolved the issue. Can you import [this unitypackage](https://github.com/yasirkula/UnityNativeGallery/files/3389831/NativeGallery.zip)
 to your project (unzip first) and try again? If possible, trying it on both Unity 2019 and 2018 (or an older version) would be awesome!

**Comment by Jur-Wind** [comment]
I got the same problem Unity 2019.1.8f1.
> Can you import this unitypackage to your project (unzip first) and try again?
Downloaded and unzipped "this unitypackage" but i cannot import it?

**Comment by yasirkula** [comment]
Does Assets-Import Package-Custom Package not work?

**Comment by Jur-Wind** [comment]
Thanks for your amazing quick reply! The extracted zip contains 13 folders with md5 hashes as names. I cannot import those via Assets-Import Package-Custom Package:(

**Comment by yasirkula** [comment]
Don't unzip unitypackage. Just extract it from NativeGallery.zip and then import NativeGallery.unitypackage to your project.

**Comment by Jur-Wind** [comment]
My fault it extracts the zip and .unitypackage automatically.. Imported the NativeGallery.unitypackage from your post above but still no go:(

**Comment by yasirkula** [comment]
I was able to test that version on 2019.1.8f1 and 5.6.2f1 in two steps each:

- WRITE_EXTERNAL_STORAGE is defined in AndroidManifest (via `Write Permission=External (SDCard)` in Player Settings)
- WRITE_EXTERNAL_STORAGE is not defined in AndroidManifest

The app never froze indefinitely for me. Even when the permissions is not defined, it froze for ~3 seconds and then continued as usual. Did it freeze indefinitely for you? On which Unity version may I ask? Did you use Mono or IL2CPP? Gradle or Internal? Did you tweak some other settings in Player Settings that might affect the plugin?

The Denied permission issue might be related to the Denied permission being cached in your first attempt with WRITE_EXTERNAL_STORAGE not defined in AndroidManifest. You can reset the cache by uninstalling the app and then reinstalling it. Does reinstalling the app with WRITE_EXTERNAL_STORAGE defined in AndroidManifest solve the permission issue?

**Comment by adoucet52** [comment]
I'm also experiencing the freeze using Unity 2019.1.10f1 with IL2CPP and building an app bundle. WRITE_EXTERNAL_STORAGE is defined in the manifest. The freeze was indefinite and I didn't see any errors in the logcat console.

**Comment by Jur-Wind** [comment]
> I was able to test that version on 2019.1.8f1 and 5.6.2f1 in two steps each:
> 
> * WRITE_EXTERNAL_STORAGE is defined in AndroidManifest (via `Write Permission=External (SDCard)` in Player Settings)
> * WRITE_EXTERNAL_STORAGE is not defined in AndroidManifest
> 
> The app never froze indefinitely for me. Even when the permissions is not defined, it froze for ~3 seconds and then continued as usual. Did it freeze indefinitely for you? On which Unity version may I ask? Did you use Mono or IL2CPP? Gradle or Internal? Did you tweak some other settings in Player Settings that might affect the plugin?
> 
> The Denied permission issue might be related to the Denied permission being cached in your first attempt with WRITE_EXTERNAL_STORAGE not defined in AndroidManifest. You can reset the cache by uninstalling the app and then reinstalling it. Does reinstalling the app with WRITE_EXTERNAL_STORAGE defined in AndroidManifest solve the permission issue?

Thanks for your reply i will try testing this first thing tomorrow to be sure.

> I'm also experiencing the freeze using Unity 2019.1.10f1 with IL2CPP and building an app bundle. WRITE_EXTERNAL_STORAGE is defined in the manifest. The freeze was indefinite and I didn't see any errors in the logcat console.

Same here App Bundle and IL2CPP

**Comment by yasirkula** [comment]
@adoucet52 Did you use the unitypackage I've provided here: 

> It has been quite some time but I might've resolved the issue. Can you import [this unitypackage](https://github.com/yasirkula/UnityNativeGallery/files/3389831/NativeGallery.zip)
> to your project (unzip first) and try again? If possible, trying it on both Unity 2019 and 2018 (or an older version) would be awesome!

@Jur-Wind Some users (including myself) reported that this unitypackage has resolved the issue. I'd like to know about your test results, as well.

**Comment by yasirkula** [comment]
https://github.com/yasirkula/UnityNativeGallery/commit/e6683a2c2c751551bddb60b4c7def71744cafd72 should resolve this issue, please give it a try.

**Comment by Jur-Wind** [comment]
I finally fixed our problem. First your update package did work in a new project. In our project we use AdMob with mediation and the mediation adapters changed the final AndroidManifest.xml with:

> <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" android:maxSdkVersion="18" />

In this case the app froze and the permission dialog did not appear so i had change our AndroidManifest.xml to:

> <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" tool:remove="android:maxSdkVersion" />

Thanks for all your help!

**Comment by adoucet52** [comment]
Whoops, you were right. The package you linked has indeed fixed the freeze.

**Comment by yasirkula** [comment]
Thanks for the feedback, glad the issue is resolved for everyone 😸
