### ISSUE TITLE
Some desired folders not listed on Android

### ISSUE THREAD

**Issue by xinaesthete** [yasirkula/UnityNativeGallery#65]
Context: I'm trying to make an app that can pick images from other apps; in particular, 360 images from devices like Ricoh Thetas, Insta360 (although that's not an important detail here).

The problem I have is that on Android, the "RICOH THETA" folder that the app for that device stores its images in doesn't appear in the picker (annoyingly not an issue I can reproduce locally).  The project previously used VoxelBuster's library, which did locate the relevant folder but I have some other issues with it and would much prefer to use this.

Looking at the Java source, I guess one possibility is that a different Uri argument for the Intent.ACTION_PICK might help.  I made a fork of this repository so I could tinker, and got the Java code into an AndroidStudio project but haven't yet worked out how to configure it to output a replacement for the jar file.

**Comment by yasirkula** [comment]
Inside build.gradle in Android Studio, change `apply plugin: 'com.android.application'` to `apply plugin: 'com.android.library'` and delete the `applicationId` line if exists. After building your project, it will output an .aar file which will contain the .jar file. I'd recommend you to open it with something like Winrar and delete BuildConfig.class. Then feel free to replace NativeGallery's jar file.

**Comment by xinaesthete** [comment]
Excellent, thanks for the quick feedback.

**Comment by xinaesthete** [comment]
It looks likely that in my case using `Intent.GET_CONTENT` in place of `Intent.ACTION_PICK` might get the right result; I'll have to wait for feedback.  Not an ideal situation (the way you had it seems to be more recommended practice); I suppose it may be worth exposing an extra option to allow the user to choose which kind of intent to use.  Not sure how many people this is likely to effect.

**Comment by yasirkula** [comment]
Yes, using ACTION_GET_CONTENT intent will enable you to pick image from external sources, as well. The code change should be trivial. Actually, it might be as simple as replacing `intent = new Intent( Intent.ACTION_PICK, MediaStore.Images.Media.EXTERNAL_CONTENT_URI );` with this:

```java
intent = new Intent( Intent.ACTION_GET_CONTENT );
intent.addCategory( Intent.CATEGORY_OPENABLE );
```

**Comment by xinaesthete** [comment]
Yes, that's what I've done locally and feedback from tester is good, I was thinking it might be an idea to go a little bit further to expose that as an option from the c# side.

**Comment by yasirkula** [comment]
With the latest release, I've added a flag to the native code to prefer ACTION_GET_CONTENT over ACTION_PICK. You can use the following code enable that flag:

```csharp
using( AndroidJavaClass ajc = new AndroidJavaClass( "com.yasirkula.unity.NativeGalleryMediaPickerFragment" ) )
	ajc.SetStatic<bool>( "preferGetContent", true );
```
