### ISSUE TITLE
GetImageFromGallery path

### ISSUE THREAD

**Issue by TaynaCT** [yasirkula/UnityNativeGallery#67]
Can you explain better how the function  NativeGallery.GetImageFromGallery works? I mean, if I want to pick several images from a specific gallery path folder, how should a pass the path to the folder I want?  Cuz, on my app the user can take a picture the when the user save it, it goes to the app folder on Gallery/Photos/AppAlbum. But then I want to display those images on the app.

**Comment by yasirkula** [comment]
It is not possible to filter the listed images in GetImageFromGallery. It lists all the images in the Gallery.

**Comment by TaynaCT** [comment]
Found a way based on this:

[https://forum.unity.com/threads/native-gallery-for-android-ios-open-source.519619/](url)

Thanks
