### ISSUE TITLE
Null Reference Exception when picking image from Gallery on an Android device

### ISSUE THREAD

**Issue by biniHash** [yasirkula/UnityNativeGallery#68]
Hi, when picking an image from the gallery gives this error, as shown in the attached image .

![Screenshot_20190716-140249](https://user-images.githubusercontent.com/45932005/61278869-9b2e8a00-a7d2-11e9-8dcb-e09671401231.jpg)

I am just modifying the example code provided on the Git Hub Readme to pick an image from the gallery and set it on a UI Image. The code is as: 

```
private void PickImage( int maxSize )
	{
		NativeGallery.Permission permission = NativeGallery.GetImageFromGallery( ( path ) =>
		{
			Debug.Log( "Image path: " + path );
			if( path != null )
			{
				// Create Texture from selected image
				Texture2D pickedTexture = NativeGallery.LoadImageAtPath( path, maxSize );
				if( pickedTexture == null )
				{
					Debug.LogError( "Couldn't load texture from " + path );
					return;
				}
				else
				{
					Debug.Log("Texture obtained succesfully!");
				}

				// Assign the obtained texture to image
				rawImagePicked.GetComponent<RawImage>().texture = pickedTexture;

			}
		}, "Select any image", "image/*", maxSize );

		Debug.Log("Permission result: " + permission );
	}
```

**Comment by yasirkula** [comment]
Is it possible that either `rawImagePicked` or `rawImagePicked.GetComponent<RawImage>()` is null? Which line is **NativeImagePicker.cs:56**?

**Comment by biniHash** [comment]
Yes, that was what was causing it. The rawImagePicked's reference was not set. (I had set it, I don't know how it's reference was reset...) Sorry for the hassle 😓 , and Thank you for the quick response !
