### ISSUE TITLE
File Metadata

### ISSUE THREAD

**Issue by unbounded26** [yasirkula/UnityNativeGallery#7]
Kindly can you make 
- a function which returns the file (image & video) size
- a function to return image width and height

Currently, it is just returning the file path, that's good. It would be much better if you return above-mentioned data as Metadata in the callback when picked/selected an image/video. 

Looking forward to your help! :)

**Comment by yasirkula** [comment]
Retrieving image dimensions from the plugin might be possible, yes. But I'd give it a low priority. Instead, at least for now, you can use the following functions:

```csharp
public long GetFileSize( string path )
{
	if( path == null )
		return 0L;
		
	return new System.IO.FileInfo( path ).Length;
}

public Vector2 GetImageDimensions( string path )
{
	if( path == null )
		return Vector2.zero;
		
	Texture2D texture = new Texture2D( 2, 2 );
	texture.LoadImage( File.ReadAllBytes( path ) );
	
	Vector2 result = new Vector2( texture.width, texture.height );
	Object.Destroy( texture );
	
	return result;
}
```

**Comment by unbounded26** [comment]
`GetImageDimensions ` it will always return the `new Texture2D( 2, 2 );` means 2x2 (width: 2, height:2 )

**Comment by yasirkula** [comment]
Hmm, on which device/OS did you test it?

**Comment by yasirkula** [comment]
I just updated the iOS plugin. If you had the 2x2 issue on iOS, you may want to give it another try.

**Comment by unbounded26** [comment]
Thanks for the iOS update! Thumbs up!
But for now, I'm testing on Android

**Comment by yasirkula** [comment]
That code worked for me on a real Galaxy S3 and a Nexus 5 (Android M) emulator. Curious why it doesn't work for you. Are you able to use the texture you generate from the returned path? Is the image loaded correctly?

**Comment by Edorne** [comment]
I have a similar problem with the size of the texture with the simple code below on IOS Iphone X: it return the size (2,2)... even if the texture contains the photo ! I don't understand why.. could you help me ? 
Thanks a lot !

		Texture2D texture = new Texture2D( 2, 2 );
		NativeGallery.Permission permission = NativeGallery.GetImageFromGallery( ( path ) =>
			{
				if( path != null )
				{
					// Create Texture from selected image
					texture.LoadImage( File.ReadAllBytes( path ) );
				}
			}, "Select a PNG image", "image/png" );

Debug.Log ("Texture SCENE Size: W " + texture.width.ToString() + " H" + texture.height.ToString());

**Comment by yasirkula** [comment]
Make sure to call texture.width and texture.height after reading the texture from the file (texture.LoadImage). The following code should output the correct size:

```
Texture2D texture = new Texture2D( 2, 2 );
NativeGallery.Permission permission = NativeGallery.GetImageFromGallery( ( path ) =>
	{
		if( path != null )
		{
			// Create Texture from selected image
			texture.LoadImage( File.ReadAllBytes( path ) );
			Debug.Log ("Texture SCENE Size: W " + texture.width.ToString() + " H" + texture.height.ToString());
		}
	}, "Select a PNG image", "image/png" );
```

**Comment by yasirkula** [comment]
I've added `NativeGallery.GetImageProperties( string imagePath )` function with the latest commit. You may wanna check it out.

**Comment by Edorne** [comment]
Thanks for NativeGallery.GetImageProperties ... but i don't know how to use it: i tried the code below and it stops the execution on IOS 11.3:

		Texture2D texture = new Texture2D( 2, 2 );
		NativeGallery.ImageProperties imageProp = new NativeGallery.ImageProperties ();
		NativeGallery.Permission permission = NativeGallery.GetImageFromGallery( ( path ) =>
			{
				if( path != null )
				{
					// Create Texture from selected image
					texture.LoadImage( File.ReadAllBytes( path ) );
					imageProp = NativeGallery.GetImageProperties (path);
				}
			}, "Select a PNG image", "image/png" );

.. I also tried to save the path in the if brakets and use it after but the saved path seems to be avoid...

		imageProp = NativeGallery.GetImageProperties (pathsave);

Could you help me to use "NativeGallery.GetImageProperties" ?

Thanks a lot !

**Comment by yasirkula** [comment]
Do you get an error message on Xcode?

**Comment by Edorne** [comment]
Well, I tried it again to get the XCode message... and now it doesn't crash, i dont know why but it's a good step ! 
But now, the imageProp.width & .height is (0,0).... even if i can see my photo... 
So do you have an idea to help me ?

Thanks

**Comment by yasirkula** [comment]
Hmm, I shall test it on an emulator before making any guesses.

**Comment by yasirkula** [comment]
On iPhone 8 Plus (iOS 11.2) emulator, everything works fine. Are you sure that you are accessing the image properties after the GetImageProperties call, e.g:

```csharp
NativeGallery.Permission permission = NativeGallery.GetImageFromGallery( ( path ) =>
		{
			if( path != null )
			{
				// Create Texture from selected image
				texture.LoadImage( File.ReadAllBytes( path ) );
				imageProp = NativeGallery.GetImageProperties (path);
				Debug.Log( imageProp.width + " " + imageProp.height );
			}
		}, "Select a PNG image", "image/png" );
```

**Comment by Edorne** [comment]
That's Ok  ! There was a delay between the call of GetImageProperties and the response. Now, i put all my functions in the "NativeGalmlery.Permission" brackets and  It works well ! 
Thank you very much for your good tool & your reactivity !

**Comment by yasirkula** [comment]
You are welcome!
