### ISSUE TITLE
Default App Selection

### ISSUE THREAD

**Issue by Legacycz** [yasirkula/UnityNativeGallery#70]
Hello,
I would like to select the used app to be always opened when I pick a media from gallery. Unfortunately I can't see the button which usually does it in some apps.

Is there a way I can do that with this plugin?

Thanks for your responses.

**Comment by yasirkula** [comment]
Here, Intent.createChooser shows the app selection dialog if a default app is not selected: https://github.com/yasirkula/UnityNativeGallery/blob/ad14dd4d8d44f3c3ee60a5f649b7faa0b38c804d/JAR%20Source/NativeGalleryMediaPickerFragment.java#L87

You've probably selected a default app to select the images with :(

**Comment by Legacycz** [comment]
Unfortunetely even if I select an app, the dialog still appears. I want to see the dialog only the first time I pick the image/video. Is it possible?

**Comment by yasirkula** [comment]
I see. Looking at [this topic](https://stackoverflow.com/a/12781183/2373034), apparently Intent.createChooser should be omitted to achieve the desired effect. You'll have to change the line I've posted above as follows, rebuild the project and then replace the NativeGallery.jar file with the updated one: `startActivityForResult( intent, MEDIA_REQUEST_CODE );`. There should be articles about creating Android plugins for Unity, you can check them out if you have no such experience.

**Comment by Legacycz** [comment]
That did it! Thanks a lot :).
