### ISSUE TITLE
Android 10 support

### ISSUE THREAD

**Issue by hippogamesunity** [yasirkula/UnityNativeGallery#71]
Hi! I know this question may not relate to your plugin, but I'm getting an error when accessing to DCIM on Android 10 (access denied).
My setup:
- Unity 2019.2.4 + SDK Level 29 + Android 10 (AVD)
- This happens on real devices (as reported by many users)
- This does't happen on Android 9 and older
- Storage permissions are requested and granted

As I see some security changes where made in Android 10, but looks like it should work when permission is requested: https://developer.android.com/training/data-storage/files/external-scoped

**Comment by hippogamesunity** [comment]
Also I've noticed that you have storage access issues with x86 emulator (in another thread). Unfortunately, I can't test it on a real device, and ARM emulation is not available for API 29.

**Comment by hippogamesunity** [comment]
This also may be related: https://stackoverflow.com/questions/57449242/android-q-10-ask-permission-to-get-access-all-storage-scoped-storage

**Comment by hippogamesunity** [comment]
https://www.androidcentral.com/what-scoped-storage-android-q

**Comment by hippogamesunity** [comment]
I've also created a thread on Unity forum: https://forum.unity.com/threads/android-10-and-scoped-storage-missed-features-in-unity-2019.749333/

**Comment by hippogamesunity** [comment]
I was able to check this code on a real device and it doesn't work:
> NativeGallery.SaveImageToGallery(new Texture2D(16, 16), "Pixel Studio", "My img {0}.png");

**Comment by yasirkula** [comment]
I'll see what I can do. In the meantime, you can check out this workaround: https://forum.unity.com/threads/native-gallery-for-android-ios-open-source.519619/page-11#post-4962206

**Comment by hippogamesunity** [comment]
Many thanks, I can confirm I works! I've spent a whole day on reading forums and decided to force my users with Android 10 to use internal app folder (insted of DCIM) as a templorary solution.

Seems making your own File Browser UI is a bad idea since Android 10. But if we still want to work with files directly it seems ACTION_OPEN_DOCUMENT_TREE is what we need. After creating such intent (I believe) we can access all files directlry from Unity/C# stack (using Syste.IO.File).

![image](https://user-images.githubusercontent.com/7318172/65455077-21a8bd00-de4f-11e9-8cd7-58b098d252b3.png)
https://developer.android.com/guide/topics/providers/document-provider

**Comment by yasirkula** [comment]
I've resolved the issue by using the recommended MediaStore approach and will push an update after verifying the plugin on iOS (made some changes there, as well).

**Comment by yasirkula** [comment]
Fixed in https://github.com/yasirkula/UnityNativeGallery/commit/ba3fbf4f4c2840d6ac2c1e1145ca14b7834660c0

**Comment by hippogamesunity** [comment]
Great, I will check this in next app update. Thanks!

**Comment by yasirkula** [comment]
Just updated my SimpleFileBrowser plugin, as well! https://github.com/yasirkula/UnitySimpleFileBrowser
