### ISSUE TITLE
Load Image

### ISSUE THREAD

**Issue by BryanJ-97** [yasirkula/UnityNativeGallery#72]
Hello, I am trying to upload an image from the android gallery to be able to send it to the Vuforia database and use it as a bookmark.
If the image loads me from the gallery, I verify it by presenting it in the Quad as the example, the problem is that when it comes to executing this line
Texture2D varTex = new Texture2D(varTexture.width, varTexture.height, TextureFormat.RGB24, false); it does not continue executing the rest of the code and I have no idea why that happens.
PSDT: I know that it does not advance from there because after each method I present in the prototype of the application messages to verify the execution.

public class CBLogic_VuforiaCLoud : MonoBehaviour
{
    CBLogic_PostNewTrackableRequest varModel = new CBLogic_PostNewTrackableRequest();
    public InputField varInput_TargetName;
    public Texture2D varTexture;
    public string varpath;
    public byte[] varImage;
    public Text statusText;
    private string ACCESS_KEY = "sadsdsd";
    private string SECRET_KEY = "dsaaddas";
    private string URL = @"https://vws.vuforia.com";//@"<a href="https://vws.vuforia.com";//">https://vws.vuforia.com";</a>
    private string varTargetName; // must change when upload another Image Target, avoid same as exist Image on cloud
    
    private byte[] requestBytesArray;

    public void CBLogic_MethodCallPostTarget()
    {
        CBLogic_MethodPostNewTarget();
    }
    
    void CBLogic_MethodPostNewTarget()
    {
          
        AddStatusText("Cargando Galeria");
        PickImage();
    }
    
    public void PickImage()
        {
        
            NativeGallery.Permission permission = NativeGallery.GetImageFromGallery((path) =>
            {
                if (path != null)
                {
                    AddStatusText("Image path: " + path);
                    CreateMarker(path);
                    
                }
            }, "Select a PNG image");

        
        }
    private List<string> messages = new List<string>();
    public void AddStatusText(string text)
    {
        if (messages.Count == 5)
        {
            messages.RemoveAt(0);
        }
        messages.Add(text);
        string txt = "";
        foreach (string s in messages)
        {
            txt += "\n" + s;
        }
        statusText.text = txt;
    }
    public void CreateMarker(string path){
        AddStatusText("Creando marcador");
        varTexture = NativeGallery.LoadImageAtPath(path, 512);
        Texture2D varTex = new Texture2D(varTexture.width, varTexture.height, TextureFormat.RGB24, false);
        varTex.SetPixels(varTexture.GetPixels());
        varTex.Apply();
        varTargetName = varInput_TargetName.text;
        varImage = varTex.EncodeToPNG();
        varModel.varImage = System.Convert.ToBase64String(varImage);
        string varMetadataStr = "Ejemplo";//May use for key,name...in game
        byte[] varMetadata = System.Text.ASCIIEncoding.ASCII.GetBytes(varMetadataStr);
        varModel.varName = varTargetName;
        varModel.varWidth = 64.0f;             
        varModel.varApplication_metadata = System.Convert.ToBase64String(varMetadata);
        AddStatusText("Preparado....");
        StartCoroutine(SendTarget());
    }
    public IEnumerator SendTarget()
    {
        AddStatusText("Enviando....");
        string REQUEST_PATH = "/targets";
        string varServiceURI = URL + REQUEST_PATH;
        string varHttpAction = "POST";
        string varContentType = "application/json";
        string varDate = string.Format("{0:r}", DateTime.Now.ToUniversalTime());
        string varRequestBody = JsonUtility.ToJson(varModel);

        WWWForm varForm = new WWWForm();

        var varHeaders = varForm.headers;
        byte[] rawData = varForm.data;
        varHeaders["host"] = URL;
        varHeaders["date"] = varDate;
        varHeaders["Content-Type"] = varContentType;

        HttpWebRequest varHttpWReq = (HttpWebRequest)HttpWebRequest.Create(varServiceURI);

        MD5 varMd5 = MD5.Create();
        var varContentMd5Bytes = varMd5.ComputeHash(System.Text.Encoding.ASCII.GetBytes(varRequestBody));
        System.Text.StringBuilder varSb = new System.Text.StringBuilder();
        for (int i = 0; i < varContentMd5Bytes.Length; i++)
        {
            varSb.Append(varContentMd5Bytes[i].ToString("x2"));
        }

        string varContentMD5 = varSb.ToString();

        string varStringToSign = string.Format("{0}\n{1}\n{2}\n{3}\n{4}", varHttpAction, varContentMD5, varContentType, varDate, REQUEST_PATH);

        HMACSHA1 varSha1 = new HMACSHA1(System.Text.Encoding.ASCII.GetBytes(SECRET_KEY));
        byte[] varSha1Bytes = System.Text.Encoding.ASCII.GetBytes(varStringToSign);
        MemoryStream varStream = new MemoryStream(varSha1Bytes);
        byte[] varSha1Hash = varSha1.ComputeHash(varStream);
        string varSignature = System.Convert.ToBase64String(varSha1Hash);

        varHeaders["Authorization"] = string.Format("VWS {0}:{1}", ACCESS_KEY, varSignature);

        Debug.Log("<color=green>Signature: " + varSignature + "</color>");

        WWW varRequest = new WWW(varServiceURI, System.Text.Encoding.UTF8.GetBytes(JsonUtility.ToJson(varModel)), varHeaders);

        AddStatusText("Hecho");
        yield return varRequest;
        if (varRequest.error != null)
        {
            AddStatusText("request error: " + varRequest.error);
        }
        else
        {
            AddStatusText("request success");
            AddStatusText("returned data" + varRequest.text);
        }
    }
}

public class CBLogic_PostNewTrackableRequest
{
    public string varName;
    public float varWidth;
    public string varImage;
    public string varApplication_metadata;
}

**Comment by yasirkula** [comment]
Can you try making the following change: `varTexture = NativeGallery.LoadImageAtPath(path, 512, false);`. By default, varTexture is marked as non-readable but the 3rd _false_ parameter disables this optimization.

You can actually directly read the bytes of the picked image via File.ReadAllBytes but I'm guessing that you are trying to create a smaller version of the picked image (512px. max.), am I right?

**Comment by BryanJ-97** [comment]
Thank you so much, it worked perfectly

**Comment by yasirkula** [comment]
Why don't you simply use File.ReadAllBytes, though? You may be wasting resources for no reason here.

**Comment by BryanJ-97** [comment]
Thank you for your suggestion, I will use it to save resources
