### ISSUE TITLE
Can't using path video on IOS 13

### ISSUE THREAD

**Issue by taipvnb** [yasirkula/UnityNativeGallery#73]
In iOS 13, picking video from gallary, it return wrongly path

What does actually happen?
Returns a invalid non proprietary FILE_URI with no access to work with, like:
file:///private/var/mobile/Containers/Data/PluginKitPlugin/43792FA5-A8F8-4ECA-8CCE-0C5877088858/tmp/trim.7F9B8FC4-3307-4452-9F96-46A5D9A9DDD5.MOV

What is expected to happen?
Return a valid proprietary FILE_URI url to work with it (for upload to server, for example)
like: file:///var/mobile/Containers/Data/Application/98D7C3AE-A24F-46CE-A3B4-CF03B26355BE/tmp/video.mp4

The problem was the image picker delegate passed the file's url to another class that then handled copying the file. This has worked fine for several years in our application but with iOS 13, once the image picker delegate goes away, the url immediately becomes invalid.

**Comment by yasirkula** [comment]
I see. I'll try to come up with a solution soon. For reference, here's a SO entry: https://stackoverflow.com/questions/57798968/didfinishpickingmediawithinfo-returns-different-url-in-ios-13

**Comment by taipvnb** [comment]
Yes, please help me

**Comment by HdSonu** [comment]
Same here , not able to save video in ios 13 , 
getting following error 
Error creating asset: Error Domain=PHPhotosErrorDomain Code=-1 "(null)"

**Comment by taavetmaask** [comment]
We're having the same issue. I hope the issue will be resolved soon. :)

**Comment by yasirkula** [comment]
I've created a fix by editing the code on Notepad++ but couldn't yet compile and test it since the only Mac I have access to is at work and it was a busy day today. I'll update the plugin here as soon as I verify that it works.

**Comment by yasirkula** [comment]
Fixed in https://github.com/yasirkula/UnityNativeGallery/commit/ba3fbf4f4c2840d6ac2c1e1145ca14b7834660c0

**Comment by taipvnb** [comment]
@yasirkula yes, I tried to use it and can upload video on ios 13.
Thanks for support me.
