### ISSUE TITLE
Unable to open Android Gallery

### ISSUE THREAD

**Issue by Rudolph-C** [yasirkula/UnityNativeGallery#74]
Hi, i'm facing a problem with android. When trying to open the android gallery we don't get the option to open the gallery, nothing happens. The app asks for the permission and it is accepted/granted. It was working before updating the plugins and libraries then it stoped.

 >-Included in proguard -keep class com.yasirkula.unity.* { *; } 
 >-Write Permission to External (SDCard) in Player Settings 
 >-Min Api is 19
 >-Unity 2018.3.9f1

Any help in solving the issue will be grateful

**Comment by yasirkula** [comment]
Which Android version does your test device have? You mentioned an update that broke the plugin, can you clarify what this update was?

**Comment by Rudolph-C** [comment]
We are using android 6.0.1 API 23 samsung j5, also tested on android emulator on multiple APIs.
The updated libraries include android support libraries (the latest androidX), ad network libraries, and your UnityNativeGallery, also from  `'armeabi-v7a', 'x86'`  to ` 'armeabi-v7a', 'arm64-v8a', 'x86'`

**Comment by yasirkula** [comment]
Can you please check out logcat for any meaningful error messages? Does NativeGallery work on an empty Unity project? If so, how about after adding ARM64 to your target architectures? Also please check out this post: https://forum.unity.com/threads/native-gallery-for-android-ios-open-source.519619/page-11#post-4962206

**Comment by Rudolph-C** [comment]
ARM64 is already a target architectures, adding `android:requestLegacyExternalStorage="true"` didn't change. 
In the logcat :
`10-04 13:53:31.023 10887-10919/com.slimesmash.android I/Unity: Permission result: Denied
    UnityEngine.Logger:Log(LogType, Object)
    PuttyController:MKKOAALAAMB(Int32)
    PuttyController:NAMPMCCJGCF(String, Object, Object[])
    <>c__DisplayClass117_0:NIMOBBELMDA()
    UnityEngine.Events.UnityEvent:Invoke()
    AudioButton:OnPointerClick(PointerEventData)
    UnityEngine.EventSystems.ExecuteEvents:Execute(GameObject, BaseEventData, EventFunction1)
    UnityEngine.EventSystems.StandaloneInputModule:ProcessTouchPress(PointerEventData, Boolean, Boolean)
    UnityEngine.EventSystems.StandaloneInputModule:ProcessTouchEvents()
    UnityEngine.EventSystems.StandaloneInputModule:Process()
    (Filename: ./Runtime/Export/Debug.bindings.h Line: 45)
10-04 13:53:31.033 10887-10887/com.slimesmash.android I/Unity: onResume`
 though the permission is being asked and granted from the app (also tried manually from application settings) but it still is denied?

**Comment by yasirkula** [comment]
Out of curiosity, does NativeGallery work on an empty Unity project?

**Comment by Rudolph-C** [comment]
NativeGallery works on an empty project.
  
```
 {
            NativeGallery.Permission permission = NativeGallery.GetImageFromGallery((path) =>
            {
                Debug.Log("Image path: " + path); 
            }, "Select a PNG image", "image/*", 1024);
            Debug.Log("Permission result: " + permission); 
        
   }
```
same is used in our app:

 ```
NativeGallery.Permission permission = NativeGallery.GetImageFromGallery((path) =>
        {
            
            if (path != null)
            {
             // code ...
             Debug.Log("Image path: " + path);
            }
        }, "Select a PNG image", "image/*", maxSize);
        Debug.Log("Permission result: " + permission); 
```
Uninstalling and reinstalling do not change the outcome.

**Comment by yasirkula** [comment]
Can you check **PROJECT_PATH/Temp/StagingArea/AndroidManifest.xml** after building your Unity project and verify that it contains WRITE_EXTERNAL_STORAGE permission? Maybe a plugin you are using is preventing that permission from being added to the AndroidManifest somehow? If it is not added to AndroidManifest automatically, then try adding it manually to **Assets/Plugins/Android/AndroidManifest.xml** inside the `<manifest>...</manifest>` tags: `<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />`

**Comment by Rudolph-C** [comment]
Im checking manually the android build for the permission `WRITE_EXTERNAL_STORAGE` and its included in the main manifest (not the plugins). For extra measure added `READ_EXTERNAL_STORAGE`. Also added the proguard rule `-keep class com.yasirkula.unity.* { *; }` in the proguard-unity.txt. In the previous comment you mentioned `android:requestLegacyExternalStorage="true"` in the application tag in the manifest, thats also included. 
Unity player settings:
-Target Architectures ARMv7, ARM64, x86
-Install Location Prefer External
-Write Permission External(SDCard)
Also tried twice to delete the NativeGallery files from the plugin folder and let unity resolve the dependancies.

**Comment by Rudolph-C** [comment]
I have figured what the problem was: When i attempted to delete this plugin from my assets and then reimport it from the assets store of unity. Apparently unity didn't properly delete the files or update them at all. The solution was that i manually copied the `Plugins/NativeGallery/NativeGallery.cs` file from github.com and replaced it in my project.
Im not sure why this happened and how is it affecting the other plugins i use !? 
Any other file i should make sure to replace?
Thank you for your support and time greatly appreciated.

**Comment by yasirkula** [comment]
I've just updated the plugin. I'd recommend you to delete the Plugins/NativeGallery directory and import the latest version from GitHub, then all should be fine: https://github.com/yasirkula/UnityNativeGallery/releases
