### ISSUE TITLE
can't use in unity 2019.2.8f1

### ISSUE THREAD

**Issue by zero16832** [yasirkula/UnityNativeGallery#75]
can't use in unity 2019.2.8f1,android system

**Comment by yasirkula** [comment]
Does a build error occur or a runtime exception is thrown when calling a NativeGallery function? In either case, the full error message(s) would help me resolve the issue.

**Comment by yasirkula** [comment]
Possibly fixed in https://github.com/yasirkula/UnityNativeGallery/commit/ba3fbf4f4c2840d6ac2c1e1145ca14b7834660c0
