### ISSUE TITLE
How to use this plugin

### ISSUE THREAD

**Issue by TashaHazel** [yasirkula/UnityNativeGallery#76]
Hello sir have a nice day. I am trying to understand the .readme file to use this plug in but i still do not understand since i still brand new in unity. For your info, i want my project to upload an avatar / user image from choosing their own gallery image by using this plug in. However, i do not have an idea where i can put the script. I try to put in canvas but it pop up an error warning. I hope you will guide me and thanking you in advance sir.

1. i want user click the profile image and they can upload their own image from gallery phone
![image](https://user-images.githubusercontent.com/39523695/66535569-9452b180-eb4c-11e9-8b84-7bfcd821126a.png)

2. Pop up error
![image](https://user-images.githubusercontent.com/39523695/66535633-c8c66d80-eb4c-11e9-8048-1ec2cbe007b5.png)

**Comment by yasirkula** [comment]
Don't try to attach NativeGallery.cs to a GameObject. You need to create a new C# script and call NativeGallery's functions from that script. Here's an example:

```csharp
public UnityEngine.UI.Image image;

public void PickImage()
{
	NativeGallery.Permission permission = NativeGallery.GetImageFromGallery( ( path ) =>
	{
		Debug.Log( "Image path: " + path );
		if( path != null )
		{
			// Create Texture from selected image
			// If the image is larger than 512px, it will be downscaled
			Texture2D texture = NativeGallery.LoadImageAtPath( path, 512 );
			if( texture == null )
			{
				Debug.Log( "Couldn't load texture from " + path );
				return;
			}

			// Create a sprite from the Texture2D
			Sprite sprite = Sprite.Create( texture, new Rect( 0, 0, texture.width, texture.height ), new Vector2( 0.5f, 0.5f ), 100 );
			
			// Assign the sprite to the Image
			image.sprite = sprite;
		}
	} );

	Debug.Log( "Permission result: " + permission );
}
```

Simply assign the Image object in your scene to the Image variable of this component and call the PickImage function whenever you want to change the avatar. For example, you can create a button and add the PickImage function to its On Click event.

**Comment by TashaHazel** [comment]
I already create a new script and paste your codes previously but there is an error on "image" variable. Then, I have tried to change the "image" variable to "profile" according to my image object name.. but there was still an error. Can you explain more about this? I think i might doing wrong because of misunderstanding.

![image](https://user-images.githubusercontent.com/39523695/66672010-dcc6b800-ec8f-11e9-82bd-227a6dbfc3ca.png)


![image](https://user-images.githubusercontent.com/39523695/66671987-cfa9c900-ec8f-11e9-9dcc-b32bdf2584d3.png)

**Comment by TashaHazel** [comment]
Thank you so much sir. It works! However, I have another favor. How to change the image from rectangle to round shape avatar image? Which line code should I change sir? 

![photo_2019-10-12_02-33-44](https://user-images.githubusercontent.com/39523695/66676651-962a8b00-ec9a-11e9-8880-c5cfc07efadd.jpg)

**Comment by yasirkula** [comment]
You can't crop the image in circular shape with NativeGallery but you can apply a mask to the image to make it look like a circle in UI. Simply add a Mask component to the profile Image's parent object and assign a circle sprite to it. For more info: https://docs.unity3d.com/Manual/script-Mask.html

**Comment by TashaHazel** [comment]
Thank you sir for your quick responses. Thanks again for helping me. I wish that you will always success whatever things that you are doing right now and your future :)

**Comment by yasirkula** [comment]
Thank you, you too!

**Comment by TashaHazel** [comment]
Hello sir, there is a problem here. After I upload the image, it successfully appear on my profile image. But after I click "home" icon, then click back "profile" icon, the image was disappeared. I hope you can help me to resolve this and thank you in advance.

![1](https://user-images.githubusercontent.com/39523695/67646552-ac5a6b80-f969-11e9-9497-944ee93fbd8c.jpg)
![2](https://user-images.githubusercontent.com/39523695/67646553-ac5a6b80-f969-11e9-9b33-ebf4a5345e77.jpg)
![3](https://user-images.githubusercontent.com/39523695/67646595-db70dd00-f969-11e9-93df-d9d35c2c59b5.jpg)

**Comment by yasirkula** [comment]
Unity doesn't save your changes to the scene at runtime. Imagine having 3 cubes in a level, destroying one of them and then restarting the level. It would be a disaster if the 3rd cube was gone forever.

You need to File.Copy the original image file to Application.persistentDataPath directory, save its path via PlayerPrefs.SetString. The next time the profile page scene is opened, check if PlayerPrefs.GetString points to an existing image file and if so, load the image via NativeGallery.LoadImageAtPath and assign it to the picture Image.

This is outside the scope of this plugin, so if you get stuck at one point, please use the forums to get help instead: https://forum.unity.com/forums/scripting.12/
