### ISSUE TITLE
HEIC format no longer supported?

### ISSUE THREAD

**Issue by Cybont** [yasirkula/UnityNativeGallery#77]
It looks as though Nativegallery doesn't support HEIC? After the new update, I can no longer pick a HEIC. I used to be able to load all photos into a texture and encode to jpg. Now when they go through my system, they become corrupt.

NativeGallery.Permission permission = NativeGallery.GetImageFromGallery((path) =>
        {
            Debug.Log("Image path: " + path);

            ImageFilePath = path;

            if (path != null)
            {
                pictureTexture = NativeGallery.LoadImageAtPath(path);

**Comment by yasirkula** [comment]
Does `pictureTexture = NativeGallery.LoadImageAtPath(path, 128);` work (for testing purposes)?

**Comment by Cybont** [comment]
Thank you so much for the timely response, it helped a lot! Though our main problem was caused by the NativeGallery.cs script flags the returned texture as non-readable.

**Comment by yasirkula** [comment]
I'm assuming that you've resolved that issue by passing _false_ to LoadImageAtPath's **markTextureNonReadable** property. Was the loadImageAtPath change necessary to resolve the issue or did you leave it as is?

**Comment by Cybont** [comment]
We resolved it by making every texture readable. We kept the changes to NativeGallery.mm. Mostly because it's working, and we don't have time to test if those changes were necessary.

**Comment by yasirkula** [comment]
That's good to hear!
