### ISSUE TITLE
ACTION_MEDIA_SCANNER_SCAN_FILE deprecated

### ISSUE THREAD

**Issue by BrahimHadriche** [yasirkula/UnityNativeGallery#80]
https://github.com/yasirkula/UnityNativeGallery/blob/670d9e2b8328f7796dd95d29dd80fadd8935b804/JAR%20Source/NativeGallery.java#L124

It seems like [ACTION_MEDIA_SCANNER_SCAN_FILE](https://developer.android.com/reference/android/content/Intent#ACTION_MEDIA_SCANNER_SCAN_FILE) got deprecated
```
Callers should migrate to inserting items directly into MediaStore, 
where they will be automatically scanned after each mutation.
```

**Comment by yasirkula** [comment]
On API 29 and later, I do insert items directly into MediaStore, so you can safely ignore that warning: https://github.com/yasirkula/UnityNativeGallery/blob/670d9e2b8328f7796dd95d29dd80fadd8935b804/JAR%20Source/NativeGallery.java#L73-L96

**Comment by BrahimHadriche** [comment]
Oh my bad!

**Comment by kulbeer670** [comment]
i still fail to understand how i can replace it in my code

**Comment by yasirkula** [comment]
This is the source code of NativeGallery.jar, so the code is already there, no action is needed.

**Comment by kulbeer670** [comment]
i got this but i am trying to use it in my app but can not implement it here is the code if you can help with this.
`private void galleryAddPic () {
            Intent mediaScanIntent = new Intent(Intent.ACTION_MEDIA_SCANNER_SCAN_FILE);
            File f = new File(currentPhotoPath);
            Uri contentUri = Uri.fromFile(f);
            MediaStore.MediaColumns.RELATIVE_PATH
            mediaScanIntent.setData(contentUri);
            this.sendBroadcast(mediaScanIntent);
        }`

**Comment by yasirkula** [comment]
This code is already in there: https://github.com/yasirkula/UnityNativeGallery/blob/670d9e2b8328f7796dd95d29dd80fadd8935b804/JAR%20Source/NativeGallery.java#L124-L126. I think you can safely ignore this warning.

**Comment by gaj-programmer** [comment]
It means now after 29, we don't need to send ACTION_MEDIA_SCANNER_SCAN_FILE broadcast?

**Comment by yasirkula** [comment]
According to the [documentation](https://developer.android.com/reference/android/content/Intent#ACTION_MEDIA_SCANNER_SCAN_FILE), yes:

> Callers should migrate to inserting items directly into MediaStore, where they will be automatically scanned after each mutation.

But if android.os.Build.VERSION.SDK_INT is less than 29, I use ACTION_MEDIA_SCANNER_SCAN_FILE instead of MediaStore. Don't know if it is the correct approach, though.

**Comment by CarlitosDroid** [comment]
I was struggling with Android 10 about this issue. Thanks a lot. I decide to use the class NativeGallery(https://github.com/yasirkula/UnityNativeGallery/blob/670d9e2b8328f7796dd95d29dd80fadd8935b804/JAR%20Source/NativeGallery.java#L73-L96) in my Android project. I really appreciate the effort.
