### ISSUE TITLE
Orientation of images not correct for iPhone 6

### ISSUE THREAD

**Issue by FrederikVRDK** [yasirkula/UnityNativeGallery#81]
Hello,

I don't get the correct orientation of images on iPhone 6.
I have not tested **7**, but **8**, **XS** and **iPad** works.

Likewise, no problem on all the Android devices I've tested.

I suspect the exif information might be different for the older iPhones?

Thanks in advance,
Frederik.

**Comment by yasirkula** [comment]
I'm assuming you are using NativeGallery.LoadImageAtPath. If you are testing with images captured via iPhone 6's camera, can you also copy some of iPhone 8's pictures to 6 and see if the problem is caused by iPhone 6's camera or NativeGallery?

**Comment by FrederikVRDK** [comment]
I mailed the pictures to the iPhone 8 and an iPad and both were then rotated correctly.

**Comment by yasirkula** [comment]
Does changing `orientationInt <= 1` to `orientationInt == 1` here affect anything: https://github.com/yasirkula/UnityNativeGallery/blob/670d9e2b8328f7796dd95d29dd80fadd8935b804/Plugins/NativeGallery/iOS/NativeGallery.mm#L483

Are there any meaningful error messages in Xcode console? Are images captured with iPhone 8 displayed correctly on iPhone 6?

**Comment by FrederikVRDK** [comment]
I tried simply taking photos from iPhone 6S following iOS update 13.1.3, orientation was not correct.

I tried sending the photos from the iPhone 8 sent to iPhone 6S, orientation was correct.

Following that, I tried the proposed change on the .mm file. Orientation was correct on iPhone 8, 6S and iPad.

Did not look at XCode console yet as the orientation was shown correctly for me.

Thank you!

**Comment by yasirkula** [comment]
That's nice to hear, thanks for the feedback!
