### ISSUE TITLE
NativeGallery.SaveVideoToGallery is generating 0 bytes files when using existingFilePath

### ISSUE THREAD

**Issue by emongev** [yasirkula/UnityNativeGallery#83]
Title basically says it all.

I generate a video on the persistentDataPath, then use NativeGallery.SaveVideoToGallery to move it to the gallery, however that only causes the original video to disappear, and an empty video 0 bytes video to appear on the save destination.

**Comment by yasirkula** [comment]
I think I've found the issue. But to see if I'm right, can you try saving the video to temporaryFilePath or changing the name of the video in SaveVideoToGallery's filename parameter?

**Comment by emongev** [comment]
@yasirkula So I just tried changing the name of the video, I did have the filename parameter, but it was named the same in both locations. Now I got both videos left in their locations, and both with their full contents!

**Comment by yasirkula** [comment]
NativeGallery doesn't touch the original video, so it should stay as is. About the other video you've mentioned, is it the video in the Gallery (which means saving works properly) or is it the temporary copy of the video created inside persistentDataPath by NativeGallery (which should've been deleted by NativeGallery automatically)? If it is the latter, are there any error messages in logcat?

**Comment by emongev** [comment]
Well before your suggested fix it was deleting my original video which was on the persistent data path of my application. From your question Im guessing it was writing on top of itself (since they were both named the same), then transferring that file to the gallery, effectively deleting the original video, and having a 0 byte file due to writing on itself conflicts perhaps?

With this fix, the video is now registered on the phone, and stored on the "DCIM/App Name" folder, so it is working correctly it seems.

**Comment by yasirkula** [comment]
Yes the issue seems to be fixed. In the next release, I'll store the temporary files in a subdirectory of persistentDataPath, so this workaround won't be necessary anymore.

**Comment by emongev** [comment]
Do you have an ETA on the next release? Just so i can come back and re-download it? :)

**Comment by yasirkula** [comment]
I'm waiting feedback from one other user about another issue. Afterwards, I'll release it.
