### ISSUE TITLE
Not being saved to Gallery in my Android device

### ISSUE THREAD

**Issue by JERINJACOBCHERIAN** [yasirkula/UnityNativeGallery#86]
I am trying to save a screenshot to my gallary,but its not working. Kindly tell me what I am doing wrong.

this is my code

using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;

public class TakeScreenshot : MonoBehaviour {

    public void TakeAShot()
	{
        StartCoroutine(TakeScreenshotAndSave());
    }

    private IEnumerator TakeScreenshotAndSave()
    {
        yield return new WaitForEndOfFrame();

        Texture2D ss = new Texture2D(Screen.width, Screen.height, TextureFormat.RGB24, false);
        ss.ReadPixels(new Rect(0, 0, Screen.width, Screen.height), 0, 0);
        ss.Apply();

        // Save the screenshot to Gallery/Photos
        Debug.Log("Permission result: " + NativeGallery.SaveImageToGallery(ss, "GalleryTest", "Image.png"));

        // To avoid memory leaks
        Destroy(ss);
    }
}

**Comment by yasirkula** [comment]
Please see: https://github.com/yasirkula/UnityNativeGallery#faq

If none of the entries in FAQ help, you should check if there are any meaningful error messages in logcat.

**Comment by JERINJACOBCHERIAN** [comment]
I am using a phone that has no external card, what should I do in such cases?

**Comment by JERINJACOBCHERIAN** [comment]
It was permission issues.My bad.

**Comment by yasirkula** [comment]
This code would always open the Settings, though, I don't think it is feasible. NativeGallery automatically asks for permission when you call SaveImageToGallery unless a) you Deny the permission on iOS or b) you Deny the permission with "Don't ask again" selected on Android. In this case, you need to call OpenSettings, yes. I'd recommend you to change your code like this:

```csharp
if( NativeGallery.RequestPermission() == NativeGallery.Permission.Denied )
    NativeGallery.OpenSettings();
```
