### ISSUE TITLE
Access the android gallery from my app

### ISSUE THREAD

**Issue by BryanJ-97** [yasirkula/UnityNativeGallery#88]
With this plugin is it possible to present the entire gallery within an app?

**Comment by yasirkula** [comment]
If you mean fetching the paths of all images in Gallery without displaying the image picker UI, it is not. You have access to only the images that you explicitly pick in the image picker UI.

**Comment by JERINJACOBCHERIAN** [comment]
I am using a phone that has no external card, what should I do in such cases?
