### ISSUE TITLE
Allow multiple image selection.

### ISSUE THREAD

**Issue by dipen-apptrait** [yasirkula/UnityNativeGallery#9]
Can you please explain the changes i need to do in order to allow multiple images selection?

**Comment by yasirkula** [comment]
It seems impossible using the built-in frameworks on iOS, or at least that is what people say on stackoverflow. So I won't be able to help you with iOS part.

On Android, it can be possible but it will require a "Minimum API Level" of at least 18. If you are OK with these constraints, I'll delve into more detail.

**Comment by dipen-apptrait** [comment]
Yes that's fine. We can work on Android.

**Comment by yasirkula** [comment]
I've updated the plugin.
