### ISSUE TITLE
i exportJar with some modifications and new name, but it told me javaClassNotFound

### ISSUE THREAD

**Issue by CUTEQWQ** [yasirkula/UnityNativeGallery#91]
when using "com.xxx.xxx.NativeGalleryMediaReceiver", xxx is my new package name

**Comment by yasirkula** [comment]
You should change all occurrences of com.yasirkula.unity namespace with the new one in the C# files (e.g. NativeGallery.cs).

**Comment by CUTEQWQ** [comment]
> You should change all occurrences of com.yasirkula.unity namespace with the new one in the C# files (e.g. NativeGallery.cs).

I have done this, and i even change the name to the origin name, but failed... the same error,

**Comment by yasirkula** [comment]
See the FAQ entry regarding ProGuard: https://github.com/yasirkula/UnityNativeGallery#faq. If it doesn't help, I might have to see your NativeGallery Java codes as well as C# codes.

**Comment by CUTEQWQ** [comment]
> See the FAQ entry regarding ProGuard: https://github.com/yasirkula/UnityNativeGallery#faq. If it doesn't help, I might have to see your NativeGallery Java codes as well as C# codes.

Thanks for your help, but i solve it another way with another new package, although i dont know where went wrong
