### ISSUE TITLE
"iOS Project Builder for Unity" Plugin build Errors

### ISSUE THREAD

**Issue by qtghost** [yasirkula/UnityNativeGallery#92]
![IBE](https://user-images.githubusercontent.com/16713354/70120012-7dd95a00-16a6-11ea-9b82-99e89bb00831.png)
hi there,
 I'm using "iOS Project Builder for Unity" Plugin to build IOS project
 the doc said if you using third-party plugins and your error is a header (.h) file not found , you need to supply the relative path.  The problem is , I dont know where to find these .h files

**Comment by qtghost** [comment]
okay I solver it

**Comment by yasirkula** [comment]
How did you solve it?
