### ISSUE TITLE
iOS: selecting image appears but path not complete (no file extension) 

### ISSUE THREAD

**Issue by newbiezuki** [yasirkula/UnityNativeGallery#93]
Hi yasirkula! Thank you so much for this plugin. It has helped loads! I've been working on Android and everything works flawlessy. But now I'm starting on iOS but facing a weird problem. Selecting and getting the image is working but the path given is incomplete? The extension of the image is missing. And this is a problem for us because we want to push the path to a cloud server but it won't accept it cause there is no extension.

In case you'd like to see my script, its the same as your example script

**Comment by yasirkula** [comment]
Seems like PHImageFileURLKey is removed in iOS 13 and I'm guessing that this issue occurs on an iOS 13 device. Can you try inserting `NSLog(@"info - %@", info);` inside the following function and see what it outputs to the console: 

https://github.com/yasirkula/UnityNativeGallery/blob/6854eaffd772e7309fc19f89d8a72b65889f79f0/Plugins/NativeGallery/iOS/NativeGallery.mm#L619-L637

**Comment by asyranamin** [comment]
Hello, ive tried your suggestion and i get this response.
I put the NSlog into here.
![Screenshot 2019-12-21 at 10 28 25 AM](https://user-images.githubusercontent.com/59105221/71301813-1da12280-23df-11ea-8422-cea73393e95a.png)
and saw this in my xcode
![Screenshot 2019-12-21 at 10 28 34 AM](https://user-images.githubusercontent.com/59105221/71301835-3a3d5a80-23df-11ea-9ad8-4a18b25ec02a.png)

does this help?

**Comment by yasirkula** [comment]
Can you try replacing that function as follows:

```objc
+ (void)trySaveSourceImage:(NSData *)imageData withInfo:(NSDictionary *)info {
	NSString *filePath = info[@"PHImageFileURLKey"];
	if (filePath == nil || [filePath length] == 0)
		filePath = info[@"PHImageFileUTIKey"];
		
	if (filePath == nil || [filePath length] == 0)
		resultPath = pickedMediaSavePath;
	else
		resultPath = [pickedMediaSavePath stringByAppendingPathExtension:[filePath pathExtension]];
	
	NSError *error;
	if (![[NSFileManager defaultManager] fileExistsAtPath:resultPath] || [[NSFileManager defaultManager] removeItemAtPath:resultPath error:&error]) {
		if (![imageData writeToFile:resultPath atomically:YES]) {
			NSLog(@"Error copying source image to file");
			resultPath = nil;
		}
	}
	else {
		NSLog(@"Error deleting existing image: %@", error);
		resultPath = nil;
	}
}
```

**Comment by asyranamin** [comment]
ive replaced the code... 
so for the image path, i get the extension, but its .heic. 

Image path: /var/mobile/Containers/Data/Application/64815E33-1D82-4DC1-A21F-2438AB9EB6EE/Library/Caches/pickedImg.heic
<>c__DisplayClass22_0:<PickImage>b__0(String)
NativeGalleryNamespace.NGMediaReceiveCallbackiOS:OnMediaReceived(String)

Im quite new at developing for ios. but are all images in ios saved as heic? no jpeg or png?

**Comment by yasirkula** [comment]
AFAIK, you have to change that setting from the camera app's settings.

**Comment by asyranamin** [comment]
would you be so kind to add the above fix as an update to your native gallery plugin? so future times i pull the native gallery from asset store, the above matter is fixed? XD

**Comment by yasirkula** [comment]
Yes, I definitely will, very soon. Thanks 😄 I'll close this issue after updating the plugin.

**Comment by yasirkula** [comment]
Update should be live soon on Asset Store.
