### ISSUE TITLE
Undefined symbols

### ISSUE THREAD

**Issue by sahilpma** [yasirkula/UnityNativeGallery#94]
![WhatsApp Image 2019-12-22 at 12 39 21 PM](https://user-images.githubusercontent.com/38884892/71318560-5cef7200-24b8-11ea-96d7-3fe0ea0e7b88.jpeg)

I have been using your fantastic asset from past a year. Thank you.
But this time when I was building for iOS, few undefined symbols are giving a error. Please help.

**Comment by yasirkula** [comment]
Have you modified the plugin's source code in any way? Did this issue possibly start occurring after updating the plugin, the Unity version or making another change in the project? Can you check if your Xcode project's Library folder has NativeGallery.mm in it? If not, please try adding it to that folder manually and see if it changes anything.

**Comment by sahilpma** [comment]
![image](https://user-images.githubusercontent.com/38884892/71319827-6d5c1880-24c9-11ea-96f6-87ed0dc94614.png)
Not included it seems

**Comment by sahilpma** [comment]
reimported package in unity, and it works. Thanks for your support.
