### ISSUE TITLE
Get paths of pictures located in given folder

### ISSUE THREAD

**Issue by ValentinChareyre** [yasirkula/UnityNativeGallery#97]
Hello,

I have just discovered your nice plugin and I want to have an "in-app gallery".

I use `NativeGallery.SaveImageToGallery` to save a texture to a given album and now, I would like to display all the pictures from this same album. I don't want to call the native image picker, I just want to get the paths of my images in order to display them in my application.

Something like:

```csharp
public static string[] GetPathsOfImages( string album )
```

Do you think it could be possible?

Thanks in advance.

**Comment by yasirkula** [comment]
It is not possible to fetch the path of the saved images; you may want to save a copy of the images to Application.persistentDataPath to achieve this behaviour.

A quote from the forum thread explaining why the paths can't be retrieved:

> On iOS, these files are stored in an internal directory that we have no access to (I don't think there is even a way to fetch that internal path), on Android, with Storage Access Framework, the absolute path is hidden behind the SAF-layer. There are some tricks here and there to convert SAF-path to absolute path but they don't work in all cases (most of the snippets that can be found on Stackoverflow can't return the absolute path if the file is stored on external SD card).

**Comment by ValentinChareyre** [comment]
I am not experienced with native development, but iOS has the [PhotoKit](https://developer.apple.com/documentation/photokit) with several functions to retrieve albums and photos inside those albums.

And this [Stackoverflow question](https://stackoverflow.com/questions/4195660/get-list-of-photo-galleries-on-android) seems to offer solutions to access the photos in the gallery

**Comment by yasirkula** [comment]
I'm already using PhotoKit (PHAsset, PHAssetCollection etc.), but there is no way to fetch a path using PhotoKit. The Stackoverflow question uses the following code the fetch the path: `absolutePathOfImage = cursor.getString(column_index_data);` where column_index_data is `cursor.getColumnIndexOrThrow(MediaColumns.DATA);`, which is [deprecated](https://developer.android.com/reference/android/provider/MediaStore.MediaColumns#DATA). Even if it still returns a raw file path at the moment, it is no longer possible to access that file via System.IO.File API, it will just throw a security exception.

**Comment by ValentinChareyre** [comment]
If there is a way to directly return the `byte[]` instead of the path, I am perfectly fine with this 😄

**Comment by yasirkula** [comment]
Probably possible but that would require some research that I don't want to conduct 😕

**Comment by gilgil28** [comment]
Is there any way of loading all images saved? I want to show a galley of saved images (from within Unity).

**Comment by yasirkula** [comment]
NativeGallery doesn't keep track of the saved images, sorry.

**Comment by Merichbier** [comment]
I have a question which is somehow related to this thread.
We are using your library to save a picture. We would like to implement a share feature then and I was wondering why you don't return somehow the path of the picture that was just saved. Since we can retrieve this path using the GetImageFromGallery method, I have the feeling this should be possible no ?

**Comment by yasirkula** [comment]
Please see FAQ for why no path is returned: https://github.com/yasirkula/UnityNativeGallery#faq

GetImageFromGallery copies the source image to Application.temporaryCachePath using native functions because paths of the source images are inaccessible.
